### ISSUE TITLE
One split one thread

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#100]
**This is low priority**

We might get better performance by allocating only one thread per split.
The idea would then to read the target amount of docs (5M) in memory, and have
a single thread indexer start working on its indexing.

Several splits would be working at the same time. Each one with a single thread.
With enough RAM, this could reduce or even remove the need for merges.

**Comment by fmassot** [comment]
As we have now one thread per indexer, it seems that we can close this issue.
