### ISSUE TITLE
Define and enforce naming convention for index ID, source ID, ...

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1007]
`[a-zA-Z0-9_-]{1,255}` ?

Following https://github.com/quickwit-oss/quickwit/pull/1272/files we need to make sure that source_id do not contain any of the kafka group_id unallowed characters, or fix the kafka source.

**Comment by fmassot** [comment]
no dots?

**Comment by guilload** [comment]
Periods are fine with me.

FYI, the field names regex is
`[_a-zA-Z][_\.\-a-zA-Z0-9]`.

Maybe we could use the same naming convention everywhere so that there's only one rule to remember. I also suggest we start with something restrictive first, that can revisit to be more lenient later.

**Comment by PSeitz** [comment]
dots could conflict to address nested documents.

e.g. `index_config.search_settings.default_search_fields`

**Comment by fulmicoton** [comment]
Is this already fixed?
