### ISSUE TITLE
Specify and implement a generic way of overriding config parameters

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1011]
For instance:
`quickwit service run searcher --config-override node-id=my-node-id searcher.listen-address=0.0.0.0`
or
`QW_NODE_ID=my-node-id QW_SEARCHER:LISTEN_ADDRESS=0.0.0.0 quickwit service run searcher`.

This is just an example. Let's discuss whether we support overrides through CLI and/or env variables, priority between overrides, syntax, implementation.

Food for thoughts:
https://materialize.com/docs/cli/#command-line-flags
```
if a command line flag takes an argument, you can alternatively set that flag via an environment variable named after the flag. If both the environment variable and command line flag are specified, the command line flag takes precedence.

The process for converting a flag name to an environment variable name is as follows:

Convert all characters to uppercase
Replace all hyphens with underscores
add an MZ_ prefix.
For example, the --data-directory command line flag corresponds to the MZ_DATA_DIRECTORY environment variable.
```

**Comment by fulmicoton** [comment]
Addressing a similar use case...

We could do string interpolation with the environment variables and have people define their own template.

**Comment by PSeitz** [comment]
If we support both, then the priorities should be:
* cli
* env
* config

But a generic solution with clap may be not so easy.

**Comment by fulmicoton** [comment]
Developing on my previous comment as it was a bit too succinct.

We could let users reference environment variables in their config.

For instance:

quickwit.yaml

```yaml
rest_listen_port: ${REST_LISTEN_PORT}
```

We can use an off-the-shelve template engine, pick the environment variable dictionary and do the render quite simply.
It is easy to implement, and perfect for the k8s use case at least.

**Comment by fulmicoton** [comment]
Developing on my previous comment as it was a bit too succinct.

We could let users reference environment variables in their config.

For instance:

quickwit.yaml

```yaml
rest_listen_port: ${REST_LISTEN_PORT}
```

We can use an off-the-shelve template engine, pick the environment variable dictionary and do the render quite simply.
It is easy to implement, and perfect for the k8s use case at least.

If we go this route (it has my votes), it would probably require displaying the resolved conf in the admin interface to let people debug.
