### ISSUE TITLE
[QUESTION] Do we want to keep the CachingDirectory with unlimited capacity?

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1012]
I'm wondering if it would be better to limit the size of this caching layer. We have set `fast_field_cache_capacity` to `10G` by default `split_footer_cache_capacity` to `1G` by default.

**Comment by fulmicoton** [comment]
The caching directory contains the data required to run a query. It is very  , We cannot really limit it. What we can do is limit the number of concurrent split. We considered limiting the concurrency based on this memory usage and judged against it.
