### ISSUE TITLE
Index and query field existence

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1039]
We should be able to store and query null values to enable filtering on null (or non-null) values.

**Comment by fulmicoton** [comment]
I suggest we emit a term to mark the presence of a field.

Something similar to exists query.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html

We could add something in the query language.
Maybe a question mark or something.

has(statusCode) AND body="hello"

**Comment by PSeitz** [comment]
We could also consider to store a `BitVec` per field.

Since there is some cost associated with that feature it should maybe configurable.

**Comment by fulmicoton** [comment]
My rule of thumb is 1/6.
If you have more than 1/6 docs in the posting list, BitVec is good. 
Below a posting list approach is nicer.
