### ISSUE TITLE
empty string is not a valid Metastore URI

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1061]
and should therefore be rejected.

Same for `default_index_root_uri`

**Comment by ddelemeny** [comment]
@fmassot @fulmicoton : while I'm in the quickwit-config area, I could close this one if it's still relevant, and add tests for different combinations of config entries.
Is there more detail to add to this issue ? How does it tie-in with #1137  ?

**Comment by fulmicoton** [comment]
@ddelemeny sorry for the super late reply. 

Unfortunately my brain is not super fresh on these subjects.
I think I created this issue after getting a paper cut while testing quickwit.

Please do as you see fit.
