### ISSUE TITLE
FileSourceParams validation mess

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1065]
Right now the model for the FileSourceParams allows for an empty filepath. This 
is interpreted as StdIn.

This piggy back is useful in the ingest CLI, but harmful when we deserialize a config.
We have a bunch of checks to void this.

We should probably make this Option a filepath, and 
create a specific source type for StdIn. We also want to somehow prevent the serialization of this source type.

# Solution?

We could introduce an extra `SourceParams` called stdin.
We can prevent its deserialization, serialization or not (the story holds for Void as well).

The StdIn filesource would get a different factory from the file source, but that new factory would produce the same source type.

**Comment by fulmicoton** [comment]
Move to quickwit 0.5

**Comment by rdettai** [comment]
Note: currently the validation is happening in 2 places:
- https://github.com/quickwit-oss/quickwit/blob/97889f61dbc3f72ce468506870792f833eeb482b/quickwit/quickwit-serve/src/index_api/rest_handler.rs#L710-L716
- https://github.com/quickwit-oss/quickwit/blob/97889f61dbc3f72ce468506870792f833eeb482b/quickwit/quickwit-config/src/source_config/serialize.rs#L82-L89
