### ISSUE TITLE
Root should check and validate the query against the last schema

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1086]
Right now the schema is a notion that is local to a split.

This is a good thing, because it will allow us to change the schema in the future (provided we are careful with the merging logic).

However, because of that, a lot of invalid queries are only spotted at the leaf level, resulting in strange errors with bad error code.

We want to validate the query against the current schema before dispatching the query to the leaves.

Should address #1014, #1016 #1082

**Comment by fulmicoton** [comment]
Assigned it to me but to reserve this ticket, but that's actually for Linh.

**Comment by linxGnu** [comment]
IMHO, I think we could close this issue now. HDYT

**Comment by fulmicoton** [comment]
Thank you @linxGnu !
