### ISSUE TITLE
ingest cli leaves us with splits in cache

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1099]
The ingest CLI gives a little bit of a misleading experience.
We keep the split in the split cache after the ingestion has terminated.

Maybe we should add a CLI option to force a cleanup?

**Comment by fmassot** [comment]
This is annoying indeed. I'm in favor of adding an option like `--clean-cache`.

**Comment by dai-dao** [comment]
I can take this on :)

**Comment by fulmicoton** [comment]
That sounds awesome @dai-dao!

**Comment by dai-dao** [comment]
I'm still working on this , the code is a quite deep to go through

**Comment by fulmicoton** [comment]
Awesome :) thank you
