### ISSUE TITLE
The curl install throws an error

### ISSUE THREAD

**Issue by larksoftware** [quickwit-oss/quickwit#1116]
**Describe the bug**
I tried to use the curl install but it just throws an error:
```
$ curl -L https://install.quickwit.io | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134  100   134    0     0    375      0 --:--:-- --:--:-- --:--:--   374
sh: 199: Syntax error: "(" unexpected (expecting "fi")
 87 15202   87 13253    0     0  23965      0 --:--:-- --:--:-- --:--:-- 23965
curl: (23) Failure writing output to destination
```

**Steps to reproduce (if applicable)**
1. Run the curl command
2.

**Expected behavior**
App would get installed

**System configuration:**
Release version (or git SHA-1), OS, ...
Pop!_OS 21.10

**Additional context**

**Comment by evanxg852000** [comment]
@larksoftware we will look into this but it seems your bash environment does not support some constructs used in the install script.
You can try `curl -L https://install.quickwit.io | bash` in the meantime.
We will investigate the offending bash syntax.

**Comment by larksoftware** [comment]
I don't know if it makes a difference but I run `zsh`.  That said I would think the shebang would send it to the proper shell.
