### ISSUE TITLE
Root should that it will be able to run the user request against the last schema

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1118]
This is the follow up of #1086 .

We now check that the Query makes sense according to the last schema.
However the collection part might still trigger an error. Right now it is catched at the leaf level.

We would like to make sure at the root level that building the collector and running search
should work normally.

**Comment by linxGnu** [comment]
@fulmicoton I think it's ok to assign to me. Will take a look at it today. Thank you very much.

**Comment by linxGnu** [comment]
@fulmicoton I have checked collector handling and I think it looks good. Maybe, I am not fully understand what you intend to do with this issue. Could you please guide me more.

Anw, I also make a small PR for tiny optimization and handling fruits/responses. PTAL: https://github.com/quickwit-oss/quickwit/pull/1121

**Comment by fulmicoton** [comment]
Duplicate of #1086  and solved in https://github.com/quickwit-oss/quickwit/pull/1106
