### ISSUE TITLE
Broken Installation script

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#1125]
Quickwit is installed using the command `curl -L https://install.quickwit.io | sh`.
However, the install script this URL (https://install.quickwit.io) is pointing at is not correct. It's pointing to the version v0.2.0 tag which has been updated because of the repo movement.

Few options:
- Create a new release containing the updated install script & redirect (too heavy) 
- Create a custom tag/branch that contains the updated install script & redirect
- Just redirect to the install script located in `main` branch (assuming we won't change this file at least till next release :roll_eyes:  )

**Comment by guilload** [comment]
I'm actually in favor of 1. I'd like to release `2.1` built with Rust `1.58.1`, which contains a major security fix. We should get in the habit of releasing more often. This is an opportunity to build that muscle. Are we missing some automation pieces?

**Comment by evanxg852000** [comment]
@guilload  No we are not missing any automation and all should be good. The change was just minor for me but yeah the security issue is actually a good point. Besides I have changes to the script to avoid the `sh` unsupported syntax of list.

**Comment by fmassot** [comment]
> Create a new release containing the updated install script & redirect (too heavy)

I don't understand what it means. Where is located the install script?

**Comment by evanxg852000** [comment]
@fmassot I had thought we currently have work-in-progress features in the main branch, so the plan here was to create a separate branch only containing the fixes we need.  It seems we are good with `main`. We will release 0.2.1 and change the redirection back to `https://raw.githubusercontent.com/quickwit-oss/quickwit/v0.2.1/install.sh`

**Comment by fmassot** [comment]
can we close this issue?

**Comment by fulmicoton** [comment]
@evanxg852000 can we close this issue?
