### ISSUE TITLE
There is no example of restful boolean operator in the documentation

### ISSUE THREAD

**Issue by sangensong** [quickwit-oss/quickwit#1130]
Hi. I want to try boolean operate in quickwit's restful search, but I'm not sure what I'm doing is right. 
So please author can provide an example of Boolean Operators search, like **AND, +, OR, NOT and -**. thank you!
    Below is my approach:
#### OR
```sh
curl "http://0.0.0.0:7280/api/v1/gh-archive/search/stream?query=body:It+OR+seems+OR+like+OR+frontend+OR+might&fastField=id"
```
#### AND
```sh
curl "http://0.0.0.0:7280/api/v1/gh-archive/search/stream?query=body:It+seems+like+frontend+might&fastField=id"
```

**Comment by fulmicoton** [comment]
@sangensong Thanks for the report! We'll address that in the next version.

You approach is correct, except for the `body:` field specifier.
You need to repeat it for every term, or alternatively, you can use the `searchField` query parameter 
as defined in https://quickwit.io/docs/reference/rest-api
