### ISSUE TITLE
`default_index_root_uri` and the `metastore_uri` default values always refers to `~/qwdata` value

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1137]
Currently, the default data dir is set to `~/qwdata`.
Moreover we use this default value to set also the `default_index_root_uri` and the `metastore_uri`.

But if you set `data_dir` to a different value, `default_index_root_uri` and the `metastore_uri` will still use `~/qwdata`. This is not what we want. `default_index_root_uri` and the `metastore_uri` should use `data_dir` defined by the use.

**Comment by ddelemeny** [comment]
Possible approaches:

### Option<> config item and getter method
Remove the default values from the `QuickwitConfig` struct and add getter methods which will return a user-set config item if any or a default value computed from `data_dir`
Pros:
- looks simple
Cons:
- creates an inconsistent way to access a particular config field

### Option<> config item and Quickwit::load augmentation
Remove the default values from the QuickwitConfig struct and populate missing values with their computed default after deserialization (in QuickwitConfig::load)
Pros:
- looks simple
- doesn't create an inconsistent API to access config fields
Cons:
- required field is an Option
- QuickwitConfig::load is not guaranteed to be called ?

**Comment by fmassot** [comment]
There is a 3rd option where you add a new intermediary struct that will be used to populate missing values and validation potentially.

As of today, I'm in favor of option 1 because:
- I'm expecting various changes in the coming months on this object so I would prefer to keep everything in one struct for now
- the cons of having some methods to access specific fields sounds acceptable, I don't think a developer will be confused by that
- validation that is missing today is still easy to add, for example with [Keats](https://github.com/Keats/validator).

**Comment by ddelemeny** [comment]
I see a potential 4th option using struct flattening and custom ser/deserialization, but it's somewhat convoluted and I haven't found any example proving the feasibility of this variant.
