### ISSUE TITLE
Add support for tantivy third party tokenizers in the doc mapping

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1139]
# Description
Currently, we support only the "default" tokenizer. But there are many third party tokenizers available:
- Chinese ([tantivy-jieba](https://crates.io/crates/tantivy-jieba) and [cang-jie](https://crates.io/crates/cang-jie))
- Japanese ([lindera](https://github.com/lindera-morphology/lindera-tantivy), [Vaporetto](https://crates.io/crates/vaporetto_tantivy), and [tantivy-tokenizer-tiny-segmenter](https://crates.io/crates/tantivy-tokenizer-tiny-segmenter))
- Korean ([lindera](https://github.com/lindera-morphology/lindera-tantivy) + [lindera-ko-dic-builder](https://github.com/lindera-morphology/lindera-ko-dic-builder))

# Simple solution

If third party tokenizers are not too heavy, we could add them to the crate.

 # Non trivial solution

Ideally, we would want to let the user add his tokenizers on his own quickwit instance.

**Comment by fmassot** [comment]
let's do it!

**Comment by guilload** [comment]
Closed via #3575 and #3608.
