### ISSUE TITLE
Scuttlebutt integration

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1141]
I have started integrating ScuttleButt into quickwit cluster and here are few things I need your take on.
- Currently  in quicwit, we have  Cluster::leave  ? I am not quiet sure i understand it's role since it's exposed on the GRPC service I would have expected to have a join method as well since the node is still kept around.  In ScuttleButt we already have the same concept as shutdown that gracefully stops the node. 
- To make quick progress, I am using pulling to keep the members list up to date in Quickwit, A stream that broadcast only member changes is needed ScuttleButt::membership_change_receiver(&self)
- We need to settle on what NodeId is https://github.com/quickwit-oss/scuttlebutt/issues/1  I am in favor of this suggestion NodeId{uniq_id, listen_udp_addr, generation} 
On the last point, we will need somewhere to store last-know generation , use it when restarting. I am thinking this makes our node statefull

**Comment by fulmicoton** [comment]
> Currently in quicwit, we have Cluster::leave ? 

You can remove it for the moment if it is tricky to implement.
The RPC call is actually quite useful. For instance, if you want to upgrade one node, or just replace it, you might want for a node to report that it is leaving the clustering to avoid any disruption. 


 - To make quick progress, I am using pulling to keep the members list up to date in Quickwit, A stream that broadcast only member changes is needed ScuttleButt::membership_change_receiver(&self)

This makes sense. The stream is only here to notify events isn't it? It does not send elements does it?

- For the last point, can you write a little design doc on what your NodeId implies... What happens when a node leaves and rejoins the cluster etc.

**Comment by evanxg852000** [comment]
>The RPC call is actually quite useful. For instance, if you want to upgrade one node, or just replace it, you might want for a node to report that it is leaving the clustering to avoid any disruption.
Then I think the shutdown method in ScuttleButt does the same. (We might need a chat around this)

> The stream is only here to notify events isn't it? The channel contains () or Vec<Member>
Yes only reporting the change with a `Vec<Member>` to that Quickwit::Cluster::update_memebers

> For the last point, can you write a little design doc on what your NodeId implies... What happens when a node leaves and rejoins the cluster etc.
Sure

**Comment by fulmicoton** [comment]
@evanxg852000 can we close this?
