### ISSUE TITLE
Fix Rustdoc links and add step to CI to check them. 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1152]

**Comment by RishiKumarRay** [comment]
can you elaborate this please i would like to go for it

**Comment by fulmicoton** [comment]
Hello @RishiKumarRay That would be awesome!

So if you run `cargo doc`, it generates a documentation which contains inner links.
Today we get a lot warning saying those links are broken.

This ticket is about fixing the link and add a step to the CI to detect broken links  in the future.
We use github actions for the CI.

If the CI stuff is difficult, fixing the existing  links would be greatly appreciated.
