### ISSUE TITLE
[question] can quickwit be used to index and search a static website/blog and can it do so without javascript?

### ISSUE THREAD

**Issue by Jieiku** [quickwit-oss/quickwit#1154]
To further elaborate on my question. I have seen a couple search engines that can be used to search static websites but they require that javascript is enabled. (so if you have noscript browser extension installed the search will not work.)

I am wondering if quickwit can be used to index and search a static website (zola)

I would want to add a search box to the static website and have it function without having any javascript enabled in the browser.

I could not actually find an example website search using quickwit or I would have tested this myself.

If this is possible using quickwit please let me know. I really appreciate the response.

**Comment by fulmicoton** [comment]
Unfortunately no. This is out of the scope of quickwit.
