### ISSUE TITLE
Kinesis as a Source

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1157]
We want to add support of Kinesis as a possible source. 

You can check the module documentation and the Source trait documentnation here.
https://github.com/quickwit-oss/quickwit/blob/main/quickwit-indexing/src/source/mod.rs

Some work has already been started along those lines:
https://github.com/quickwit-oss/quickwit/tree/main/quickwit-indexing/src/source/kinesis

The logic should end up being very close to that of Kafka.
https://github.com/quickwit-oss/quickwit/blob/main/quickwit-indexing/src/source/kafka_source.rs

Localstack can be used for testing.

**Comment by guilload** [comment]
#1194
