### ISSUE TITLE
HOUSEKEEPING: get [GitHub verified] badge for quickwit-oss org

### ISSUE THREAD

**Issue by rimutaka** [quickwit-oss/quickwit#1162]
GitHub provides organizations with a special "verified" badge to tell them apart from clones, fakes and imposters. It would be good if https://github.com/quickwit-oss/ had one as well. This verified status shows up in API details for the org to help secure the supply chain at the org level.

#### Example

![image](https://user-images.githubusercontent.com/5926028/157780000-d9e4e0bb-260c-4b96-afe0-fb214bf9a297.png)

Org owners (either @guilload or @shikhar) need to go to https://github.com/organizations/quickwit-oss/settings/domains and add a TXT record generated on that page. It shouldn't take you more than 5 min all up if you have access to your Route53.

**Comment by guilload** [comment]
Thanks for the suggestion and instructions @rimutaka. I'll work on this in the next few days.

**Comment by fulmicoton** [comment]
We are now veriifed.
