### ISSUE TITLE
Fix REST, gRPC, and UDP ports config

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#1191]
The previous cluster implementation could not allow us to share node ports.
Now we can use scuttlebutt to let other nodes know what is our gRPC port.

The Specs are as follow:
- REST,  Gossip (udp),  and gRPC ports are configured from the configuration file.
- REST port has a hardcoded default value that can be overridden from the configuration file.
- gRPC and gossip (UDP) ports default values are computed from the RESP port.
- A client node should use scuttlebutt to know the gRPC port of its peers.

Also, expose a `ClusterState` method via the `ClusterService` gRPC service. This method should display the cluster state from a node's perspective in JSON format.

**Comment by fulmicoton** [comment]
Closing...
