### ISSUE TITLE
Update docs for the Search REST API

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1198]
The search REST API docs are not up to date with the new aggregation endpoint.

To do after #1197

**Comment by fmassot** [comment]
I'm reopening this issue as the aggregation are not yet documented.

@dzvon do you want to take care of that too?

**Comment by dzvon** [comment]
Sure, I'll give it a look.

**Comment by fmassot** [comment]
@dzvon aggregations are not a string :)
 
Here is an example based on one test: https://github.com/quickwit-oss/quickwit/blob/02e8455c2e4e68ac316f5e147ddeef25cf9cfc86/quickwit-cli/tests/cli.rs#L263-L291

You have another example here: https://github.com/quickwit-oss/tantivy/blob/141b9aa2455549b50d5a61896a5416f1be1d191d/src/aggregation/agg_req.rs#L31-L45

This issue is not as easy as it seems, writing the docs accurately for aggregations can be hard. You can also have a look at elasticsearch docs as the API should be the same.
