### ISSUE TITLE
"Indexed in <float> min"

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1203]
After ingest via the cli we display a duration with a silly format.

```Indexed 5032105 documents in 7.38min.```

That's not how humans like to read time. Also adding thousands separator would be nice for the number of docs.

```Indexed 5,032,105 documents in 7 min 23 secs.```

would be nicer.

**Comment by dzvon** [comment]
Maybe we can take advantage of this (https://github.com/time-rs/time/commit/0a3cf3ce5295400a6fcb5b03c340f05ca6555901), if this commit is released.

**Comment by fulmicoton** [comment]
@dzvon Wow you are omniscient.
