### ISSUE TITLE
Distributed queue for the push API [design]

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1209]
Quickwit 0.3 will introduce a PushAPI.

Currently Quickwit does not have distributed indexing. The PushAPI just add records to a local queue implemented in RocksDB, and data loss may occur if the indexing node hard disk is lost.

We need to design how our indexing queue could be distributed. The problem is tightly related to #1208. We can assume a leader node is maintained and is able to dispatch the work amongst a set of indexing nodes.

This ticket is about describing in detail how the queue of our PushAPI should be implemented.
- The permanent node of should not result in the loss of any data.
- The system must scale to 1000 different indices.
- The system must scale to 100 indexing nodes.

- See #1208 
- See replication in LogDevice / Kafka / Pulsar

My hunch: We can rely on the control plane to define, for each index, a set of 2 nodes that will act as a leader / follower and perform synchronous replication. 
Clients get the current leader from the control plane.
If the leader fails, the follower is declared the new leader by the control plane.
*Devils hide in the details*
...

**Comment by guilload** [comment]
We've designed a solution for distributed ingestion and indexing. Design docs are currently on Notion, but we will eventually commit them to our internal docs.
