### ISSUE TITLE
Binaries packaging broken

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#1219]
Nightly builds broken on musl build and need to be fixed.
Most likely a docker image update with Rockdbs dependencies (LLVM)

https://github.com/quickwit-oss/quickwit/actions/workflows/publish_nightly_packages.yml

**Comment by fulmicoton** [comment]
Closing: same discussion in  #1221

**Comment by evanxg852000** [comment]
@fulmicoton Re-opening this as we need to fix the binaries build for Rcksdb inclusion libs
