### ISSUE TITLE
PushAPI Source

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1235]
We need a push api source

**Comment by evanxg852000** [comment]
looking at this, my guess is that we need a source that takes as input the HTTP request body and emits batch of docs. 
I am starting to think it could probably be better to have the elastic specific parsing in a dedicated source `ElasticBulkApiSource` rather than having it in the endpoint handler. WDYT?

**Comment by fulmicoton** [comment]
I think we need 2 rest API endpoint.
- One compatible with elastic batch endpoint.
- One that just takes ndjson
We then need to store the data in rocksdb, one doc per record, in a way that is agnostic of the rest ingest endpoint. 

We then need a single source.

**Comment by evanxg852000** [comment]
Currently, I am making push service (Mailbox<PushApiService>) a member of source.
```rust
pub struct PushApiSource {
    push_api_mailbox: Mailbox<PushApiService>,
   ...
}
```

Making it not possible to get an instance of `Mailbox<PushApiService>`  inside  
```rust 
impl TypedSourceFactory for PushApiSource {
      async fn typed_create_source(params: PushApiSourceParams, checkpoint: SourceCheckpoint,) {
           .... 
      }
```

@fulmicoton couple of solutions:
- Make the push_api_mailbox globally available via a function 
- Not support constructing the source via config (I don't think end-user needs to see/configure this). Do not implement `TypedSourceFactory` at all if that is the case
- Accept the Queues path and Open a Readable RockDB instance from PushApiSource, (very clunky)

I was in favor of solution (2) but you said we might need it to be able to instantiate `PushApiSource` via Factory.

**Comment by fulmicoton** [comment]
> I was in favor of solution (2) but you said we might need it to be able to instantiate PushApiSource via Factory.

Just to clarify. This is not me doing overengineering here. I think we do need a factory to spawn an indexing pipeline, so you might need right after this ticket. 
You can double check that statement by doing a find usage.

It should lead you to these lines.
https://github.com/quickwit-oss/quickwit/blob/main/quickwit-indexing/src/actors/indexing_pipeline.rs#L384-L386

Solution one seems to be the only one possible.

Actix does that as part of the framework, offering a register for a specific class of service actors (that can be instantiated without  extra params). Fetching an actor can then spawn them in a lazy manner if they are not there.
We might add in the future too.

For the moment, can you add two method in the push-api crate that returns such a singleton.

```rust
pub fn init_push_api(queue_path: &Path) -> anyhow::Result<()> {
   // ...
}

pub fn get_push_api_service() -> Option<Mailbox<PushApiService>> {
  // ...
}
```

Or something like that.
The reason I think we cannot just have one method is that  we need to know the queue path for instanciation.

(Of course, this is just one solution and possibly not the best one.) 

The painful thing here is unit testing. By introducing that kind of singleton, unit tests are not nice independent unit anymore.

**Comment by evanxg852000** [comment]
No, you are not over overengineering, validating this decision was quite important for me in other aspects: In which appropriate crate to place the push_api_source in. Besides, having this conversation makes sure we are on the same line. After writing the test, I also found it was not as obvious as I thought for plugging the Source then I started exploring what you said.
