### ISSUE TITLE
Implement a Push REST API

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1239]
We want a rest push api :)

Actually we probably want 2 apis.
One compatible with elastic's bulk api, and one specific to quickwit.
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

Quickwit is append-only so the "verbs" (index/create) is meaningless for quickwit...
we want to treat both as a new document.
We also want to return an error if an unsupported operation is sent in the bulk API. (e.g delete)

**Comment by evanxg852000** [comment]
@fulmicoton @fmassot 
1. Right now I think a separate bulk API for Quickwit might not be needed as this could be done by the ingest API.
My reasoning is that we support `append-only` operation so there is no need to have the same API spec as elastic bulk API.
2. For the elastic bulk API, we want to specify how the source input should be structured for the operations: create, update and delete. right ?

**Comment by evanxg852000** [comment]
Regarding certain error handling, it would have been nice to have RocksDB transactions available in the wrapper crate we are using :disappointed: . 
I think we will have to `undo` when an error occurs (ugly). 
There is `WriteBatch` but I am concerned about making a bunch of `create_cf` atomic which is not available on `WriteBatch`
There is a PR but not sure it's gonna land soon https://github.com/rust-rocksdb/rust-rocksdb/pull/565

**Comment by fulmicoton** [comment]
> 2. For the elastic bulk API, we want to specify how the source input should be structured for the operations: create, update and 
   delete. right ?
   
Just return an error for update/delete, and treat both create and index like a create.

**Comment by fulmicoton** [comment]
```
Regarding certain error handling, it would have been nice to have RocksDB transactions exposed from the wrapper crate we are using disappointed .
I think we will have to undo when an error occurs (ugly).
There is WriteBatch but I am concerned about making a bunch of create_cf atomic which is not available on WriteBatch
There is a PR but not sure it's gonna land soon https://github.com/rust-rocksdb/rust-rocksdb/pull/565
```

@evanxg852000 For the moment let's not add this complexity.

First, this is only a concert for the ES API. We have only one possible targetted in a single ingest call with the regular API.
Second, we need to progress on #1229 , but I suspect atomically creating  of cf is not much of a problem.

I suspect we can get away with:
The metastore is the single source of truth for the existence or the inexistence of an index.
cf are created and opened lazily upon the first ingestion after a restart.

On an elastic compatible bulk request, we first create or open all of the required cf, and then ingest with a WriteBatch.
One of the create_cf might fail but we don't care... This is not an effective "state".
