### ISSUE TITLE
Ensure we do not need to manually create the  pushapi source.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1310]

**Comment by evanxg852000** [comment]
Any details?

**Comment by fulmicoton** [comment]
All indexes should come with a PushAPI source per default one way or another, and users should not have to set it up.
There are different ways to make that work.

That's related to your ticket about the lifecycle of the pushapi so it might come for free as a side effect of what you do there, but I preferred to add an extra ticket to make sure we don't oversee that in 0.3.

**Comment by fulmicoton** [comment]
Addressed by #1343
