### ISSUE TITLE
Default value for config filepath

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1339]
The quickwit config filepath should default to `./config/quickwit.yaml`.

In other words, the value should be populated from the first of the following option:
- config CLI value
- ENV variable
- ./config/quickwit.yaml

**Comment by guilload** [comment]
What about additionally looking for a config file in `$HOME/.quickwit`, the same way the AWS CLI (in `$HOME/.aws`) and `kubectl` (in `$HOME/.kube`) do?

**Comment by fulmicoton** [comment]
I don't think it is a good idea for quickwit.

**Comment by guilload** [comment]
Here's the full story I had in mind. I wanted to pave the way for defining multiple configurations in `~/.quickwit` where each config is linked to a named profile. This allows for switching between configurations and clusters easily.

This is how I handled working in multiple AWS environments in the past. The default profile points to the dev env to avoid errors and I was switching between envs with `--profile <profile name>` or `AWS_PROFILE=<profile name>` for longer sessions. Kube has a similar mechanism called "context".

I thought this mechanism would be convenient for working with multiple quickwit clusters. 

[Named profiles for the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html).

Just food for thought for future releases.
