### ISSUE TITLE
Some commands fail with `Data dir does not exist.` when the data dir is actually not needed

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1352]
**Describe the bug**
Some commands fail with `Data dir does not exist.` when the data dir is actually not needed. This affects almost all read-only commands.

**Steps to reproduce (if applicable)**
1. Create index with Postgres metastore
2. Run `split list --config config/quickwit.yaml --index my-index`

**Expected behavior**
The command should succeed and display an empty list of splits.

**Comment by fulmicoton** [comment]
I don't think we need to fix that.

We have two paradigms here.
- current paradigm: quickwit CLI is meant to be run from its directory.
- next paradigm: quickwit  CLI targets the API of a running quickwit server.

**Comment by guilload** [comment]
I agree. Moving to an API-based CLI makes my point moot. Are we going to get rid of `quickwit index ingest`, though? I like the ability to append data to an index from the CLI without needing a server.

**Comment by fulmicoton** [comment]
Ingest from a CLI or a spark job to populate is awesome. The current implementation is not great though, as it does not coordinate itself with any existing server to decide who should do merges.
