### ISSUE TITLE
Discord link on website has expired invite

### ISSUE THREAD

**Issue by oaustegard** [quickwit-oss/quickwit#1374]
**Describe the bug**
Discord link on website has expired invite:
![image](https://user-images.githubusercontent.com/3268739/166941492-3f870e81-b24d-4daf-adc3-aaf54f5ba33b.png)

**Steps to reproduce (if applicable)**
1. Go to https://quickwit.io/
2. CLick Discord link in either header or footer: https://discord.gg/MT27AG5EVE

**Expected behavior**
Quickwit's Discord to launch

**Configuration:**
Please provide: 
1. Output of `quickwit --version`:  NA
2. The index_config.yaml: NA

**Comment by oaustegard** [comment]
That's the same I used, so hmmm... and the other link also doesn't work.  Looks like a beed between Discord and me:
![image](https://user-images.githubusercontent.com/3268739/166958991-34a38fbf-2676-4519-9aff-8ffc36d6be24.png)

Feel free to close - or heck - I'll close it.

**Comment by maximkpa** [comment]
It could also happen if you have more than 100 discord servers on your Discord account. I believe they have a limit of 100. But this one is rare. Let us know, maybe we could look more into it!

**Comment by oaustegard** [comment]
Nah, this had to do with some weird login state of mine; once I logged out, reverified my account, jumped on one leg while I swung a sacred chicken over my head and chanted discord, discord, discord, I was able to log in to Discord and after that the invite link worked. Sorry for the red herring.
