### ISSUE TITLE
"/" should serve the admin

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1383]
Right now "/" is not a valid route on our HTTP server.

One has to type `HOSTNAME:PORT/ui/` to get an admin UI.

/ should give back index.html.
all of the static content should only be accessible under ui/ or static/ (or whatever)

**Comment by kstaken** [comment]
Could I make a suggestion that you maybe have `/` return a JSON metadata representation with information about the deployed system. This is a really handy pattern for services deployed in larger environments and helps with infrastructure introspection and usability, especially when you have numerous instances of the same service.  Along with information about the deployed service, versions and such it could also include a field with information about the UI path to make it discoverable.

**Comment by guilload** [comment]
> all of the static content should only be accessible under ui/ or static/ (or whatever)

I personally prefer the latter: `static`.

**Comment by fulmicoton** [comment]
So to clarify. 

We serve the UI and the API on the same port.
I was saying to serve the UI index.html on "/",
and have the UI serve as a way to document the UI.

Francois already added UI links at the bottom of the UI pages to 
show what API calls are made.

We could have this a  cluster conf & cluster state api endpoint on `api/`.

I'm ok to discuss having it on `/` but I feel hosting the UI is better there.

Opinions @kstaken @guilload ?

**Comment by fmassot** [comment]
I tend to agree with `index.html` at the root. The rationale would be: all our API endpoints have the prefix `/api` so why not use the root for the UI.

**Comment by fmassot** [comment]
I'm rethinking serving the UI at the root.

The UI has currently 5 routes:
- `/`
- `/search`
- `/indexes`
- `/indexes/:indexId`
- `/clusters/members`

Like we isolated the API URLs, I think doing the same for the UI makes sense. 

Moreover, as you said, the UI will not be the primary way and I would expect in the future the root endpoint to return a JSON containing some information about the version/build.

As for now, I think a simple redirect '/' -> '/ui' would be convenient for our short-term goal of "smoothen the user journey.".

**Comment by fulmicoton** [comment]
Redirect is good enough
