### ISSUE TITLE
Isolate elasticsearch compatible endpoints with a common prefix 

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1395]
We could use the prefix `/api/v1/elasticsearch` like:
- `/api/v1/elasticsearch/_bulk`
- `/api/v1/elasticsearch/{index}/_mapping`
- `/api/v1/elasticsearch/_msearch`

I see 2 pros:
- specific elasticsearch endpoints are isolated
- we can later think about having an endpoint `/api/v1/elasticsearch` that you set into Grafana or into other tools with an elasticsearch backend

**Comment by kstaken** [comment]
You might want to consider using a more generic name like `/api/v1/compat` or shorten it to `/api/v1/es`  to avoid building around a name owned by Elastic Inc. 

Also there is a coming increase in divergence between Elasticsearch and Opensearch which will likely impact this in the future. Elasticsearch it self is no longer Open Source and it remains to be seen how this plays out, but there are going to be client and API differences fairly soon and Elastic is showing signs of being fairly aggressive in breaking client compatibility with Opensearch which would almost certainly affect this too if Elastic's client is used by a tool like Grafana. I suspect most Open Source tools are going to end up switching to an Opensearch client fairly quickly.

**Comment by fmassot** [comment]
Done, it's `api/v1/_elastic` since 0.6.
