### ISSUE TITLE
Add Kafka example

### ISSUE THREAD

**Issue by gnufree** [quickwit-oss/quickwit#1397]
How to configure Kafka source, obtain data and create index

**Comment by fmassot** [comment]
Hi @gnufree, good point. We have only one example [here](https://quickwit.io/docs/reference/cli/#source-add) but we need a tutorial on that.

**Comment by gnufree** [comment]
I've seen this. I don't know how to apply it after adding the source

**Comment by gnufree** [comment]
Without this step：quickwit service run indexer --indexes wikipedia --config=./config/quickwit.yaml

**Comment by guilload** [comment]
Hello @gnufree, I've just committed a [tutorial](https://github.com/quickwit-oss/quickwit/blob/main/docs/tutorials/kafka.md) for Kafka. Hopefully, this helps. Let me know if you have more questions regarding configuring/using a Kafka source with Quicwkit.
