### ISSUE TITLE
FileBackedMetastore not up to date when index is deleted

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#1399]
The FileBacked Metastore has caching mechanism for lazily loading the metastore file. When an index is deleted, it is not reflected in the metastore even when pooling is activated on that metatstore file. 

**Steps to reproduce**
1. configure filebacked meatsrore with pooling `s3://quickwit-dev/foo#polling_interval=30s`
2. Create an index and start the indexing server
3. Index a batch of data to create a split. (can be skipped)
4. Open another terminal and delete the index
5. The Metastore will still see the splits from the last know index. This can be noticed from the GarbageCollector actor in the pushAPI indexing pipeline
6. Pooling the Metastore file for new content will fail with `FetchError`

**Expected behavior**
In the last step of the reproduction, the metastore should remove the know the index is deleted and remove itself.

Related to cleaning up of object in https://github.com/quickwit-oss/quickwit/issues/1229

**Comment by evanxg852000** [comment]
After investigating, the pooling works, `30s` is just too long, especially when running one of the indexer or searcher services.
@fulmicoton WDYT?  if we introduce a default `polling_interval` we still don't prevent the actors from discovering the index is suddenly gone before the metastore pooling task has ran (when a user set a longer pooling interval).

**Comment by fulmicoton** [comment]
Ah right. When we delete splits, we are saved by the grace period. But when we delete index, we don't benefit from that unfortunately.

I think this will be a non-fix for the moment.

**Comment by fulmicoton** [comment]
Closing as won't fix.
