### ISSUE TITLE
Add tests on push REST API

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1408]
I did not see any test on the REST API.

**Comment by fmassot** [comment]
@fulmicoton I would prefer to do this for the 0.3.1

**Comment by fulmicoton** [comment]
ok

**Comment by fmassot** [comment]
Fixed by commit [cd6e158](https://github.com/quickwit-oss/quickwit/commit/cd6e15822a1640ce512fdd6ef2da70d0d857c394)
