### ISSUE TITLE
The installation XP is not really nice when the user disovers lately that some dependencies are needed

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1422]
Currently we have a poor dev XP during the installation phase:

```
./quickwit-v0.2.1/quickwit: error while loading shared
libraries: libpq.so.5: cannot open shared object file: No
such file or directory
```

We could check if dependencies are missing, we can also push ahead the use of docker files or improve the docs too.

**Comment by fulmicoton** [comment]
@fmassot updated the docs. Eventually we should simply get rid of the postgresl drive deps by switching to sqlx for instance.
