### ISSUE TITLE
Improve (or just check) that tutorial with "search on AWS S3" shows how to set correctly the AWS env

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1423]
For example, we can make sure that AWS S3 is reachable from the instance by using the AWS CLI to:
- check the bucket existence
- make a put / delete a file to ensure everything is working well

**Comment by guilload** [comment]
Closed via 2f514ebca5bb4e979356b0b76426c51ae7b3ab0a.
