### ISSUE TITLE
Push API - Add mechanism to check status

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#1442]
### Issue Outline

The Push API  currently returns the number of docs received, but this does not mean the documents are indexed, they are merely stored in the rocks-db.

It could be that the documents had a wrong format or other errors. Currently there is no way for the user to know the status of committed documents, except checking the server logs or check if they appear in search.

### Async API design

The Push API is essential a async API. A typical pattern for async APIs is to return an id handle to the user with status code 202 when the documents have been securely stored. This handle can then be used to check the actual status of the submitted documents.

The endpoint to check could be a plain http returning some status in json, or websocket-like [server sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events).

Async API pattern: https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply

**Comment by guilload** [comment]
See #3743 insead.
