### ISSUE TITLE
Debounce block fetch in docstore

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1467]
Right now when fetching N documents after a search, there are no mechanism to make sure we do not attempt to download the same block over and over.

A possibility could be to debounce read calls at the storage layer.
Another possibility could be to group by blocks, but that will require to expose internals.

**Comment by PSeitz** [comment]
Also may make sense to combine adjacent blocks into a single request

**Comment by fulmicoton** [comment]
That would be even nicer... although are cache won't liek that at all.

**Comment by guilload** [comment]
@PSeitz, can we close this issue?

**Comment by PSeitz** [comment]
Yes that's finished
