### ISSUE TITLE
Quickwit can't support Elasticsearch _bulk `create` semantics

### ISSUE THREAD

**Issue by kstaken** [quickwit-oss/quickwit#1525]
I saw in the documentation for the Elasticsearch _bulk ingest API that the only method that is supported is `create` however I believe Quickwit can't actually implement the semantics required for `create`. The action it should be supporting is `index`. 

`create` is used when you want to store a document only if it doesn't already exist in the index. It's a really handy operation but without the ability to quickly tell what docs already exist it can't be implemented correctly.

`index` simply indexes the document. Note: if `_id` is provided to the request this will also be semantically incorrect as that tells ES to reindex and replace the document but in Quickwit it will result in a duplicate document being indexed.

**Comment by fulmicoton** [comment]
confirmed

**Comment by evanxg852000** [comment]
@fmassot  should switch to `index` and document?
