### ISSUE TITLE
Query on no fields does not return an error for dynamic mapping

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#1526]
Query on dynamic mapping without default search fields and the query itself also defining no search fields returns an empty result instead of an an error

```
mode: dynamic

➜  aggregation_doc git:(aggregation_doc) curl -sS 'http://localhost:7280/api/v1/air_quality_no_ff_s/search?query=a'
{
  "num_hits": 0,
  "hits": [],
  "elapsed_time_micros": 1906,
  "errors": []
}⏎

mode: lenient
➜  aggregation_doc git:(aggregation_doc) curl -sS 'http://localhost:7280/api/v1/air_quality_no_ff/search?query=a'
{
  "InvalidQuery": "No default field declared and no field specified in query"
}⏎
```

**Comment by evanxg852000** [comment]
@fulmicoton 
I don't think it's good to use the `_dynamic` field in search query 
https://github.com/quickwit-oss/quickwit/blob/main/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs#L483-L485

at least from our first design, even base on the comment here
https://github.com/quickwit-oss/quickwit/blob/main/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs#L95-L97
Did we change our approach?

**Comment by fulmicoton** [comment]
I'm not sure what you mean exactly?

**Comment by fulmicoton** [comment]
So if you are in the `_dynamic` mode, the fields that are not mapped end up in the `_dynamic`  field.

We add it as a default field, so that you can search them naturally.

Did you observe an incorrect behavior?
