### ISSUE TITLE
num_ingested_docs is incorrect on REST ingest API

### ISSUE THREAD

**Issue by kstaken** [quickwit-oss/quickwit#1553]
Using the REST ingest API the num_ingested_docs returned appears to always be 1 instead of the number of docs in the request. 

```
curl 'localhost:7280/api/v1/noaa-1m/ingest' -d @./data/noaa-10000-filtered.json
{
  "num_ingested_docs": 1
}
```

In this case I would have expected it to be 10,000

**Comment by fmassot** [comment]
@kstaken I had the same issue, it works with this command:
```
curl 'localhost:7280/api/v1/noaa-1m/ingest' --data-binary @./data/noaa-10000-filtered.json
```

**Comment by fmassot** [comment]
From the curl man page on '-d' argument:
```
Posting data from a file named from a file like that, carriage returns and newlines will be stripped out.
```

**Comment by fmassot** [comment]
I made this same mistake and discovered the same bug as you in #1551

**Comment by kstaken** [comment]
Grr, --data-binary, I always forget about that.
