### ISSUE TITLE
Link to the nightly build binaries on the main-branch docs

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1585]
On quickwit.io, the `main-branch` install docs points to the latest release binaries. It could be nice to point to the nightly binaries.

**Comment by evanxg852000** [comment]
@fmassot RIght now I think the easiest to do is to have a Nighlty build section in the  docs with the links, because if we want to have the current install docs for main and release, we will have to change our install script, and possibly the helm install to support nightly

**Comment by fmassot** [comment]
It's possible with docusaurus to make a section optional and I think we should be able to get the `version` and have an if statement.
