### ISSUE TITLE
Timestamp based search

### ISSUE THREAD

**Issue by mr-karan** [quickwit-oss/quickwit#1614]
**Is your feature request related to a problem? Please describe.**

If this tool is meant for log analytics, I'd like to be able to search for all entries based on "timestamp". 

**Describe the solution you'd like**
A `from` and `to` field (as datetime dropdowns in the UI) will be useful to have.

**Describe alternatives you've considered**

Currently, I don't think there's a way to query with time.

**Additional context**
-

**Comment by guilload** [comment]
Hi @mr-karan,

Quickwit does support "time-based" search: the search API endpoint has two parameters `start_timestamp` and `end_timestamp` for this purpose ([docs](https://quickwit.io/docs/reference/rest-api#get-parameters)). The also UI features a datetime picker.

Is there something that we can make clearer in the docs and/or README?

**Comment by fmassot** [comment]
Note: timestamp filtering is activated in the UI only if the index has a `timestamp_field`.

**Comment by fmassot** [comment]
With the screenshot

<img width="1440" alt="screenshot-timestamp-dropdown" src="https://user-images.githubusercontent.com/653704/172461017-a9ebfbf0-356e-40ab-9b77-5ff9c0e1af35.png">

**Comment by fmassot** [comment]
ok! Then I think the quickstart should include an example with timestamp, let's close this one and open an issue on that.
