### ISSUE TITLE
copy pasting the API urls at the bottom of the pages in the UI do not work

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1628]
at least on my computer....

I am on linux/brave.
The copy paste buttons on github are working fine.

**Comment by fulmicoton** [comment]
Ooooh it was probably the http va https problem then. I was running on localhost.

**Comment by evanxg852000** [comment]
There are plenty of sloppy workaround like `prompt("Copy to clipboard: Ctrl+C, Enter", text)` but the modern and nice way has this restriction on the web API for security. The only exception is when running on localhost.
We can probably detect when standard browser API is not applicable and do a workaround or at least gray out (disable) the button

**Comment by fmassot** [comment]
Or maybe put a `href` with `target="_blank"`
