### ISSUE TITLE
HTTP method not allowed for wrong json

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#1632]
Any additional fields on the json request returns "HTTP method not allowed"
```
➜  quickwit-indices curl -X POST -H "Content-Type: application/json" \
                            -d '{"query":"body:cliid", "does not exist": true}' \
                            http://127.0.0.1:7280/api/v1/hdfs/search
{
  "error": "HTTP method not allowed"
}⏎
```

Ignoring the field or returning an error with the unrecognized field would be better.

**Comment by fulmicoton** [comment]
We get this error if a query parameter is wrong too!

```
> curl "http://127.0.0.1:7280/api/v1/oom/search?query=p004&sort_by_fiel=toto" 

{                                                                                                                              │Run query 1360
  "error": "HTTP method not allowed"                                                                                           │[ec2-user@ip-172-31-12-46 oom]$ ../oom/target/release/oom 14000000000 | ./quickwit index ingest --index oom                   
}
```

**Comment by fmassot** [comment]
Yes, the way warp handles rejection does not help us here. What we want is:
- try to match a route with an URI + method
- if it matches, validates query parameters and/or payload and on error return an appropriate response
- if it does not match, find another route

Today using rejection leads to ugly code (see `recover_fn` function) and it would be nice to clean that.

I saw two interesting threads on the subject:
- a PR https://github.com/seanmonstar/warp/pull/909 that can help clean the code
- discussion about how to handle rejection property https://github.com/seanmonstar/warp/issues/388

I'm pushing a simple PR to fix the problem.

**Comment by sunisdown** [comment]
> try to match a route with an URI + method
> if it matches, validates query parameters and/or payload and on error return an appropriate response
> if it does not match, find another route

Totally agree.  It seems that the error returned by `serde_qs` can't be handled by warp.
