### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [quickwit-oss/quickwit#1651]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know). This kind of information is important for the end-users.

The only thing that I have found - info about prebuilt binaries. But prebuilt binary that is not the same as supported architecture. If in your case it it is - please write a note about it somewhere in the documentation.

Thanks in advance!

**Comment by fulmicoton** [comment]
We should probably find a place where to put that information but... 

We officially only support Linux, also it should work on Freebsd and MacOS too.
We support x86-64  and ARMv7.

On x86-64, we do not require the use a recent CPU but not having SSSE3 will have
a strong impact on performance (we detect the presence of the instruction set at runtime).

On ARMv7, quite frankly I don't know. I can only say we do not use NEON explicitly yet,
and I assume rustc is conservative in its default, but I am not sure.

**Comment by zamazan4ik** [comment]
That is fine. Just put this information into the documentation. And if in the future architecture requirements will be changed, do not forget to update it :)
