### ISSUE TITLE
Cause: Last checkpointed offset `2692` is greater or equal to high watermark `42`

### ISSUE THREAD

**Issue by chenjinlei1122** [quickwit-oss/quickwit#1653]
**Describe the bug**
can't index from kafka 
the error is as follows:
```
2022-06-20T06:26:01.726Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=71000}: quickwit_indexing::actors::indexing_pipeline: Error while spawning indexing pipeline, retrying after some time. error=Failed to create source `source-kafka` of type `kafka`. Cause: Last checkpointed offset `2692` is greater or equal to high watermark `42`.

Caused by:
  Last checkpointed offset `2692` is greater or equal to high watermark `42`. retry_count=26 retry_delay=600s
```

**Configuration:**
Please provide: 
1. quickwit 0.2.1
2. The  trace.yaml
```
version: 0 # File format version.
index_id: trace
doc_mapping:
    field_mappings:
        - name: id
          type: u64
          fast: true
        - name: raw_content
          type: text
          tokenizer: default
          record: position
search_settings:
    default_search_fields: [raw_content]

sources:
    - source_id: source-kafka
      source_type: kafka
      params:
          topic: ua
          client_params:
              bootstrap.servers: 127.0.0.1:9092
              group.id: FullText
              security.protocol: PLAINTEXT
```

**Comment by fmassot** [comment]
Hi @chenjinlei1122, thanks for the report.

First, I'm wondering why you are still using the 0.2.1, the `trace.yaml` indicates a format only compatible with the 0.3. 

Concerning the error `Last checkpointed offset `2692` is greater or equal to high watermark `42`. retry_count=26 retry_delay=600s`, Quickwit indicates an inconsistency between the last checkpoint offset in Quickwit which is `2692`, and the last offset in Kafka `42` (high watermark is the higher offset of messages that are fully replicated).

When starting Quickwit, it will consume messages from the offset of the last checkpoint offset, which means from `2692`, this means that you have already indexed some data with Quickwit which produced a split that contains this checkpoint offset.
But the high watermark or HM is lesser than this offset which is not normal: now Quickwit expects to retrieve message from an offset that is higher than the highest offset. It can come from the fact that you delete/create the same topic or if you have reset the offset of that topic.

**Comment by chenjinlei1122** [comment]
that's right， thanks for your repley
