### ISSUE TITLE
index create --overwrite should be more clearly indicated as a destructive operation

### ISSUE THREAD

**Issue by kstaken** [quickwit-oss/quickwit#1666]
**Describe the bug**
We needed to update the configuration on an existing index and one of my engineers pointed out the --overwrite option to index create as a possible way to do it. We both read the description in the CLI help but not the online docs and neither of us realized that it meant it completely overwrites the index including removing all existing data. We had just expected it to overwrite the index configuration. 

This blew away about 5 billion records, no big deal since we're just testing QW anyway but was a bit of a surprise.

**Expected behavior**
At a minimum the CLI description should be clearer that it's a destructive operation. `Completely overwrites the pre-existing index including removal of all existing data.`

Also since this is a CLI command may be worth considering prompting for confirmation along with another option to explicitly accept the prompt if you needed to script the behavior.

**Comment by fmassot** [comment]
True, thanks for reporting that.

I opened a PR here https://github.com/quickwit-oss/quickwit/pull/1696

**Comment by guilload** [comment]
François' PR was merged, closing.
