### ISSUE TITLE
Split sizes in the metastore appear to be incorrect

### ISSUE THREAD

**Issue by kstaken** [quickwit-oss/quickwit#1667]
**Describe the bug**
The split sizes stored in the metastore appear to be incorrect and result in over reporting on the size of the data in the UI and other places where the size is surfaced. 

Split as reported by Quickwit

```
  {
    "split_state": "Published",
    "update_timestamp": 1656028266,
    "version": "1",
    "split_id": "01G69FGNK6G5STF596PAV60RCR",
    "num_docs": 11616042,
    "size_in_bytes": 9520864939,
    "time_range": {
      "start": 1655915049,
      "end": 1655939291
    },
```

Object size in Object storage.

```
2022-06-23 23:50 3276823007   s3://quickwit/indexes/rc_test_v1/01G69FGNK6G5STF596PAV60RCR.split
```

**Comment by fulmicoton** [comment]
This size is the original size of your documents payload, not the size of the splits.
We did a proper rename in the code but not in the serialization.

It would also be nicer to have both.
