### ISSUE TITLE
Broken `make fmt` - license check has been deprecated from Rust nightly

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1673]
See https://github.com/rust-lang/rustfmt/issues/5103

We need to find an alternative to do license check.

**Comment by fmassot** [comment]
I did not find an alternative in rust.
We can either:
- having a custom `build.rs` like in this project https://github.com/AleoHQ/snarkOS/pull/1807
- create a small crate that does the job.

I'm in favor of option 2.

**Comment by guilload** [comment]
There used to be `license-check` and `license-fix` commands in the Makefile based on this [tool](https://github.com/apache/skywalking-eyes), which was clunky in my opinion but somewhat got the job done. We can reinstate those commands.

**Comment by fmassot** [comment]
yes, good idea

**Comment by saroh** [comment]
You could use diff for `licence-check` + patch + cleanup diffs in `license-fix`. 
```bash
$ diff <(sed 's/{\\d+}/2022/' .license_header.txt) <(head -n 19 quickwit-search/src/lib.rs)
1c1
< // Copyright (C) 2022 Quickwit, Inc.
---
> // Copyright (C) 2021 Quickwit, Inc.
```

**Comment by fulmicoton** [comment]
The previous tool sucked. I tried to package @saroh's diff solution into a bash script. It seems decent enough.
