### ISSUE TITLE
Rework docs fetching

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#1690]
#### One Searcher per Document
- Potentially excessive amount of searchers
- We never hit the docstore cache 
- We cache all uncompressed data from fetching docs (e.g. 10_000 hits all in different blocks -> 1MB blocks -> 10GB)

#### Decompression running on tokio thread:
- 1MB Block -> Decomp 2000MB/s
less than 0.1ms: should be fine

####  Unlimited Cache, when fetching documents.
- All compressed data is cached (e.g. 10_000 hits all in different blocks -> 0,2MB blocks -> 2GB)

## Design
Ideally we decompress a block only once, and limit the amount of caching.
- Use a single searcher
- Remove unlimited cache on `open_index`
- Debounce inflight requests
    - Order fetched docs by docid
    - Set docstore cache to number of parallel requests, so that requests on the the same block always hit the cache

### Alternative Design
Instead of de-bouncing inflight requests, we could expose the doc store checkpoint API. But the docstore reader lives on the segment level which is not exposed usually.

**Comment by fulmicoton** [comment]
Does decompression really works linearly or does it have a startup cost? A quick measurement would be nice (I have never coded one of those)

Also this is a no-op point, but we might want to advise Kimbro to use smaller block for its default.

**Comment by PSeitz** [comment]
lz4 doesn't have a startup cost, but zstd has some, since it creates decompression tables for huffman trees (up to 32kb) and sometimes for ans. It's probably neglibible, but we should test it.
