### ISSUE TITLE
Make it possible to sort by doc in presence of a timestamp field

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1694]
Right now the search API makes it psosible to select the sort field.
If it is not there , the default is
- to sort by the timestamp field if any
- to return docs sorted by `(split, doc_id)` if there are not timestamp field.

Sorting by doc id is really lighter and can be useful  even in presence of a timestamp field.

We could keep the current default, but make it possible to explicitly sort by field if 
the value of `sort_by_field` is empty, ie `sort_by_field=`.

**Comment by fmassot** [comment]
Can't find the piece of code where we sort by timestamp by default. I checked by searching on 2 splits generated by the hdfs logs dataset with no sorting and saw unsorted results.
