### ISSUE TITLE
Does it support chinese tokenizer or custom tokenizer?

### ISSUE THREAD

**Issue by lingo-xp** [quickwit-oss/quickwit#1737]
**Describe the solution you'd like**
Is there any plan to support chinese tokenizer?  I just check the document , but find it doesnt support it now. Maybe we can supprt custom tokenizer as plugin, Just like what did in ES.

**Comment by fulmicoton** [comment]
We don't have any plugins at the moment, but a company already requested  different language tokenizers so we can probably add chinese too.

I however cannot speak Chinese.
Do you know a good chinese tokenizer in rust?

tantivy already supports  jieba-rs (via https://github.com/DCjanus/cang-jie) and Lindera (https://github.com/lindera-morphology/lindera-tantivy)

**Comment by fmassot** [comment]
@lingo-xp we have just merged a chinese tokenizer #2008 

Does this new feature suit your needs?

**Comment by fmassot** [comment]
Closing, @lingo-xp don't hesitate to reopen it.
