### ISSUE TITLE
Support data transformation in quickwit for `queue` sources

### ISSUE THREAD

**Issue by sunisdown** [quickwit-oss/quickwit#1740]
**Is your feature request related to a problem? Please describe.**
The data in kafka(or some sources else) has it's format, but maybe the format is not supported by Quickwit. before we consume the data with quickwit, we need to transform the data and fit it into quickwit format

**Describe the solution you'd like**
We can add a transform layer in quickwit, and consume the predefined format and transform the data into Quickwit supported format

**Describe alternatives you've considered**
We can also do the transform outside quickwit, use systems like `Vector`

**Comment by guilload** [comment]
Closing in favor of #2077.
