### ISSUE TITLE
Avoid fetching timestamp fast field when there is no sorting on this field nor filtering

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#1744]

**Comment by kstaken** [comment]
As an addendum to this, the system should also only load fast fields when absolutely needed. I believe currently they are fetched in a `warmer` process before the data selection occurs but on large scale queries, where many splits will produce no results, that will result in fetching a large amount of unneeded data and kill the effectiveness of the fast field cache.

The same also applies if a split only returns a single result, even if the query asks for sorting, a single result is already inherently sorted and fast fields aren't needed for that split unless required by other operations.

**Comment by fmassot** [comment]
> I believe currently they are fetched in a warmer process before the data selection occurs but on large scale queries

True. When #1745 will be merged, we will prefetch the timestamp fast field only if we need to filter values. NB: we are already pruning splits that have no overlap between the requested time range and the split time range, in this case, no prefetch is done.


> The same also applies if a split only returns a single result, even if the query asks for sorting, a single result is already inherently sorted and fast fields aren't needed for that split unless required by other operations.

This may be hard to do as we don't know in advanced the result. We plan to work on fast fields codecs as we know to be more efficient (for sparse fast fields for example), looking at Parquet format can be interesting as we can apply filtering on blocks and thus reduce the number of bytes to fetch. This is still in discussion and we don't know yet when we will work on that.

**Comment by fmassot** [comment]
Partly closed by #1749 

Issue #1748 is tracking another optimization that we can make.

Closing.
