### ISSUE TITLE
Avoid filter when the entire split is within the timestamp bounds

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1748]
If we search for `[ta, tb)` and the split meta informs us that the split's timestamp are within the  `[tA..tB]` range,
with  `[tA..tB] ⊆[ta, tb)`  there is no need to do any filtering.

This issue is not entirely straightforward, because the split meta are not passed in the leaf requests.

One possibility might be to get the meta from the fast field and make sure those metadata are added into the hotcache if it is not there yet.

The logic must be implemented for the search **and** search stream.

**Comment by fulmicoton** [comment]
@fmassot following your PR. I think I misunderstood one of your comment, and said otherwise. Apologies if you already created a similar ticket.

**Comment by trinity-1686a** [comment]
> This issue is not entirely straightforward, because the split meta are not passed in the leaf requests.

since #3254, we have access to slightly more split meta in leaf requests, notably the time range. It should make this ticket easier to implement (this is true only for "normal" search, not search stream)
