### ISSUE TITLE
If a S3 compatible endpoint is defined, parsing the region from the `QW_S3_ENDPOINT` takes precedent to reading from `AWS_REGION` environment variable.

### ISSUE THREAD

**Issue by laurids-reichardt** [quickwit-oss/quickwit#1757]
**Describe the bug**
If a S3 compatible endpoint is defined, parsing the region from the `QW_S3_ENDPOINT` takes precedent to reading from `AWS_REGION` environment variable. As discussed on discord and according to the Quickwit doc, this should work the other way around: [https://quickwit.io/docs/reference/storage-uri#region](https://quickwit.io/docs/reference/storage-uri#region)

This currently blocks using S3 compatible object storage like Cloudflare R2, which do not specify a region in their S3 compatible URL but won't accept the default `qw-custom-endpoint` region as well: [Cloudflare R2 bucket region](https://developers.cloudflare.com/r2/platform/s3-compatibility/api/#bucket-region)

**Steps to reproduce (if applicable)**

1. Set appropriate env variables:
```
❯ export QW_S3_ENDPOINT=https://<accountid>.r2.cloudflarestorage.com; \
export AWS_ACCESS_KEY_ID=XXX; \
export AWS_SECRET_ACCESS_KEY=XXX; \
export AWS_REGION=auto
```
2. Quickwit doesn't use region `auto` but  `qw-custom-endpoint` during ingest:
```sh
...
2022-07-11T22:29:55.384Z  INFO sniff_s3_region:region_from_env_variable: quickwit_storage::object_storage::s3_compatible_storage: Setting AWS Region from environment variable. env_var_key="QW_S3_ENDPOINT" env_var="https://xxx.r2.cloudflarestorage.com"
2022-07-11T22:29:55.385Z  INFO sniff_s3_region: quickwit_storage::object_storage::s3_compatible_storage: set-aws-region region=Custom { name: "qw-custom-endpoint", endpoint: "https://xxx.r2.cloudflarestorage.com" } from="env-variable"
---------------------------------------------------
 Connectivity checklist  ✔ metastore
 ✖ storage
 ✔ .cli-ingest-source
---------------------------------------------------
 Error Details 

 ✖ storage
Request ID: None Body: <Error><Code>InvalidRegionName</Code><Message>The region name &apos;qw-custom-endpoint&apos; is not valid. Must be &apos;auto&apos;</Message></Error>
```

**Expected behavior**
Quickwit should use region `auto` as set in the `AWS_REGION` environment variable.

**Configuration:**
Please provide:

1. Output of `quickwit --version`:
```
❯ ./quickwit --version
Quickwit 0.3.1 (aarch64-unknown-linux-gnu 69eb7db7c 2022-06-22)
```

**Comment by fmassot** [comment]
Closed by #1758
