### ISSUE TITLE
Add support for snippetting.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1789]
Tantivy offers a way to return a sample of the documents that contains some passage containiing the matched keywords.

It would be nice to add this feature to quickwit's API.

**Comment by evanxg852000** [comment]
I would go with 
- Rest: `https://quickwit-host/api/v1/hdfs/search?query=body:foo&snippet_field=body`
- Cli: .quickwit index search --query "body:foo"  --snippet_field body

The following checks need to happen during search: 
- does snippet_field appear in the query or part of the default search fields?
- is snippet_field of field type that supports snippeting (text,..)
- Serialise the snippet
