### ISSUE TITLE
Install File Download Faild and  glibc 2.17 not support

### ISSUE THREAD

**Issue by yangshike** [quickwit-oss/quickwit#1808]
1. install faild ( instal llink)
#curl -L https://install.quickwit.io | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134  100   134    0     0    125      0  0:00:01  0:00:01 --:--:--   126
100 15266  100 15266    0     0   5537      0  0:00:02  0:00:02 --:--:-- 22156

                                   Q U I C K W I T
                                      Installer

--------------------------------------------------------------------------------
Website: https://quickwit.io/
Docs: https://quickwit.io/docs/
--------------------------------------------------------------------------------

>>> Downloading Quickwit via https://github.com/quickwit-oss/quickwit/releases/download/v0.3.1/quickwit-v0.3.1-x86_64-unknown-linux-musl.tar.gz
>>> command failed: downloader https://github.com/quickwit-oss/quickwit/releases/download/v0.3.1/quickwit-v0.3.1-x86_64-unknown-linux-musl.tar.gz quickwit-v0.3.1-x86_64-unknown-linux-musl.tar.gz

--------------------------------------------------------------------------------

curl: (22) The requested URL returned error: 404 Not Found

2、 when i download the tar file. but i got 
 ./quickwit
./quickwit: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./quickwit)
./quickwit: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./quickwit)
./quickwit: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./quickwit)
./quickwit: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./quickwit)
my system  glibc version is 2.17
 can i  install with source code ,and build myself?

**Comment by fulmicoton** [comment]
@evanxg852000 Our install script does refer to the musl build but we seem to not create such binaries.

@yangshike I'm afraid you will have to build quickwit on your own.
You willl need to clone quickwit and run 
```
cargo build --release --features release-feature-set
```

On ubuntu I think you will need the following dependencies
```
libssl-dev
llvm
clang 
cmake
```

**Comment by yangshike** [comment]
Thank you very much!
Unfortunately, I use CentOS
i install llvm/clang/cmake from source code，Finally, it failed！！！

#cargo build --release --features release-feature-set
...
...
error: failed to run custom build command for `librocksdb-sys v0.6.1+6.28.2`

Caused by:
  process didn't exit successfully: `/usr/local/quickwit-0.3.1/target/release/build/librocksdb-sys-1762e0184363836a/build-script-build` (exit status: 101)
  --- stderr
  rocksdb/include/rocksdb/c.h:45:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found
  rocksdb/include/rocksdb/c.h:45:9: warning: #pragma once in main file [-Wpragma-once-outside-header], err: false
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found, err: true

I think I'll wait for you to release the binary version。

**Comment by evanxg852000** [comment]
@fulmicoton I will the appropriate error message since don't provide musl for the time being.
@yangshike It's exactly because of RocksDB build issue we stopped making musl builds for the time being. We will give another, hopefully, the tooling (cross) now has good support for it or at a workaround. With the appropriate libraries, you should be able to solve the header issue but you end up with a linker error. 
Our build script uses cross with this custom image https://github.com/quickwit-oss/quickwit/blob/main/build/cross-images/x86_64-unknown-linux-musl.dockerfile
```
cross build --release --features release-feature-set --target x86_64-unknown-linux-musl
```

**Comment by fulmicoton** [comment]
GLIBC 2.17 is 10 years old. I'm afraid we won't be able to support your OS @yangshike .
