### ISSUE TITLE
Improve the routing key DSL

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1814]

**Comment by guilload** [comment]
You mentioned supporting something like `(hash(fields) mod n)` in another issue.  This feature is usually called bucketing and is often implemented outside of partitioning (Hive, Spark, ...). I don't think we have to support this now. I'd be happy with simply supporting multiple fields as a partition key.

**Comment by fmassot** [comment]
I believe this has been solved by #2553.
