### ISSUE TITLE
Support for U256 and I256 field types

### ISSUE THREAD

**Issue by machete-michael** [quickwit-oss/quickwit#1830]
**Is your feature request related to a problem? Please describe.**
I am dealing with cryptocurrencies and need support for UInt256. Without this support, I can’t even ingest JSON with values larger than U/I64.

**Describe the solution you'd like**
Support for U/I256 integer types

**Describe alternatives you've considered**
I tried ingesting values as text but that resulted in an ingestion error because it is not text

**Additional context**
N/A

**Comment by PSeitz** [comment]
> I tried ingesting values as text but that resulted in an ingestion error because it is not text

If you ingest it as text, you need to quote it. JSON doesn't have 256 bit numbers.

**Comment by machete-michael** [comment]
Would it be possible for the system to cast the values to string instead of requiring users to modify all their data to use Quickwit?

**Comment by PSeitz** [comment]
If you put u256 as a JSON number and not as text, you are probably doing something wrong. There is barely any support for u256 in general.

**Comment by fmassot** [comment]
@machete-michael: can you give us an example of a document you are trying to ingest?

**Comment by machete-michael** [comment]
Hi François,

Thank you for reaching out but please go ahead and close the ticket. 

I deal with systems that handle UInt256 and I’ll simply process these values in those systems and not involve Quickwit.

You could also easily come up with a test JSON with a value that is greater than what’s supported by U/I64 to replicate this problem.

Cheers,
Michael

**Comment by fmassot** [comment]
No pb, but maybe you saw a bug that I cannot reproduce.

Let me explain you what I did to reproduce:

1. Create an index with dynamic mapping
2. Insert 2 documents with a huge integer either set as int or string:
```json
[
{
   "cart": [
      {
          "product_description": "Cherry Pi",
          "product_id": 2.2010202020202104e68
      }
    ]
},
{
  "cart": [
     {
        "product_description": "Cherry Pi",
        "product_id": "220102020202021011012039120299292991191992929292999992922299299393929"
      }
  ]
}
]
```  

With that, I tried a few queries and saw a few things

Query on float is broken
```
curl -XGET http://localhost:7280/api/v1/my_dynamic_index/search\?query\=car.product_id:2.20
{
  "InvalidQuery": "The field '_dynamic' does not have positions indexed"
}%    
```

I cannot do a query on the exact string "Cherry Pi" as it is immediately considered as a phrase query. This is not what I want as the dynamic mapping is using the default raw tokenizer.

````
curl -XGET http://localhost:7280/api/v1/my_dynamic_index/search?query=car.product_id:%22Cherry\sPi%22
{
  "InvalidQuery": "The field '_dynamic' does not have positions indexed"
}
```

**Comment by PSeitz** [comment]
I had a look on the JSON spec. While it does not limit the number range per se, it does discourage large number ranges for interoperability reasons.

https://datatracker.ietf.org/doc/html/rfc7159#section-6

> This specification allows implementations to set limits on the range
>    and precision of numbers accepted.  Since software that implements
>    IEEE 754-2008 binary64 (double precision) numbers [[IEEE754](https://datatracker.ietf.org/doc/html/rfc7159#ref-IEEE754)] is
>    generally available and widely used, good interoperability can be
>    achieved by implementations that expect no more precision or range
>    than these provide, in the sense that implementations will
>    approximate JSON numbers within the expected precision.  A JSON
>    number such as 1E400 or 3.141592653589793238462643383279 may indicate
>    potential interoperability problems, since it suggests that the
>    software that created it expects receiving software to have greater
>    capabilities for numeric magnitude and precision than is widely
>    available.
> 
>    Note that when such software is used, numbers that are integers and
>    are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
>    sense that implementations will agree exactly on their numeric
>    values.

**Comment by machete-michael** [comment]
Yup, agreed. I could totally be doing something wrong.

Please close ticket if QuickWit doesn’t want to entertain this idea.

Thank you.

**Comment by machete-michael** [comment]
Yup… I’ve already submitted a separate bug, #1829, on what you described here.

Thanks again for looking into it.
