### ISSUE TITLE
Show BM25 scores of docs on search response when they are sorted by their score

### ISSUE THREAD

**Issue by boraarslan** [quickwit-oss/quickwit#1851]
We want to see calculated BM25 results when the docs are sorted by their score. It possibly requires the internal gRPC API to be changed.

**Comment by fulmicoton** [comment]
#1868 showed that there was no easy path to solve this issue. We will postpone this issue until someone actually needs it.

I assume the original intent was to help people debug the scoring.
A better alternative could be to add a flag to add the score and the explanation of the score as returned by tantivy.
