### ISSUE TITLE
Does quickwit support "Multiple indexers" deployment currently?

### ISSUE THREAD

**Issue by geek-frio** [quickwit-oss/quickwit#1856]
Does quickwit support "Multiple indexers" deployment currently?

**Comment by fmassot** [comment]
Hi @geek-frio
Indeed distributed indexing is not yet available.

But we are working on this:
- There is an issue to have distributed indexing working with Kafka #1794. This should be available before the end of the month.
- We are also working on the implementation of the control plane that will assign indexers indexing task, hopefully it will be ready in the coming months.

Are you working with Kafka or other distributed queues?

**Comment by geek-frio** [comment]
> Are you working with Kafka or other distributed queues?
@fmassot 
Thanks for reply! I'm not using distributed queues currently.My server is a central tracing service which provides grpc service to tracing collector, so the tracing collector will send tracing grpc request to the service directly. After getting the request, I batch the request and store in the ElasticSearch. Currently my service max qps will be 30000 qps, and data size is about 1T one day.  

Maybe I can change to use kafka queues to store these data, quickwit's design is very suitable for my tracing data and logging data storing circumstance. 😊

**Comment by fulmicoton** [comment]
@geek-frio Oh cool. We willl probably develop specific features to deal with storing tracing data specifically. If you have time to describe your use case in depth, I'd love to discuss

**Comment by fulmicoton** [comment]
For eventual future readers, this aged very fast. We are about to merge multi-node indexing in main
https://github.com/quickwit-oss/quickwit/pull/1824
