### ISSUE TITLE
Refactor Janitor service GC actor

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#1926]
Refactor the Garbage collection actor in Janitor service to directly work on dangling splits.
- We  want to have a new method on the Metastore that return the list of garbage collectable splits in all registered indexes.
- We also want the `list_splits` method of the metastore to have a filter on `node_id` as we have some common splits operations (clean local split store) done at node level.

Related: https://github.com/quickwit-oss/quickwit/issues/1915

**Comment by evanxg852000** [comment]
@fmassot @guilload I want to close this as I am realising:
- The indexes point to different storage so even with a list of garbage collectable splits, we still need to group them by index instead of my initial plan to start deleting in one go. There is also the number of splits that will be loaded in memory. This will just change the logic but not really improve.
- We are thinking of other ways to clean the split store now.

**Comment by guilload** [comment]
Ok. In the end, this issue is primarily about improving the API of the metastore and offering the ability the arbitrary express filters on splits, which is already tracked by another issue.
