### ISSUE TITLE
Support for ARM architecture (Mac M1)

### ISSUE THREAD

**Issue by demangejeremy** [quickwit-oss/quickwit#1928]
I see that there is no binary available for ARM / Mac M1. If nobody is on this project, I can participate on my time (because I need it, the indexing time is way too high on M1 as I have to mimic the x64 architecture). 

Can I build it and fix any bugs if needed? 
And also try to find solutions to build an ARM compatible Docker.

**Comment by evanxg852000** [comment]
Yes sure, That will be awesome.
We used to have ARM builds in our release, but currently we depend on RocksDB and it makes it hard to build and link for ARM.
As a pointer, you could try building from [cross images.](https://github.com/cross-rs/cross) They recently updated the tools in those base images.

**Comment by fmassot** [comment]
@demangejeremy I'm on M1, and you can build it with cargo. If you need to build it with all features (kafka, azure, postgresql...), you can launch
`cargo build --features release-feature-vendored-set`

**Comment by fulmicoton** [comment]
Also, we will likely ditch RocksDB in the near future.

**Comment by sudochia** [comment]
Still waiting for a binary for ARM / Mac M1, any updates on this?

**Comment by vvo** [comment]
Came here to support this issue too. M1s are the de-facto choice for most developers nowadays. Which makes the getting-started of quickwit a bad experience from the get-go unfortunately. I do not know the effort to have a pre-built version of quickwit for arm but hope you can achieve this at some point 👍  (I'll still continue exploring)

**Comment by fmassot** [comment]
Agreed.

GitHub does not offer macOS m1 runner, and it won't come [before one year ](https://github.com/orgs/github/projects/4247/views/1?pane=issue&itemId=5944419).

Meanwhile, we can:
1. Cross-compile Quickwit on a runner with arch `x86_64` and use ` --target aarch64-apple-darwin`
2. Compile on a self-hosted runner with arch `aarch64`.

The issue with 1 is that cross-compilation is currently failing. See the [logs here](https://github.com/quickwit-oss/quickwit/actions/runs/3861538872/jobs/6582573837#step:3:1226). This is related to this [issue](https://github.com/MaterializeInc/rust-sasl/issues/46).

**Comment by fmassot** [comment]
Let's reopen it as the binaries are not yet available.

**Comment by fmassot** [comment]
M1 binary released: https://quickwit.io/docs/get-started/installation!
