### ISSUE TITLE
Truncated subcommands such as `quickwit index` or `quickwit source` should display the subcommand help.

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1935]
```
$ quickwit source
Failed to parse command arguments: Failed to parse source subcommand arguments.
```

Let's display the same output as `quickwit source --help`.

**Comment by fmassot** [comment]
Strange, on main it's already displaying the help message without adding `--help`.

**Comment by guilload** [comment]
Not able to reproduce. Most likely happened as I was adding a command to the CLI.
