### ISSUE TITLE
Chinese search is not supported？

### ISSUE THREAD

**Issue by yangshike** [quickwit-oss/quickwit#1979]
when i  run:
  "elapsed_time_micros": 79922,
  "errors": []
}[root@iZ8vbb3fnrdi22x6avhwmhZ indexes]# curl  "http://127.0.0.1:7280/api/v1/customer/search?query=wechat_name:maya"

its ok!
 but when i run :
 curl  "http://127.0.0.1:7280/api/v1/customer/search?query=wechat_name:啊"

No output ！！

**Comment by fulmicoton** [comment]
This looks like a tokenization problem. 
You need to configure a chinese tokenizer for your index. Unfortunately, quickwit does not offer any chinese tokenizer out of the box. The good news is that tantivy does offer several, so if you help us we can add support for chinese relatively fast.

Can you help reviewing the results / supplying us with a small dataset?

**Comment by yangshike** [comment]
Of course, but I don't know what I need to do. Could you tell me in more detail

**Comment by trinity-1686a** [comment]
Hi, could you tell us more about your use case? Are you trying to process data primarily in English but which may contain sequences of Chinese (possibly something like logs), documents mostly in Chinese, a dataset of documents in various languages, or something else entirely?

**Comment by yangshike** [comment]
applause！！
