### ISSUE TITLE
Route not found

### ISSUE THREAD

**Issue by YANGJINJUE** [quickwit-oss/quickwit#1997]
**Describe the bug**
curl -X POST http://127.0.0.1:7280/api/v1/hdfs-logs/ingest -H 'context-length:295' -d '{"body":"Deleted BP-108841162-10.10.34.11-1440074360971 blk_1074166613_425789 file /opt/hdfs/data/current/BP-108841162-10.10.34.11-1440074360971/current/finalized/subdir6/subdir123/blk_1074166613","resource":{"service":"datanode/28"},"severity_text":"INFO","tenant_id":20,"timestamp":1475215749}'

execute the ingest will return :
{
  "error": "Route not found"
}

**Expected behavior**

**Configuration:**
Please provide:

1.version: Quickwit 0.3.1 (x86_64-apple-darwin 69eb7db7c 2022-06-22)
2. config: #
# Index config file for hdfs-logs dataset.
#

version: 0

index_id: hdfs-logs

doc_mapping:
  field_mappings:
    - name: timestamp
      type: i64
      fast: true
    - name: tenant_id
      type: u64
    - name: severity_text
      type: text
      tokenizer: raw
    - name: body
      type: text
      tokenizer: default
      record: position
    - name: resource
      type: object
      field_mappings:
        - name: service
          type: text
          tokenizer: raw
  tag_fields: [tenant_id]

indexing_settings:
  timestamp_field: timestamp

search_settings:
  default_search_fields: [severity_text, body]

**Comment by fmassot** [comment]
Thanks for the report @YANGJINJUE 

Currently, if you start the indexing server and then create the index, the indexing server will not see the new index. You need to restart the indexer. 

Can you confirm that this issue is related or not with the current quickwit behavior? By the way, this behavior will change in 0.4.

**Comment by YANGJINJUE** [comment]
thanks for your reply ,the tutorials [https://quickwit.io/docs/tutorials/tutorial-hdfs-logs#start-your-server](url) only start searcher,
./quickwit run will start index and searcher，this will solve the problem.

**Comment by fmassot** [comment]
Ok! Closing the issue but don't hesitate to reopen it if it does not work as expected.
