### ISSUE TITLE
Kafka SourceActor timeout when starting indexers on k8s

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2004]
It happens only when starting the indexer, the pipelines are working well after generation 2 or 3.

I attached the log but there is not much to say as we only see the actor timeout.

[logs.txt](https://github.com/quickwit-oss/quickwit/files/9630030/logs.txt)

**Comment by guilload** [comment]
I'm able to reproduce source actor timeout. When I set `yield_after_each_message` to `true`, this behavior seems to disappear.
