### ISSUE TITLE
The specified column query is invalid

### ISSUE THREAD

**Issue by yangjinming1062** [quickwit-oss/quickwit#2011]
**Describe the bug**
![image](https://user-images.githubusercontent.com/30614179/192076597-5e4c1ad9-752d-4958-8f02-8fc6da030dde.png).
The fuzzy query lists some existing data, and then queries according to the id result but cannot find the content.

**Expected behavior**
How to find specific document.

**Configuration:**
Please provide:

1. quickwit --version: 0.3.1
2. The index_config.yaml
![image](https://user-images.githubusercontent.com/30614179/192076710-c60d8508-8ff7-4a5a-8cbd-1e649a5868f2.png)

**Comment by fulmicoton** [comment]
I am not sure how to fix this but this is a UI bug.

The first screen is actually the wrong one. 
The JSON API is returning a different value, but the browser, as it parses the JSON, uses a 64 bit float point, and cannot represent this number 


One easy way to confirm is to run this in a browser console.
```
s = "{\"id\": 106698291236395745351}";
'{"id": 106698291236395745351}'
v = JSON.parse(s)
{id: 106698291236395750000}
```

Two workarounds  in the meanwhile:
- Redo you test without using the UI. You can hit the API with query=*, get the real id, and run the search query with the correct id value.
- Index your id as a raw text.

You can also wait for us to come up with a fix :)

**Comment by yangjinming1062** [comment]
> I am not sure how to fix this but this is a UI bug.
> 
> The first screen is actually the wrong one. The JSON API is returning a different value, but the browser, as it parses the JSON, uses a 64 bit float point, and cannot represent this number
> 
> One easy way to confirm is to run this in a browser console.
> 
> ```
> s = "{\"id\": 106698291236395745351}";
> '{"id": 106698291236395745351}'
> v = JSON.parse(s)
> {id: 106698291236395750000}
> ```
> 
> Two workarounds in the meanwhile:
> 
> * Redo you test without using the UI. You can hit the API with query=*, get the real id, and run the search query with the correct id value.
> * Index your id as a raw text.
> 
> You can also wait for us to come up with a fix :)

Thanks, I confim that is a BUG of UI

**Comment by fulmicoton** [comment]
I'll create a separate issue so we can track it.

**Comment by fulmicoton** [comment]
@yangjinming1062 thank you for all of the bug reports! It is really helpful for us.
