### ISSUE TITLE
Update tutorial following change in Vector. ndjson => json + framing.method := "newline_delimited"

### ISSUE THREAD

**Issue by yangshike** [quickwit-oss/quickwit#2019]
when i used send logs from vector to quickwit , i got error:
2022-09-27T05:47:01.785Z  WARN {actor=quickwit_indexing::actors::indexing_service::IndexingService}:{msg_id=1}::{index=customer3 gen=0}:{actor=quickwit_indexing::actors::doc_processor::DocProcessor}:{msg_id=4}: quickwit_indexing::actors::doc_processor: err=NotJsonObject("[{\"id\":4152728738612")

this is my vector output on console:
{"id":415272873861226802,"wechat_name":"清醒"}

my vector sink config:
[sinks.quick]
type = "http"
inputs = ["modify_t_customer"]
encoding.codec = "json"
uri = "http://127.0.0.1:7280/api/v1/customer3/ingest"

when i chaneged my vector config to :
[sinks.quick]
type = "http"
inputs = ["modify_t_customer"]
encoding.codec = "native_json"
uri = "http://127.0.0.1:7280/api/v1/customer3/ingest"

i got error like this:

2022-09-27T05:49:43.074Z  WARN {actor=quickwit_indexing::actors::indexing_service::IndexingService}:{msg_id=1}::{index=customer3 gen=0}:{actor=quickwit_indexing::actors::doc_processor::DocProcessor}:{msg_id=169}: quickwit_indexing::actors::doc_processor: err=RequiredFastField("id")

It looks like a problem with my vector sink config

However, vector sink http only supports：
 expected one of `avro`, `gelf`, `json`, `logfmt`, `native`, `native_json`, `raw_message`, `text` 

but I didn't see the ndjson in the document url ：https://quickwit.io/docs/tutorials/send-logs-from-vector-to-quickwit
[sinks.quickwit_logs]
type = "http"
inputs = ["remap_syslog"]
encoding.codec = "ndjson"
uri = "http://host.docker.internal:7280/api/v1/otel-logs/ingest"

what can i do!!

**Comment by fulmicoton** [comment]
It seems like a breaking change in vector as described in https://github.com/vectordotdev/vector/blob/7b263c2e4e96127145857e58634bc516c0deac85/website/content/en/highlights/2022-08-16-0-24-0-upgrade-guide.md#sink-encoding-json.

We should update our tutorial accordingly.

The new configuration to get ndjson content is :

```toml
[sinks.quickwit_logs]
type = "http"
inputs = ["remap_syslog"]
encoding.codec = "json"
encoding.framing.method = "newline_delimited"
uri = "http://host.docker.internal:7280/api/v1/otel-logs/ingest"
```

**Comment by yangshike** [comment]
i changed my vector  configs:
[sinks.quick]
type = "http"
inputs = ["modify_t_customer"]
encoding.codec = "json"
encoding.framing.method = "newline_delimited"
uri = "http://127.0.0.1:7280/api/v1/customer3/ingest"

But the mistake is still there！
2022-09-27T06:51:25.072Z  WARN {actor=quickwit_indexing::actors::indexing_service::IndexingService}:{msg_id=1}::{index=customer3 gen=0}:{actor=quickwit_indexing::actors::doc_processor::DocProcessor}:{msg_id=270}: quickwit_indexing::actors::doc_processor: err=NotJsonObject("[{\"id\":4312058343309")

**Comment by fulmicoton** [comment]
I don't think you got the framing method right.
```
encoding.framing.method = "newline_delimited"
```

**Comment by yangshike** [comment]
when i changed config like this , its ok!!
[sinks.quick]
type = "http"
inputs = ["modify_t_customer"]
encoding.codec = "json"
framing.method = "newline_delimited"
uri = "http://127.0.0.1:7280/api/v1/customer3/ingest"

framing.method = "newline_delimited"
not encoding.framing.method = "newline_delimited"

**Comment by fulmicoton** [comment]
ok cool ! @yangshike

**Comment by yangshike** [comment]
> ok cool ! @yangshike Let's leave the issue open so we update the tutorial. If you want to contribute the tutorial fix you are welcome to :) https://github.com/quickwit-oss/quickwit/blob/c9eac002484ad59d10b05a3c155ac419996492df/docs/tutorials/send-logs-from-vector-to-quickwit.md

Pull a branch to modify and submit? From which branch?

**Comment by yangshike** [comment]
Does quwickwit have a unique key? Or does it support index updates?

For example, first insert {"id": 123, "value": "abcde"}

Then insert {"id": 123, "value": "abcde"}

At present, 2 records will be searched

**Comment by fulmicoton** [comment]
Unfortunately no... Quickwit does not support such updates.

**Comment by fulmicoton** [comment]
> Pull a branch to modify and submit? From which branch?

Yes so you can clone quickwit's repository.
Position yourself on the `main` branch.
Create a branch called `issue/2019-ndjson-vector-tutorial`  for instance
Do the modification locally.
Push to your repository clone.
Open a pull request to our repo.

**Comment by yangshike** [comment]
# 位于分支 issue/2019-ndjson-vector-tutorial

[yangshike@maven tutorials]$ git push origin issue/2019-ndjson-vector-tutorial
ERROR: Permission to quickwit-oss/quickwit.git denied to yangshike.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by fulmicoton** [comment]
Yes... You need to fork our repo to your github account, push there, and send a pull request.

Here is a guide:
https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by yangshike** [comment]
Do I need to clone the code to my own account?

https://github.com/yangshike/quickwit.git ??

This is my git config：
alias.st=status
alias.co=checkout
alias.ci=commit
alias.br=branch -a
alias.me=merge
alias.lg=log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:quickwit-oss/quickwit.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main

I cannot directly execute this command??
#git push origin issue/2019-ndjson-vector-tutorial

**Comment by fulmicoton** [comment]
Yes. The easiest way is to click the "fork" button on github. at the top right of the screen.
Then you clone the repo to your computer.

Push the change to your copy: https://github.com/yangshike/quickwit.git
And then create the pull request on quickwit-io/quickwit

**Comment by yangshike** [comment]
i‘m sorry , 

I have sent it to my own address: https://github.com/yangshike/quickwit

But I didn't find my push when I created a pull request in quickwit io/quickwit

**Comment by fmassot** [comment]
Is your repo private? I can't view it.

@fulmicoton meant "create a pull request on quickwit-oss/quickwit" no "quickwit-io/quickwit"

**Comment by yangshike** [comment]
I have set: https://github.com/yangshike/quickwit It's public, but I'm

My branches cannot be found when quickwit oss/quickwit creates a pull request

**Comment by fulmicoton** [comment]
The problem is that I think you didn't create the fork using github. Github has no link between quickwit-oss/quickwit and your repo.

**Comment by fulmicoton** [comment]
Thank you and congratulation for your first contribution :)

**Comment by yangshike** [comment]
yeah，Thank you for your help！！
