### ISSUE TITLE
Use parallel podManagementPolicy for stateful sets

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2054]
Currently, scaling indexers and searchers is slow as we use the `OrderedReady` pod management policy (it's the default). It seems very interesting to use the parallel policy to start all pods at the same time, at least this is very cool for a demo ^^.

For searchers, it seems only beneficial to use the parallel policy. Starting a searcher is very light, there is no risk to overload the system by making many queries on the metastore.

For indexers, there is a risk to overload the metastore. On the contrary, by starting together 10 nodes, there is a chance that we will avoid making several rebalances.

I would go for the parallel policy at least for searchers, for indexers, we could progressively start indexers in groups of 10 so that you don't have to wait that much when you need to start 100 indexers.

See [docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#orderedready-pod-management) for more details.

**Comment by guilload** [comment]
Closing in favor issue linked above.
