### ISSUE TITLE
Remove `chrono` dependency 

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2066]
1. The parsing API prevents us from validating custom input formats submitted by users
2. The lib does not seem maintained and has a bunch of lagging dependencies.

We can implement custom input formats parsing with `time` with [`time::format_description::parse`](https://docs.rs/time/latest/time/format_description/fn.parse.html).

`time` does not support the `strftime` format natively. Investigate we can rely on a trustworthy third-party crate to do so. If not, we can ditch the `strftime` format for the time being.

Update docs with supported custom input formats for dates and datetimes.

**Comment by guilload** [comment]
https://crates.io/crates/time-fmt

**Comment by fulmicoton** [comment]
I'm ok with dithcing the strftime format if we document with examples the format we accept. The time crate documentation is very technical and hard to grok.

**Comment by evanxg852000** [comment]
**Ticket Amendment**: Ideally we want to parse the format once, hold  on to the parse tree and use if for subsequent date parsing.
