### ISSUE TITLE
Harmonise the internal object id marker

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#2069]
In Quickwit, we have some special objects with known names. 
- SOURCE_FIELD_NAME: `_source` 
- DYNAMIC_FIELD_NAME: `_dynamic`
- CLI_INGEST_SOURCE_ID: `.cli-ingest-source`
- INGEST_API_SOURCE_ID: `.ingest-api`

Let's hamonise all this to use the `_` marker .
It would also be nice to group all these known objects' names in one place, namely `quickwit-common/quickwit.rs` (debatable).

**Comment by fulmicoton** [comment]
Agreed with the harmonization. I disagree with the all in one place. Most of these are "private" names that are not meant to be used outside of a project
