### ISSUE TITLE
Remain consistent between index_config and index_metadata for retention key

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2105]
When we create an index, the user can define the retention by the key "retention". When the index_metadata is serialized, we use  the key `retention_policy`.

**Comment by guilload** [comment]
This is not an issue IMO; there are other examples in the config objects where we went for a nicer external name and a more explicit internal name:

`data_dir` -> `data_dir_path`
`indexer` -> `indexer_config`
`searcher` -> `searcher_config`
`period` -> `retention_period`
...
