### ISSUE TITLE
Indexing with many partitions stalls during merging big splits

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2121]
I'm indexing on a `c5ad.2xlarge`.

The following statistics were registered during several consecutive merges of 10 splits that are leading to splits between 1 to 10 million docs, split size from 1GB to 10GB.

Here is the output of `iostat -hyx 1 4` during big merges:

```
iostat -hyx 1 4
Linux 4.19.0-18-cloud-amd64 (external-providers-quickwit-indexer1-staging.eu-west-1.csq.io) 	10/15/22 	_x86_64_	(8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.0%    0.0%    0.0%    0.0%    0.0%    0.0%

     r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util Device
    0.00    0.00      0.0k      0.0k     0.00     0.00   0.0%   0.0%    0.00    0.00   0.00     0.0k     0.0k   0.00   0.0% nvme0n1
  420.00  373.00     47.9M     77.3M     0.00   125.00   0.0%  25.1%    4.11    3.36   3.23   116.8k   212.3k   1.26 100.0% nvme1n1

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.1%    0.0%    0.8%   12.6%    0.0%   84.5%

     r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util Device
    0.00    0.00      0.0k      0.0k     0.00     0.00   0.0%   0.0%    0.00    0.00   0.00     0.0k     0.0k   0.00   0.0% nvme0n1
  463.00  303.00     57.5M     67.6M     0.00   107.00   0.0%  26.1%    4.12    3.66   3.17   127.2k   228.5k   1.31 100.0% nvme1n1

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.8%    0.0%    1.0%   17.8%    0.0%   77.4%

     r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util Device
    0.00    0.00      0.0k      0.0k     0.00     0.00   0.0%   0.0%    0.00    0.00   0.00     0.0k     0.0k   0.00   0.0% nvme0n1
  393.00  375.00     48.4M     76.9M     0.00   179.00   0.0%  32.3%    6.01    6.14   4.87   126.2k   210.1k   1.30 100.0% nvme1n1

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.8%    0.0%    0.9%   11.3%    0.0%   85.0%

     r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util Device
    0.00    0.00      0.0k      0.0k     0.00     0.00   0.0%   0.0%    0.00    0.00   0.00     0.0k     0.0k   0.00   0.0% nvme0n1
  416.00  370.00     51.6M     73.6M     0.00   152.00   0.0%  29.1%    3.98    3.69   3.25   126.9k   203.7k   1.27 100.0% nvme1n1
```

The output of top:

```
top - 22:38:29 up 131 days, 12:34,  1 user,  load average: 7.53, 6.56, 6.21
Tasks: 128 total,   1 running, 127 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.0 us,  7.0 sy,  0.0 ni, 48.9 id, 39.8 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :  15858.3 total,    156.8 free,   1979.9 used,  13721.5 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  13318.1 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
24390 quickwit  20   0   23.4g   4.6g   3.1g S 148.8  29.9  83:30.73 quickwit-latest
  634 prometh+  20   0  116760  12520      0 S   3.0   0.1 918:21.97 node_exporter
```

And here is the graph showing the slowdown of indexing

![Capture d’écran 2022-10-16 à 00 36 05](https://user-images.githubusercontent.com/653704/196010149-6070a397-9c44-4ac3-b0a3-5c4fbe049a4b.png)

Load average graph

![Capture d’écran 2022-10-16 à 00 51 55](https://user-images.githubusercontent.com/653704/196010466-dd8ea709-a188-43c3-87a2-8495234f7517.png)

**Comment by fmassot** [comment]
As suggested in #2124 , it would be nice to measure the backpressure.

I'm doing some experimentations in this PR #2125 to measure the time we wait to send a message in an actor mailbox.

Here the graph from prometheus:
![Capture d’écran 2022-10-16 à 19 48 01](https://user-images.githubusercontent.com/653704/196050358-a0bb1223-d4ba-46da-9b90-a4278feb0f3e.png)

I'm showing this metric: 
```
histogram_quantile(0.9,
  rate(quickwit_indexing_message_waiting_time_bucket[5m])
)
```

The blue line corresponds to the waiting time to send a message to the index serializer. The grey and green lines corresponds to the waiting time to send a message to the merge downloader and merge executor.

**Comment by fmassot** [comment]
New graph during big merges.

First, I'm simulating a situation where there are several big merges to do as I have just changed a parameter in the merge policy. Even if the system should usually have fewer merges to do, this situation illustrates how quickwit behaves under heavy merges.   

In the waiting time chart, we can see that the merge planner is waiting for the merge downloader, this is expected as there are several merges to run.

The interesting part here is the purple line which is the waiting time to send a message to the indexer. This is thus the indexer that is applying some backpressure. This backpressure is propagated to the doc processor (but it's hard to see it on the graph as several lines are overlapping. The Kafka source will then stop consuming message, thus the drop in the indexing throughput.


![Capture d’écran 2022-10-16 à 22 25 09](https://user-images.githubusercontent.com/653704/196056559-301db4d5-2606-48a5-9a24-c962e31c5ef7.png)

![Capture d’écran 2022-10-16 à 22 25 24](https://user-images.githubusercontent.com/653704/196056556-b02a67cc-9be8-4a83-99c8-273f17d44893.png)

**Comment by fmassot** [comment]
It's interesting to see the lifecycle of one split to see the different timing:

```
2022-10-16T21:15:10.417Z  INFO quickwit_indexing::actors::indexer: new-split split_id="01GFHAD2YG96ZS94P08WPQ3ZGX"
2022-10-16T21:15:48.355Z  INFO quickwit_indexing::actors::indexer: send-to-packager commit_trigger=Timeout split_ids=... num_docs=874
2022-10-16T21:19:37.575Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:packager: quickwit_indexing::actors::packager: start-packaging-splits split_ids=["...."]
2022-10-16T21:19:37.650Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:packager: quickwit_indexing::actors::packager: create-packaged-split split_id="01GFHAD2YG96ZS94P08WPQ3ZGX"
2022-10-16T21:19:40.754Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:uploader: quickwit_indexing::actors::uploader: start-stage-and-store-splits split_ids=[...]
2022-10-16T21:19:40.882Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:uploader:stage_and_upload{split=...}:store_split: quickwit_indexing::split_store::indexing_split_store: store-split-remote-success split_size_in_megabytes=0 num_docs=21 elapsed_secs=0.072952814 throughput_mb_s=0 is_mature=false
2022-10-16T21:19:40.882Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:uploader:stage_and_upload{split=...}:store_split: quickwit_indexing::split_store::indexing_split_store: store-in-cache
2022-10-16T21:19:50.948Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:publisher{split_update=SplitsUpdate { index_id: "quickwit-fts-staging", new_splits: "...", checkpoint_delta: Some(...)) }}:publish_splits{index_id="quickwit-fts-staging" new_split_ids=[..] replaced_split_ids=[] checkpoint_delta_opt=Some(...)
2022-10-16T21:19:50.967Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:publisher{split_update=SplitsUpdate { index_id: "quickwit-fts-staging", new_splits: "...", checkpoint_delta: Some(...)) }}: quickwit_indexing::actors::publisher: publish-new-splits new_splits=[...] checkpoint_delta=Some(...))
2022-10-16T21:19:50.967Z  INFO index_batch{index_id=quickwit-fts-staging source_id=kafka-source pipeline_ord=0}:publisher{split_update=SplitsUpdate { index_id: "quickwit-fts-staging", new_splits: "...", checkpoint_delta: Some(...)) }}: quickwit_metastore::checkpoint:
```

**Comment by fulmicoton** [comment]
Possible explanation #2129

**Comment by fmassot** [comment]
Problem was solved as I was indexing on an EBS volume contrary to what I thought initially. When indexing on a local SSD, the disk is no more saturating and the indexing throughput varies between 20BM and 25MB/sec.
cc @guilload

**Comment by fmassot** [comment]
I'm reopening the issue as I'm observing the same behavior but at a smaller scale when using a local SSD.

Every time we have to do merges of millions of documents, a merge will typically take between 1 and 2 minutes to complete.
During the merge, the disk is being saturated and the indexing throughput drops.

Those big merges do not happen. On my use case, I'm expecting a drop of indexing throughput during around 1 hour every 16 hours.



```
    r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util Device
 1365.00 1008.60    169.3M    120.6M     0.00   118.20   0.0%  10.5%    0.76   31.45  32.89   127.0k   122.4k   0.42 100.2% nvme0n1
```



![Capture d’écran 2022-10-18 à 10 13 14](https://user-images.githubusercontent.com/653704/196377081-df72d524-c657-442a-9fb2-c03cefc592c6.png)

**Comment by fulmicoton** [comment]
@fmassot can we close this?

**Comment by fulmicoton** [comment]
This issue contains different problem:
- competition between index and merge on IO
- lack of backpressure
- large merges preventing small merges to be executing for long period of times.

That last one is the last problem remaining if I understand correctly.

It is tracked in #2348. Closing this issue. (feel free to reopen if my understanding is off)
