### ISSUE TITLE
Remove tantivy dependency from quickwit-common

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2135]
I introduced this dependency in #2116 but we want to keep `quickwit-common` as light as possible.

I believe we can move that in the `quickwit-doc-mapper` but I was not very fond of it. The advantage is that tantivy is already use there.

**Comment by guilload** [comment]
I'm going to close this because #2205 is also adding a dependency on tantivy.

**Comment by fulmicoton** [comment]
I can remove the deps to  tantivy in #2205.

**Comment by fulmicoton** [comment]
I just removed this deps, and I confirm it would be nicer to remove tantivy from quickwit-common.
