### ISSUE TITLE
`LocalSplitStore` error from `split_id_from_split_folder` is misleading / fragile.

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2145]
Currently, if the `LocalSplitStore` attempts to be open it will list all of the cached splits folders. This is fine however, under high load and with a high number of splits, it's possible that whilst iterating through the folder a split folder could be deleted or cause an IO error which causes `Path::is_dir` to default to `false`.

Because of this default to `false` on error behaviour, we get the following error:
```
Command failed: Split folder name should match the format `<split_id>.split`. Got `"/home/chillfish8/projects/quickwit/qwdata/cache/splits/01GFR31YZX8KM8XJ895WSE37ZX.split"`.
```

This error is fairly misleading as it does two things:

- It suggests that the folder should have a naming format that suggests it is a file, not a folder. (`.split` ending suggests it's a file when you read over it quickly.)
- The error suggests it's a naming error rather despite being in the correct format when it Is, in fact, caused by a separate error.

**Potential Solution**
I think the potential solution is that we silently ignore (or just warn) and continue on ignoring the bad file/folder, rather than making this a hard error.

**Comment by fulmicoton** [comment]
Nice find!

**Comment by guilload** [comment]
There's one thing I don't understand. The `LocalSplitStore` is, AFAIK, the only object responsible for removing splits from the split cache, and there should only be one instance per process, so I don't see how it can run in "listing" AND "eviction" mode at the same time.

Were you running multiple processes sharing the same data dir?

**Comment by ChillFish8** [comment]
I was mostly being lazy and running the `ingest` command with a local file and then also running `run`.

**Comment by guilload** [comment]
Let's use `fs::metadata` directly then, so we don't swallow the file not found error.

For your tests, you can run `QW_NODE_ID=node-1 QW_DATA_DIR=qwdata/node-1 quickwit ...`
