### ISSUE TITLE
Create index via http request

### ISSUE THREAD

**Issue by Liyixin95** [quickwit-oss/quickwit#2176]
I have saw the previous issue: #1481, which comment out the rest handler of index management. At this time,  the `metastore` is ensured to be existsed before the indexer start, so I think it may be it's time to provide the rest handler of index management.
  
  Beside the code previously commented out, I think the code of informing the `IndexingService` to spwan a pipeline when creating index is also needed.

  If you don't mind, I can provide a PR.

**Comment by fmassot** [comment]
Thanks @Liyixin95 for the feedback. We commented the code in #1481 as we have currently no reliable way to notify the indexers that a new index has been created. This will be the job of the control plane, there is a PR about that but there is still a lot of work to do on this and we plan to release the control plane probably beginning of next year. Currently we are very focused on the 0.4.

Something crossed my mind recently and maybe we could provide an alternative at short term: each indexing service could poll the metastore and start new pipelines and remove ones from deleted indexes. WDYT @guilload @fulmicoton ?

**Comment by fmassot** [comment]
@Liyixin95 this has been added by #2512  and is part of 0.4.0. We plan to add also creation with yaml/toml payload.
