### ISSUE TITLE
Having a configmap dedicated to the metastore related stuff?

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2187]
Currently, we have one configmap with the metastore configuration, typically PostgreSQL stuff. But the metastore configuration is useful only for the metastore service.

We may want to have a dedicated configmap for the metastore for clarity, suggested by @clemcvlcs.

**Comment by guilload** [comment]
Let's move this issue to the [helm-charts](https://github.com/quickwit-oss/helm-charts) repo.
