### ISSUE TITLE
Add confirm promp for CLI destructive commands

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2201]
It would be nice to have that or some users will lose their indexes. I saw that `quickwit index delete` does not have a prompt.

**Comment by fatelei** [comment]
assign to me

**Comment by fulmicoton** [comment]
Thanks for chiming in @fatelei. It's all yours!

**Comment by fulmicoton** [comment]
Assigned to druznek aka Maurizio.

**Comment by ph** [comment]
I think this issue can be closed, following the work in #2618 and #3147.

I did a small audit of the `quickwit-cli/src` source code and identified the following destructive sub-commands and they have a user confirmation.

- index clear
- index delete
- split mark-for-deletion 
- source delete

**Comment by guilload** [comment]
Closing then. Thanks @ph !
