### ISSUE TITLE
Refactor IndexPipelineId and MergePipelineId

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2206]
My hunch...

We  don't need have the pipeline_ord on split metadata. It has become meaningless for merged pipelines, and the 
debugging value is limited.

We can probably ditch the indexpipelineid / merge pipeline id distinction, and just sparkle pipeline_ord on the rare place where it is needed.

**Comment by fmassot** [comment]
Fixed in #2214
