### ISSUE TITLE
Remove the support of i64 as timestamp.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2220]
Our datetime field allows to ingest date as a unix timestamp.
It also allows representation in different format. 

There is no need to support defining a i64 field as a timestamp anymore.

Let's ditch this and force user to define a proper datetime field as the index timestamp in the docmapper.
Let's also ditch the horrible `GenericFastField` thing.

@evanxg852000 @fmassot Can you both confirm that this makes sense?

**Comment by fmassot** [comment]
@evanxg852000 mentioned that we won't have aggregation on datetime field, so if we remove the support of i64, we will lose aggregation on timestamp field.

I think this can wait 0.4.1.

@fulmicoton @guilload ?

**Comment by guilload** [comment]
yes!
