### ISSUE TITLE
Uri::new and Uri::try_new names are confusing.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2230]
We have two functions to build Uri object.

The comments are helpful, but the constructor names are quite confusing. 

We can probably find a better name.

**Comment by guilload** [comment]
We can ditch `try_new` for `FromStr`.

**Comment by evanxg852000** [comment]
We can replace the `try_new` method with  an `impl FromStr for Uri` this can allow us to do:
```rust
 let u1 = Uri::from_str("http://example.com/foo")?;
 let u2 = "http://example.com/bar".parse::<Uri>()?;
 ```
As for `new`, I think we can just replace it with for_test because we only use it in tests.

**Comment by guilload** [comment]
`new` is used in a few places where we trust the input.

**Comment by fulmicoton** [comment]
It is not just about trust here. Try_new really does more work like resolving relative file path.

**Comment by guilload** [comment]
I was talking about `new`... We use `new` when we know the URI is well-formed, i.e. `protocol://<absolute path>`
