### ISSUE TITLE
Committing offsets on Kafka side for monitoring purposes?

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2268]
Quickwit ensures exactly-once semantics by storing Kafka offsets in the metastore on a split publish.

We may also want to commit offsets after a split publish on Kafka side too. The benefit would be that Kafka will be aware of the lag of the consumers, it can be helpful for monitoring purposes. 

However, I'm not sure if we can do it correctly, we would need to commit offsets on Kafka without interfering with our Kafka consumers. 

There is also an alternative: a monitoring dashboard could compare the latest publish offsets by calling the Quickwit API and thus be available to track the lag.

**Comment by guilload** [comment]
This also has been requested by another user. @yangshike, can you describe your use case? Is it related to retention?

**Comment by guilload** [comment]
Closed via #3638.
