### ISSUE TITLE
Add the ability to disable colours and other ASNI codes when logging.

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2273]
Currently, we use the default `tracing_subscriber` formatter which logs using the traditional ASNI colours I believe, but this can be particularly unhelpful if you're logging to a file or central source which does not render these colour codes where they become simply noise rather than helpful. 

Logs with ASNI codes being injected without rendering:
```
^[[2m2022-11-08T21:28:25.720Z^[[0m ^[[32m INFO^[[0m ^[[2mquickwit^[[0m^[[2m:^[[0m ^[[3mversion^[[0m^[[2m=^[[0m"0.3.1-nightly" ^[[3mcommit^[[0m^[[2m=^[[0m"449014911"
```

What disabling ASNI codes should do:
```
2022-11-08T21:23:42.220Z  INFO quickwit: version="0.3.1-nightly" commit="449014911"
```

**Comment by fmassot** [comment]
Agreed, I was going to open the same issue. My thoughts on this is that we can do the following:
- detect the output goes into a terminal and activate color only if this is a terminal (using `atty`)
- add a flag to enforce logs without ANSI codes.
