### ISSUE TITLE
Is it possible to update/delete documents at all?

### ISSUE THREAD

**Issue by valerauko** [quickwit-oss/quickwit#2298]
I saw in the README that immutability of the data is an assumption, but is it possible at all to update/delete documents through some API (eg not the CLI)?

While an uncommon occurrence in my use case it might be necessary for eg compliance/legal reasons.

I tried looking through the docs but couldn't find a mention of this.

**Comment by valerauko** [comment]
I have seen that tantivy [can delete documents](https://github.com/quickwit-oss/tantivy/blob/main/examples/deleting_updating_documents.rs) but is this functionality exposed in quickwit?

**Comment by fmassot** [comment]
Hi @valerauko, we have introduced on the main branch a delete by query feature #402. It will be part of the next release 0.4 planned for the end of the month.

The delete is quite heavy in tantivy so this feature targets compliance use cases (few deletes per day).

**Comment by valerauko** [comment]
Awesome, thanks!
