### ISSUE TITLE
Query `body:*` returns no result

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2313]
The char `*` is a special character that can be used to define an `AllQuery`.

While this query sounds dumb (and it is really), when you have no default search field defined, you may, at one moment, type this... (it happened to me). And when you search for `body:*`, it will return no result as it will build an `EmptyQuery`.

This can be confusing for the user that can believe something is broken, it would be nice to avoid this bad experience.

**Comment by fulmicoton** [comment]
That's more a feature than a bug. We need to have `body:*` return all docs with a body field.

**Comment by guilload** [comment]
Fixed via #2319.
