### ISSUE TITLE
Merge CLI command is broken

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2403]

**Comment by fmassot** [comment]
@ChillFish8 my thought on this:
- we can observe the merge pipeline every xx milliseconds
- the `MergeStatistics` may be a bit poor but we can enrich by adding the number of ongoing merge operations
- stop the merge pipeline when there is no more ongoing merge operations.

**Comment by ChillFish8** [comment]
Sounds like a plan, I think we can probably do what we've done with the index CLI.
