### ISSUE TITLE
Limit number of histogram buckets.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2503]
When creating an histogram bucket it is quite easy to shoot oneself in the foot.

We could have a parameter (not sure what would be a good name) to return an error if there are too many results.
The idea is just not to crash the server.
(The min_count can then easily fix the user problem)

We can default to 1000 (?)

**Comment by PSeitz** [comment]
We already a max bucket limit (https://github.com/quickwit-oss/tantivy/pull/1363) and it's set to 65000.
`const AGGREGATION_BUCKET_LIMIT: u32 = 65000;`

Currently histogram buckets are pre-created depending on the fastfields min max values and passed bounds. This allows easy computation of the bucket pos for incoming values.
When we would enable the bucket limit during initial bucket creation a lot of valid queries would be cancelled, so the validation is postponed for the conversion to intermediate buckets.

We need to switch the Histogram to lazy bucket creation to enable a more early cancellation.
