### ISSUE TITLE
Use OpenAPI to generate REST docs. 

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2509]
Our REST API is growing and it will soon be very painful to update it. It is time to think about using OpenAPI.

**Comment by ChillFish8** [comment]
My experience with [utoipa](https://crates.io/crates/utoipa) has been very good and should integrate into the existing code base fairly smoothly.

**Comment by fulmicoton** [comment]
Cool. Would you be ok to take the lead on this @ChillFish8 ?
That would really improve the project.

**Comment by fulmicoton** [comment]
Cool. Would you be ok to take the lead on this @ChillFish8 ?
That would really improve the project.

**Comment by ChillFish8** [comment]
yes, fine by me 👍
