### ISSUE TITLE
Generate Markdown from clap docs

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#256]
Currently the docs for the markdown are manually created and update. It would be better to generate a md page from the clap docs.

I didn't find something exact as solution, but a hook to generate stuff exists (https://github.com/clap-rs/clap/blob/master/clap_generate/src/lib.rs).

There is also an abandoned project (https://github.com/rust-cli/clap-md) and an open issue for generation of man pages etc. (https://github.com/clap-rs/clap/issues/552)

**Comment by fulmicoton** [comment]
We rely on yaml, so maybe we can do something with some template tech.

**Comment by evanxg852000** [comment]
There seems to be a work started on this but currently, only the `bash` completion is generated.
This doc also looks confusing as `gen_manuals` is not available in any clap_generate https://github.com/rust-cli/book/issues/61

**Comment by fulmicoton** [comment]
What is the status of this? I think you implemented something @PSeitz

**Comment by PSeitz** [comment]
Yes, the `generate_markdown.rs` generates markdown from the clap parameters

https://github.com/quickwit-oss/quickwit/blob/8d9a1a1a661ca096b74a81c3af5eb7a0ecc96742/CONTRIBUTING.md#generating-the-cli-docs
