### ISSUE TITLE
List of terms for field

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2567]
Given a field `f`, a prefix `p`, and a maximum number of returned terms `n`, returns at most `n` unique terms ordered lexicographically starting with the prefix `p` for the field `f`. Returns all the terms in `f` if `p` is the empty string and `n` is `None`.

Use case: for the Jaeger integration, we want to efficiently retrieve the list of `services` for which traces have been ingested in the last 24h. Since the term dictionary will be small for this field, we will likely want to store it in the hotcache.

**Comment by fulmicoton** [comment]
I took the liberty to change the name of the ticket.

This ticket is related to https://github.com/quickwit-oss/quickwit/issues/2266

**Comment by fulmicoton** [comment]
We might need to land https://github.com/quickwit-oss/tantivy/pull/1734 before this.

**Comment by fulmicoton** [comment]
More information:
First important realization:
A prefix query is also a range query.

For instance, if the prefix being search is `blabla @ last_char`, then the prefix is equivalent to searching for 
 `[`blabla @ last_byte`, `blabla @ last_char`) `

I leave it to you to sort out how to deal with `last_char == 255`


Then we already have code to identify file slice that need to be warmed up to go through a range:
`Dictionary::file_slice_for_range`

We can be a tiny bit more tight fit if needed by adapting it to only cover enough blocks to make sure we cover `n` terms.
