### ISSUE TITLE
Prune splits based on partition key

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2572]
See `search::root::list_relevant_splits`.

**Comment by fulmicoton** [comment]
Can you detail a bit more what you mean?

We voluntarily chose to decouple the isolation mechanism (partitioning) from the pruning mechanism (tagging).

**Comment by guilload** [comment]
The index I'm working with is partitioned on `service_name`. I'm performing queries such as `service_name:frontend AND ...`. I was surprised to notice that all the splits were targeted. I thought that was an oversight, not a feature.

**Comment by guilload** [comment]
I think the missing piece is auto-tagging then. In my case, since I'm partitioning by `service_name` name, I should have also tagged this field.

**Comment by fulmicoton** [comment]
Closing, replacing by #3000
