### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2649]
We need to release a new Quickwit version (0.4.1) after fixing these two bugs:
- https://github.com/quickwit-oss/tantivy/issues/1757
- https://github.com/quickwit-oss/tantivy/issues/1783

**Comment by fulmicoton** [comment]
@PSeitz can you take care of publishing a tantivy hotfix rapidly first?

Main is messy, by hotfix I mean backporting the fixes to the 0.19 tag and publishing that.

**Comment by PSeitz** [comment]
I don't think they are relevant for Quickwit 0.4, the fix on `get_docids_for_value_range` is relevant for range queries on u64-like fastfields, and they have just recently been enabled

**Comment by fulmicoton** [comment]
Cool so no need for a Quickwit 0.4.1 release?

**Comment by PSeitz** [comment]
Only tantivy `0.19.1`
