### ISSUE TITLE
ES-compatible API

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2653]
Endpoints:
- [x] https://github.com/quickwit-oss/quickwit/issues/2656
- [x] [_msearch endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/search-multi-search.html)
- [x] https://github.com/quickwit-oss/quickwit/issues/2770 (high priority)
- [x] #3527
- [x] #3526
- [x] #3525

Search parameters:
- [x] https://github.com/quickwit-oss/quickwit/issues/3551 (high priority)
- [x] https://github.com/quickwit-oss/quickwit/issues/2670 (high priority)
- [x] #3310 
- [x] #3523 (under discussion)

Query DSL:

- [x] #3263 (high priority)
- [x] Query string with  `lenient`, `default_field`, `fields` params (high priority)
- [x] [Multi-match query](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/query-dsl-multi-match-query.html) with `[phrase_prefix, phrase]` type, `lenient`  (high priority)
- [ ] [Terms query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html) note this is mildly different from term query. (s)  (high priority)
~~- [Multi-match query with `analyze_wildcard`  + `analyzer` (under discussion)~~
- [x] Match all `{"match_all": {}}`
- [x] https://github.com/quickwit-oss/quickwit/issues/2657
- [x] [Query string](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/query-dsl-query-string-query.html)
- [x] [Match query](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/query-dsl-match-query.html)
- [x] #2266
- [x] [Range query](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/query-dsl-range-query.html)
- [x] [Sort](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html)

Aggregation DSL:
- [x] [Date histogram](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/search-aggregations-bucket-datehistogram-aggregation.html)
- [x] Histogram
- [x] [Percentiles aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/search-aggregations-metrics-percentile-aggregation.html)
- [x] [Terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html)
- [x] [Stats aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-stats-aggregation.html) 

Other missing elastic features that we might discuss:
- [x] Support sort on multiple fields & different types of sort https://www.elastic.co/guide/en/elasticsearch/reference/8.6/sort-search-results.html (under discussion)
- [ ] Support selecting/excluding specific document source fields to display (under discussion)

**Comment by guilload** [comment]
Bumping priority for:
- Query string with `analyze_wildcard`
- Multi-match query

**Comment by esatterwhite** [comment]
One thing I'm noticing missing from the `_search` api is the ability to [search across multiple indicies](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-multiple-indices.html)

**Comment by fmassot** [comment]
Thanks for the feedback. Just confirming that search across multiple indices is not yet supported.

**Comment by esatterwhite** [comment]
The Validation for index names is a little different than what elasticsearch allows.

`^[a-zA-Z][a-zA-Z0-9-_]{2,254}$` doesn't allow for a dot (period) `.` Which is allowed and common in elastic index names.

**Comment by esatterwhite** [comment]
It looks like the `_bulk` endpoint is lacking the ability to create missing indexes as well

**Comment by fulmicoton** [comment]
Commenting about the HEAD request. @fmassot fixed it.

**Comment by esatterwhite** [comment]
I think we can probably call this done for our purposes @fulmicoton, what do you thin?

**Comment by fulmicoton** [comment]
If you have everything you need I think we can close it yes!
