### ISSUE TITLE
Setup Elastic _search endpoint

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#2656]
Setup the Elastic _search endpoint in `warp`.
- Create models (serialization/deserialization) for Request and Response 
- Come up with a strategy for updating changes in the models

SearchAPI Docs: https://www.elastic.co/guide/en/elasticsearch/reference/8.6/search-your-data.html
SearchAPI Docs: https://www.elastic.co/guide/en/elasticsearch/reference/8.6/search-search.html
API Spec:: [https://github.com/elastic/elasticsearch-specification](https://github.com/elastic/elasticsearch-specification)

**Comment by fmassot** [comment]
Closed by #3148
