### ISSUE TITLE
Use the REST API in the CLI when applicable

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2663]
The metastore should send events to the control plane so that a new source is immediately detected.

This can be done if the CLI uses a gRPC metastore or the REST API.

Currently, the CLI is using a quickwit config file but we just need to have an instance address if we use the REST API or the metastore address if we use the gRPC metastore.

**Comment by fmassot** [comment]
# Problem

I think we should start to distinguish between the quickwit server binary and the CLI (or CTL) binary. The CLI will only use Quickwit API to interact with a Quickwit cluster. 

Pros: 
- keeping all in one binary is confusing for a user
- code is cleaner as we separate the client from the server
Cons:
- This is a lot of work

## State of the CLI

- CRUD operations on indexes are partially covered by the REST API. GC is not covered.
- CRUD operations on splits are partially covered: we did not implement some filtering nor mark-for-deletion on the REST endpoints. Moreover, to extract a split, we need to get the info to connect to the storage backend to download the split
- CRUD operations on sources are partially covered. The enabling/disabling of a source is not covered.
- Merge/Ingest commands are not covered. We can probably drop the merge and  reimplement the ingest command with the ingest API or revamp the file source (cf #1159)

# Proposition for the 0.4.1

- Keep only one binary.
- Use the REST API for "common" CRUD operations - create/list/delete indexes/sources/splits + enabling/disable sources. This means that we need to extend the split list and source REST API. For these commands, the user has to give a `--host` args (remote mode).
- Keep merge/ingest/extract/GC/mark for deletion commands, but these commands must be executed on a node (local mode). We can migrate them progressively so that they will also work on a remote client.

**Comment by fulmicoton** [comment]
> Keep merge/ingest/extract/GC/mark for deletion commands, but these commands must be executed on a node (local mode). We can migrate them progressively so that they will also work on a remote client.

I'm not sure what local mode here, so I suspect it will be confusing for the user.
If I have a cluster running and I run ingest, what happens?

**Comment by fmassot** [comment]
Yes, it's not clear. Let's ditch `local` word.

We can distinguish two types of commands:
- commands that are hitting the REST API and thus require only an `endpoint` to be executed.
- commands that require a node config and access to metastore and object storage.
