### ISSUE TITLE
Implement `quickwit dataset` CLI command

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2681]
This Quickwit command will allow users to list the available datasets and download a specific dataset.

`quickwit dataset list` -> list datasets available for download
`quickwit dataset pull <dataset name>` -> download the dataset

**Comment by Abhicodes-crypto** [comment]
I'd like to work on this.

**Comment by fulmicoton** [comment]
With hindsight this was probably a terrible idea :D
closing.

**Comment by Abhicodes-crypto** [comment]
Yes I would like to help with that

**Comment by eliKalter** [comment]
I am interested in collaborating with someone on their project so I can learn the language while they get a  sidekick.
Let me Know if this is something that could work for you.
I Would need you to explain and guide me through my first steps in the language (I already started learning) and set the standard for me in code reviews but after a short while I'm sure I'll become an asset to the project.
(I have some experience in Typescript and Java and have learned C a few years ago).

**Comment by Abhicodes-crypto** [comment]
@eliKalter , This issue has been closed.
