### ISSUE TITLE
[EPIC] Generic routing

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2707]
Currently, we have some ad-hoc logic in some places to reroute some requests from one node to another, but we need to solve this problem with a more generic solution.

We want to put a router in front of all the requests that decides whether a request can be satisfied by the node or should be forwarded to another one.

Goals: 
- any node can satisfy any request.
- efficient routing, i.e., minimizing the number of hops
- remove ad-hoc logic and reduce boilerplate

Linked issues:
- [x] #2705
- [x] #2706

**Comment by fulmicoton** [comment]
Do we keep this on 0.6?

**Comment by guilload** [comment]
After landing #3332 and #3243, routing requests has become much easier, so we're close. What needs to be added is the ability to route a request from an actor on node A to another on node B, but we can tackle that later. There's no pressing need for this.
