### ISSUE TITLE
Doc: node configuration page isn't up to date

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit#2714]
https://quickwit.io/docs/configuration/node-config/ misses some information, and contain some outdated ones.
- `split_store_max_num_bytes` default is is 100G, not 200G
- `split_store_max_num_splits` default is 1k, not 10k
- `fast_field_cache_capacity` is 1G, not 10G
- `split_footer_cache_capacity` is 500M, not 1G
- `ingest_api` and children keys are missing

(list not exhaustive)

**Comment by fmassot** [comment]
Link to the repository doc page: https://github.com/quickwit-oss/quickwit/blob/main/docs/configuration/node-config.md?plain=1
