### ISSUE TITLE
Documentation for storage-uri's is a dead link

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2764]
The hyperlink here: https://quickwit.io/docs/configuration/index-config/#index-uri

Takes you to:
https://quickwit.io/docs/configuration/reference/storage-uri

But this is a 404

![image](https://user-images.githubusercontent.com/57491488/217236335-475e742b-8efa-4a6d-a187-36b02b2a1699.png)

**Comment by fmassot** [comment]
Fixed by @ChillFish8.
