### ISSUE TITLE
The install does not really install

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#277]
It just puts a binary in the CWD if I understand correctly. That's ok with me, but we should probably put a message explaining that somewhere.

Ideally we could have an extra step offering `sudo mv` it to /usr/local/bin .

**Comment by fulmicoton** [comment]
Opinions @fmassot ?

**Comment by fmassot** [comment]
I think this is ok for our first release. I prefer let the user do the mv himself, he will know better where to put it.

**Comment by fulmicoton** [comment]
Ok for me!

**Comment by evanxg852000** [comment]
It is absolutely possible to have step that actually puts it in somewhere like `/home/<user>/.quickwit-inc/quickwit` and adds it to the user path.

**Comment by fulmicoton** [comment]
Well let's not do it for the moment.
