### ISSUE TITLE
Grafana indexer dashboard broken with multiple indexes

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2787]

**Comment by guilload** [comment]
The fix is to change the label filter operator from `=` to `=~`.

**Comment by guilload** [comment]
Turns out you can have two-way sync between host and contain on Linux with the `shared`, which makes iterating on dashboards much easier. This is not possible on macOS.

```
volumes:
    - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:shared
```
