### ISSUE TITLE
ingesting via file source often fails for no obvious reason to the user

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit#2857]
**Describe the bug**
the new file "source" sends files by chunks of 5k lines, which on some dataset can go over the limit of what the ingest api accepts.
On gh-archive, I had to lower that number to 800 to not actually get errors, but on worst dataset (or worst batch of the same dataset), this might not even be enough.

Instead of counting lines, we should count bytes and send just what the api will allow

**Steps to reproduce (if applicable)**

try to ingest a few hours of gh-archive dataset with the file source.

**Expected behavior**
it ingests without throwing an error

**Comment by fmassot** [comment]
I had the same issue on the wikipedia dataset. We should get the size of each json line and ensure that we respect the API limit.
