### ISSUE TITLE
test_indexing_pipeline_retry_1 sometimes fail

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2865]
https://github.com/quickwit-oss/quickwit/actions/runs/4237637962/jobs/7363833327

**Comment by fmassot** [comment]
`test_indexing_pipeline_simple` is also concerned.

The tests expect a pipeline of generation 1 to end successfully, but on the CI, it seems that we end up with generation > 1. Which was not the case before :/

**Comment by fmassot** [comment]
I fixed the issue by not using `Universe::accelerated_time()` and instead using a regular `Universe`.

The real issue is that `accelerated_time` does not play well with the supervision of the indexing pipeline. I will open an issue on this as we may encounter this kind of failure in other tests.

**Comment by fulmicoton** [comment]
Fail with more logs.
https://github.com/quickwit-oss/quickwit/actions/runs/4240945047/jobs/7370553001
