### ISSUE TITLE
Disabling the ingest API for a given index does not prevent from pushing documents

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2904]
**Describe the bug**

Currently it's possible to disable an ingest API source. It shuts down the pipeline but the ingest service will still accept incoming documents.

From a user's point of view, this is bad as he can wrongly push documents and fill the queue without any feedback.

**Expected behavior**
Quickwit should return a 404 error on a ingest request when the ingest source is disabled.

**Potential solutions**

The fundamental issue we have with the ingest API is that it is unaware of the index/source config; requests are forwarded directly to the ingest service. This will change in the future as we will need to make schema validation. 
But for the 0.5, a workaround would be nice to find.

Let's list three possible solutions:

- When enabling and disabling the ingest API source, we can delete/create the queue. This will work nice but... this means that disabling can delete data that is not indexed yet.
- We can add a flag on the ingest service to indicate the queue of a given index_id is closed or opened: this adds complexity, so let's not do that... 
- We can simply remove for the 0.5 the ingest API source enabling/disabling feature . This is probably a good short-term solution.

**Comment by guilload** [comment]
Disabling the enable/disable feature has my vote.
