### ISSUE TITLE
Make dynamic mode the default, and allow for the mapping to be empty

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2910]
With the addition of fast fields, it is more and more appealing to make the dynamic mode the default, and to allow for 
the mapping to be unspecified.

Users could then supply quickwit a very minimal document mapping:

```yaml
version: 0.4
index_id: my-dynamic-index
```

The bummer of course is the absence of timestamps at this point :-(

**Comment by peacand** [comment]
In that case, you would have an issue to search on your data by default : https://github.com/quickwit-oss/quickwit/issues/1829#issuecomment-1519675765

Should you also set record="position" by default so that users will be able to search easily out of the box ?
