### ISSUE TITLE
Plug tantivy's range query into QUickwit

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2913]
Quickwit uses an adhoc solution to filter per timestamp.
It is actually broken for optional columns.

tantivy has a nicer solution for fast field based range query. Can we plug it in quickwit for the time filtering?

Range by string would be great too

**Comment by PSeitz** [comment]
It doesn't seem to be broken for optional columns.

```

impl TimestampFilter {
    #[inline]
    pub fn is_within_range(&self, doc_id: DocId) -> bool {
        if let Some(ts) = self.timestamp_column.first(doc_id) {
            self.time_range.contains(&ts)
        } else {
            false
        }
    }
}
```

**Comment by fulmicoton** [comment]
I confirmed this works for optional values.

I'm not sure there is a good valuable heuristic to rely on the tantivy's range query here, when we are not facing a RangeQuery. I'll open a separate ticket to have it for AllQueries maybe. but this is low priority.
