### ISSUE TITLE
Add endpoint to get basic information on the index

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2942]
It was asked by a user and while I'm testing Quickwit, I think it can be very nice to get these info from the index via the REST API:
- size of the index
- number of documents
- number of splits

Finally, having something that is quite similar to what we have in `quickwit index describe` command is finally what a user would want to know about an index.

**Comment by gagan-gaurav** [comment]
I want to contribute in this project, can some one tell me what are the files i need to change for above enhancement or how to approach it, i am new to this project.

**Comment by fmassot** [comment]
HI @gagan-gaurav! You will find the REST handlers  [here](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-serve/src/index_api/rest_handler.rs#L58-L77).

There is a CLI `describe` command that is doing what we want but on the CLI side, the code is [here](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-cli/src/index.rs#L497-L512).

You can read the [CONTRIBUTING](https://github.com/quickwit-oss/quickwit/blob/main/CONTRIBUTING.md) to have instructions to start coding on Quickwit. And you can join our [discord server](https://discord.gg/MT27AG5EVE) of course :)

**Comment by gagan-gaurav** [comment]
Thanks @fmassot!  I will be looking into it and try to implement the above enhancement, In case i required any further help, i will be getting back to you :)

**Comment by gagan-gaurav** [comment]
![Screenshot from 2023-03-10 03-24-42](https://user-images.githubusercontent.com/51356017/224169249-90ea90b4-276d-4590-bb18-36c5ecdbf872.png)
@fmassot this is the new index describe API that i added, it is working fine. should i make a PR?

**Comment by gagan-gaurav** [comment]
can u review this PR #2971

**Comment by Narayanbhat166** [comment]
This issue seems to be addressed. Can it be closed?

**Comment by fmassot** [comment]
thanks @Narayanbhat166 you're right, closed notably with #2996
