### ISSUE TITLE
Wrong revision of Tantivy?

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#2967]
**Describe the bug**

The current Cargo.toml is using a revision of Tantivy corresponding to a dangling commit https://github.com/quickwit-oss/tantivy/commit/116c6d3

https://github.com/quickwit-oss/quickwit/blob/eccd16bdb3be0badd8c990ec3ff45cbd7835057a/quickwit/Cargo.toml#L223

**Steps to reproduce (if applicable)**

N/A

**Expected behavior**

I would expect it to point to a non-dangling commit on some branch.

**Configuration:**
N/A

**Comment by trinity-1686a** [comment]
I've restored the corresponding branch, but quickwit shouldn't depends on commit from non-main

**Comment by fulmicoton** [comment]
PR#2976

This is still not attached to the main branch... because I had to add hotfixes, but it is tagged, which is sufficient to avoid the rev to be GCed by github.

**Comment by fulmicoton** [comment]
Fixed in https://github.com/quickwit-oss/quickwit/pull/2976
