### ISSUE TITLE
Ensure we are not missing fixes in the tantivy tag quickwit 0.5

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2977]

**Comment by PSeitz** [comment]
This commit should be included: https://github.com/quickwit-oss/tantivy/commit/3da08e92c78e25a1ac67581718b2c495ad0420fc

**Comment by fulmicoton** [comment]
Done... Ticket in tantivy https://github.com/quickwit-oss/tantivy/issues/1938
tag in tantivy repo quickwit-0.5-rev
