### ISSUE TITLE
Systematic  incremental compilation error on quickwit

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2983]
I have this error for a few days when compiling `quickwit-serve` or `quickwit-cli` for executing test or for using the CLI:

```bash
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(dea4b59d871cfb72-948ebd8b8d3fb5d0)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p quickwit` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(dea4b59d871cfb72-948ebd8b8d3fb5d0): Ok(EvaluatedToAmbig)', compiler/rustc_query_system/src/query/plumbing.rs:684:9
stack
```

The backtrace is super super long so I won't put it there. But I noticed that I don't have this incremental compilation error if I revert the modification made here https://github.com/quickwit-oss/quickwit/commit/eccd16bdb3be0badd8c990ec3ff45cbd7835057a

To be able to work, I revert this change.

**Comment by fmassot** [comment]
Here is the full backtrace

[full_backtrace.txt](https://github.com/quickwit-oss/quickwit/files/10952471/full_backtrace.txt)

**Comment by imotov** [comment]
I wonder if this is arm64 Mac - specific. I have been experiencing the same.

**Comment by trinity-1686a** [comment]
I can reproduce on linux x86_64. I haven't found a ticket with that specific error (`Ok(EvaluatedToAmbig)`) upsteam.

In the meantime, we should set [`build.incremental = false`](https://doc.rust-lang.org/cargo/reference/config.html#buildincremental), that will increase compilation time, but still better than having to `cargo clean` every time
