### ISSUE TITLE
Quickwit panics while attempting to parse `index_uri`.

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2991]
Quickwit panics when parsing `http://localhost:9000/quickwit` as the index_uri config value.
The value should be reported as an invalid error since  index_uri expect a [storage_uri](https://quickwit.io/docs/reference/storage-uri)

**Comment by guilload** [comment]
What's the use case for an HTTP index URI?

**Comment by ChillFish8** [comment]
I should clarify, it wasn't meant to be an HTTP uri, but if you give it one it'll panic and say it's a bug rather than say it's invalid.
