### ISSUE TITLE
Swagger UI tail endpoint does not work

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3002]
When hitting execute on tail, the browser emits a request to `http://localhost:7280/api/v1wikitenant/tail`
instead of `http://localhost:7280/api/v1/wikitenant/tail`

Search does work as intended.

**Comment by ChillFish8** [comment]
This should already be fixed 
![image](https://user-images.githubusercontent.com/57491488/227494339-e6a9db21-0f1c-4ce9-a510-59dd87199da3.png)

**Comment by fulmicoton** [comment]
@fmassot I think it was fixed for Quickwit 0.5.0
