### ISSUE TITLE
Index selector combo box still broken some time

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3027]
I don't know if this is because I need to recompile the webapp bundle or somthing like that...

![Quickwit UI](https://user-images.githubusercontent.com/1021506/225515497-c5a27027-d69d-47c8-aa56-3e77de3fa241.gif)

**Comment by fulmicoton** [comment]
The bug is confirmed in main

**Comment by fulmicoton** [comment]
Still broken when using Ctrl + Enter instead of clicking on the button

**Comment by fmassot** [comment]
Closed by #3043
