### ISSUE TITLE
Add an internal incarnation number/id to the index id for the control plane

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3041]
Currently, the control plane has a dreadful glitch if we delete an index and swiftly recreate an index with the exact same name. (This is a rather common operation.)

The control plane will not have time to stop existing pipelines, and will be perfectly happy to see a pipeline already running with the specified index id.

As a fix for #3036, I suggest we introduce the notion of incarnation number for our index id.

This number is never used/shown to the user. 
The index id is still unique at any moment of time.

The point of this incarnation id is to make it natural for the control plane to  notice that the instance before the delete/create operaiton has happened is obsolete.

In the future, this incarnatin is also an elegant way to allow a change of conifguration.
We can simply bump the incarnation number when a change is operated.

We also need to take change the incarnation of `clear index` for the same reasons.

**Comment by fmassot** [comment]
We probably want to do the same thing at the source level. For handling delete/create of a source and `reset-checkpoint`.

**Comment by fulmicoton** [comment]
Assigned to @imotov
