### ISSUE TITLE
The API screen does not show the necessary api/v1 prefix.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3100]

**Comment by ph** [comment]
I am just looking at `bug` labelled issues, sorry for the noise If I make mistakes.

I assume that `The API screen` means the  API section in the `quickwick-ui`, if this is the case, it appears to correctly have the required `api/v1` prefix at least in the 0.5 release, I've used the multiple examples in the UI and they have all the right paths. 

![20230417_18h44m21s_grim](https://user-images.githubusercontent.com/640/232626748-3edac84f-026e-47d8-88c6-12f886989fab.png)

**Comment by fmassot** [comment]
@ChillFish8 I think you fixed this issue right?

**Comment by ChillFish8** [comment]
Yes I did when cleaning up the oppenapi stuff

**Comment by fmassot** [comment]
Cool, thanks for the review @ph, closing...
