### ISSUE TITLE
longer timeout for ingestion query with wait/force commit

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit#3137]
Currently the timeout is always 10s, which is fine to just push data, but when waiting for a commit, it can easily take a good minute (commit timeout), even more if too much data got buffered. The last ingest query made by the cli should be longer to account for that, and possibly tunable

**Comment by imotov** [comment]
I just ran into this while trying to index hdfs-logs sample dataset with a force flag. I can take this issue.
