### ISSUE TITLE
Add warnings on storage AWS credentials errors

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3139]
We don't log any errors on credentials errors when connecting to S3.

PR in WIP here: https://github.com/quickwit-oss/quickwit/pull/3120

**Comment by fmassot** [comment]
Can you takeover on this @ChillFish8 ?

**Comment by ChillFish8** [comment]
Sure 👍

**Comment by guilload** [comment]
Moving to the AWS SDK fixes this issue, assuming we can log those errors in the Rust crate.
