### ISSUE TITLE
Dual-licence quickwit-actors as something more permissive than AGPL

### ISSUE THREAD

**Issue by Alxandr** [quickwit-oss/quickwit#3144]
**Is your feature request related to a problem? Please describe.**
I watched the [FOSDEM talk](https://fosdem.org/2023/schedule/event/building_an_actor_library_for_quickwits_indexing_pipeline/) about how you built an actor library and was very interested in parts of it. I'm currently writing a library for creating Home Assistant MQTT addons in Rust, and would like to model that using actors (every light is an actor). However, my project is released as MIT, and I do not wish to change it to AGPL. I'm pretty sure I recall in the talk the speaker said he might be willing to change the licence, so before I start adoping another library I figured I'd at least just ask.

**Describe the solution you'd like**
An MIT compatible license for quickwit actors.

**Describe alternatives you've considered**
Using another actor library or making my own.

**Additional context**
I tried searching the issue tracker for whether or not this has been requested in advance. Also, if this is not something you would like to do, feel free to just close this issue.

**Comment by fulmicoton** [comment]
I think switching to MIT is ok. We might need to warn that we won't be able to afford caring too much about community requests or even making sure we don't break backward compatibility for a while.

**Comment by Alxandr** [comment]
That's perfectly reasonable. I'm planning to take parts of the code, not use it as a library (though linking back ofcause).

**Comment by fulmicoton** [comment]
Sorry for the late reply. A light PR is in the way to license quickwit-actors under MIT license.
I did not have time to fight much with the code. There is still a dependency on AGPL project unfortunately.

It should be sufficient for you to fork and/or copy paste code however.

**Comment by Alxandr** [comment]
Definitely. Thank you very much. It's very interesting seeing how you've solved different issues such as the time skipping in this codebase. If I end up making something (re)-usable, I'll post a link.
