### ISSUE TITLE
start_timestamp, end_timestamp parameters should return an error without timestamp field defined

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#3167]
Currently these parameters are just silently ignored

**Comment by JerryKwan** [comment]
@PSeitz 
Would you please give more information about this bug? How can we reproduce the problem? thank you

**Comment by PSeitz** [comment]
Create and index without a timestamp field defined and run a search query with start_timestamp and end_timestamp filter.

Do you want to take over the issue?

**Comment by JerryKwan** [comment]
Hi @PSeitz 
Thanks for the information
I will try to re-produce the problem,and then look into the codes and keep you posted about the progress, thank you

**Comment by JerryKwan** [comment]
@PSeitz 
please help to review the PR, thank you
[PR3870](https://github.com/quickwit-oss/quickwit/pull/3870)
