### ISSUE TITLE
localstack in docker compose script doesn't start after localstack's 2.0 release

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#3177]
**Describe the bug**
LocalStack 2.0 was released 2 weeks ago and it removed a deprecated initialization setting that we were using in our docker-compose.yaml script. So, if you pull the latest image, docker compose no longer starts. In other words it looks like we ran into localstack/localstack#8127.

**Steps to reproduce (if applicable)**

1. run `make docker-compose-down`
2. run `docker image rm localstack/localstack`
3. run `make docker-compose-up`
4. observe this command failing unable to start the localstack container

**Expected behavior**
Command should succeed.

**Other thoughts:**

I am going to open PR to fix this particular problem in a bit, but I would also like to discuss this issue in general. We are using the `latest` tag in a couple of places and it looks like we missed this issue for a couple of weeks, which basically means that if somebody new tried to build quickwit in the last 2 weeks they had a bad time. There are a few ways of preventing this from happening in the future with their own pros and cons:

1. We can add `pull_policy: always` to our script to make sure we are pulling new images whenever they become available. This might make building while with bad internet connection more difficult, but will guarantee that we are always working with the latest version.
2. We can add some command only to CI script that would force pull. That will not affect building locally, but somebody will pull the short straw of opening PR just after a breaking change in the image, which can be disruptive to this person.
3. We can also replace the "latest" tag with the actual versions and update manually, but than we need some process for bumping the versions.

**Comment by guilload** [comment]
I vote for 2.
