### ISSUE TITLE
Make it possible to set a fast field normalizer for JsonOptions and the dynamic mode.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3179]

**Comment by fulmicoton** [comment]
@PSeitz  Can you connect the dots and edit the QuickwitJsonOptions to forward that info to tantivy?

**Comment by PSeitz** [comment]
Related https://github.com/quickwit-oss/quickwit/issues/3246

**Comment by fulmicoton** [comment]
Can we close this?

**Comment by PSeitz** [comment]
yes
