### ISSUE TITLE
Using :latest tag in docker compose

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#3184]
Currently, we are using `:latest` tag for several images in docker-compose script that starts services for our test environment. Since docker compose doesn't pull new images in our current configuration, it means that we are testing against different versions of several services. Basically everybody are using whatever was the "latest" version when they ran this script the first time. I see a couple of issues with that:

1. We don't detect breaking changes in these dependencies, which can lead to bad newcomer experience. See #3177, for example, I only noticed the issue after 2 weeks because I recently rebuilt my linux machine.
2. We might be running old images that might have security vulnerabilities on our development machines. That can be mitigated to a certain degree by #3183, but at the moment I think it is an issue.

Any thoughts/suggestions?

**Comment by ph** [comment]
Hello @imotov (it's been a while! it's a small world)

I was also hit by the same issue with `localstack` when bootstrapping this project and  I have also fixed my issue by using a previous version. Concerning, the forward steps, I think its logical and totally OK to fix a project to a predefined version of the dependencies this ensure that the project is tested with a fixed matrix of version and limits the explosion of things to verifies and support. This make it clear to the user what work with what too.

Nothing prevent you to add a new job on the github CI that would pickup the `latest` version of the containers and run the test suite, maybe a subset of the suite to not slow down the run. Also this would be up to you to make it block a pull request or not.  The downside of this approach is it may cause developers to ignore a failure of a job..

**Comment by guilload** [comment]
Let's go ahead and use fixed versions for our Docker compose images. For critical components such as PostgreSQL, Kafka, and Pulsar, we can use the earliest versions that are not EOL and upgrade as they become EOL.

For mocks and telemetry components, we can use the current latest versions and upgrade them once in a while or as needed (bugs, deprecations, need for a new feature).

The CI job on `latest` is also a good idea. There's probably a way to avoid duplicating the GitHub Actions workflows using different `.env` files, and run the `latest` workflow on a weekly (monthly?) basis. However, I ignore how we will be notified in case of failure. Finally, I don't know if we want to invest too much time in this at the moment. Your call, @imotov.
