### ISSUE TITLE
Make REST API Grafana JSON Plugin compatible

### ISSUE THREAD

**Issue by pachico** [quickwit-oss/quickwit#319]
Grafana provides an out of the box JSON plugin that might allow QW to have a UI, at least for certain use cases, if its REST API was compatible with it.

- JSON Plugin Specs: https://grafana.com/grafana/plugins/simpod-json-datasource/

**Comment by fulmicoton** [comment]
Thank you for th epointer @pachico

**Comment by fulmicoton** [comment]
Unfortunately we need to move this to quickwit 0.5

**Comment by guilload** [comment]
See https://grafana.com/grafana/plugins/quickwit-quickwit-datasource.
