### ISSUE TITLE
Improvement: Factorize the retry logic in /cluster_sandbox.rs

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3214]
We have many instances of the following snippet.

```rust
      let mut num_attempts = 0;
        let max_num_attempts = 3;
        while num_attempts < max_num_attempts {
            if num_attempts > 0 {
                tokio::time::sleep(Duration::from_millis(100 * (num_attempts))).await;
            }
            if blah()
            {
                return Ok(());
            }
            num_attempts += 1;
        }
        if num_attempts == max_num_attempts {
            anyhow::bail!("Too many attempts to get expected number of pipelines.");
        }
        Ok(())
```
(by the way why is this a while loop O_o and what is the point of the `  if num_attempts == max_num_attempts` statement)

We should probably factorize it into something that looks more like 

```
async fn wait_for<Cond, Fut>(awaited_condition: impl Fn() -> Fut) -> anyhow::Result<()>
    where
        Fut: Future<Output = anyhow::Result<bool>>,
    {
    const MAX_NUM_ATTEMPTS: u64 = 3u64;
    for num_attempts in 0..MAX_NUM_ATTEMPTS {
        tokio::time::sleep(Duration::from_millis(num_attempts * 100)).await;
        if awaited_condition().await? {
            return Ok(())
        }
    }
    anyhow::bail!("Failed after {MAX_NUM_ATTEMPTS} attempts")
}
```

if we really need different retry schedule, we can make that into a `struct`.
Similar function already exist in `quickwit_common/src/utils.rs`, and in the `retry.rs` files.

No need to end up with a single instance... but at least one instance for unit test would be nice.

**Comment by fmassot** [comment]
@fulmicoton I'm probably the culprit on this, I already added a `wait_until_predicate` function here: https://github.com/quickwit-oss/quickwit/blob/ea6d4fcf02d9ae02f79f26579fb157d76cf90059/quickwit/quickwit-common/src/test_utils.rs#L28

It uses a while loop too because it uses a timeout.
