### ISSUE TITLE
Add TCP_NODELAY to our client's socket

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3242]
Nagle's algorithm could well be the cause of our gRPC latency. 
It needs to be done on the client and the server side.

**Comment by trinity-1686a** [comment]
Tonic documentation says its already enabled by default for both [server](https://docs.rs/tonic/0.8.3/tonic/transport/server/struct.Server.html#method.tcp_nodelay) and [client](https://docs.rs/tonic/0.8.3/tonic/transport/channel/struct.Endpoint.html#method.tcp_nodelay)

**Comment by fulmicoton** [comment]
Yes closing. I shouldn't fill ticket in a rush.
