### ISSUE TITLE
Introduce two different tokenizer manager. One for indexing one for fast fields

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3246]
Currently we have one tokenizermanager.

The situation is quite catastrophic, as we introduced fast field tokenizer that are not tokenziing without any hint in their name.
e.g.
en_stem is tokenizing
lowercase isnot tokenizing.

We want two TokenizerManager in tantivy and plug them in quickwit, that will act as namespaces for the indexer and for the fast fields.

**Comment by fmassot** [comment]
tokenizer manager is also a poor name. Why not introducing a `normalizer` field? (like in ES)

**Comment by fmassot** [comment]
Closed by #3404
