### ISSUE TITLE
Date histogram API discrepancies between OpenSearch and Elasticsearch

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3250]
For `airmail` project, we need to support the OpenSearch API. 

The date histogram OpenSearch uses the `interval` field:

```
json
{
  "size": 0,
  "aggs": {
    "logs_per_month": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "month"
      }
    }
  }
}
```

[Ref](https://opensearch.org/docs/latest/aggregations/bucket-agg/#histogram-date_histogram)

But tantivy supports only `fixed_interval` or `calendar_interval`. This corresponds to [ES API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html). The `interval` field was deprecated in version `7`.

We have two solutions:
- support the `interval` field in tantivy
- when parsing aggregation in Quickwit, we fix the query so that tantivy can run.

I suggest the first solution as the problem is "relatively" simple.

**Comment by fulmicoton** [comment]
Closed as not wanted. this feature is deprecated in both elastic and opensearch
