### ISSUE TITLE
Increase default bucket limit?

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3282]
When using quickwit with Grafana, I'm hitting the bucket limits. Slightly increasing up to 80~90 will avoid that (currently it's 60k).

I'm assigning this issue to myself as I'm not sure yet if this is a bad Grafana config or not.

**Comment by fulmicoton** [comment]
@PSeitz si working on something that should help a lot with this. Increasing the limit slightly is not a bad idea too.

**Comment by PSeitz** [comment]
This is about the bucket limit, which is unaffected by the change.

Hitting the bucket limit suggests the query requests too much data.

**Comment by fulmicoton** [comment]
Ah got it! Sorry for the noise.

**Comment by fmassot** [comment]
Closing... the issue comes from Grafana UI
