### ISSUE TITLE
Optimize sort by date

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3298]
This optimization is more important than it might look like. In particular it considerably improves
the AllQuery we run when reaching the UI screen, and the same logic could apply to tracing. (although we will have to replicate this logic)

The optim can be done on the leaf side (although it can be done on the root side in the case of the MatchAllQuery). 

On the leaf side, if a leaf node has a lot of splits, it could for instance process the splits in the most recent order. 
If a split about to be processed has max(timestamp) < current bottom k, we know it won't contribute to the top K.
We can disable the top K computation, hence removing the need to download the timestamp column.

If there are no aggregation, in the future we can also just run a count query. 

- [x] Avoid downlading the sorting field if K's top K = 0 
- [ ] Nullify K depending on the split metadata and previously processed splits.
- [ ] Integrate a similar optim in tracing. 

To complicate stuff a little more... In the future we might want to remove "accurate count", and let quickwit tell us "More than 10000 docs matching" for instance. Entire split could then be skipped.

**Comment by trinity-1686a** [comment]
>  Integrate a similar optim in tracing.

could you clarify? The jaeger interface either uses `root_search` which should benefit from the change anyway, and `root_list_terms` which isn't concerned by this optimization, so I think this comes free?
