### ISSUE TITLE
Inconsistent handling of long index names 

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#3308]
**Describe the bug**
A file-based metastore allows index names up to 255 characters long, while PostgreSQL metastore only allocates 50 characters for the index name. 

**Steps to reproduce (if applicable)**

1. Try create an index with more than 50 characters in its name using qw instance with PostgreSQL metastore.

**Expected behavior**
The index name limit should be consistent.

**Configuration:**
All version are affected as far as I can tell.

**Comment by fulmicoton** [comment]
Let's go with 255 as a limit and enforce the limit everywhere.
