### ISSUE TITLE
ES API does not fully support ES sort API

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3310]
In the Grafana plugin or for `airmail` project, sorts are defined by a JSON object... like this:

```json
{
  "query": {
    "match_all": {}
  },
  "sort": {"ts": {"order": "desc"}, "id": {"order": "desc"}}
}
```

This seems wrong as you cannot define an order. I suggest not supporting that and pushing for using an array.

**Comment by guilload** [comment]
If we must support this for some reason or another, we can use the `preserve_order` of `serde_json`. Returning documents exactly as they were passed to us would be a good feature too.

**Comment by fulmicoton** [comment]
I don't understand this ticket. What is ambiguous in your example Francois?
