### ISSUE TITLE
Support datetime range query with number

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3323]
Currently, for a range query on a datetime field, we convert the bounds only if they are defined as an `Rfc3339` string.

We could also support integer values (and maybe float?). But for that, we need to define a default unit.

I have a preference for milliseconds:
- it's clearly easier from the user's point of view... entering nanoseconds is very boring
- milliseconds will be the default format in aggregations too.
- (bonus) it's the default format in elasticsearch range query.

And if you need nanoseconds, then you have to express the bounds in `Rfc3339` strings.

**Comment by guilload** [comment]
I prefer SI units: so seconds coupled with support for float to handle subsecond digits. Otherwise, millisecond is ok. We should also support a date parser in range queries.

**Comment by fmassot** [comment]
> We should also support a date parser in range queries.

Do you mean by that to allow the user to define a format so that we are able to convert to the right unit internally?

**Comment by fulmicoton** [comment]
Wouldn't it be cleaner to apply try and parse according to `[output] + input_formats` (where + stands for concatenation).
The rationale here is that users are more likely to use the format that they see in the output. (and copy paste it)

I also suggest we default output format to the first `input_format`.
