### ISSUE TITLE
Make  INGEST_CONTENT_LENGTH_LIMIT configurable

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-oss/quickwit#3355]
Some deployment environments (Free Tier) are usually very limited in `content-length` that can be POSTed.
We still need to support those limitations on our end to make trying out Quickwit enjoyable. 
Currently during ingestion, `INGEST_CONTENT_LENGTH_LIMIT` has a good default set to 10MB but it would be nice to switch it to a command flag allowing users to specify it when invoking the ingest command if needed.

**Comment by fmassot** [comment]
Yes, we can add an argument to the CLI command.
`index ingest --index {my-index} --ingest-content-length-limit {my-limit}`

The arg is a bit long though.
