### ISSUE TITLE
Scratch directories are not being deleted

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#3363]
**Describe the bug**
If I delete and create an index with the same name, scratch directories in the following paths are not getting deleted:

/qwdata/delete_task_service/{index_name}/{ulid}/scratch
/qwdata/indexing/{index_name}/{ulid}/scratch

**Steps to reproduce (if applicable)**

1. Create and delete an index with the same name 5 times
2. Restart the server
3. Create and delete an index with the same name 5 more times
4. Check qwdata directory

**Expected behavior**
Unnecessary scratch directories should be deleted on pipeline shutdown.

**Comment by fulmicoton** [comment]
Crash also needs to be considered.
