### ISSUE TITLE
Lift the no array accepted limitation associated with objects.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3371]
Related with #3296.

The ticket suggests we should use the raw tokenizer by default for json/dynamic stuff.
Then explains user can then go and override this configuration for the few fields that do contain actual text.

A typical example of this is our beloved gharchive example.

```json
{
  // ...
  "payload": {
     //...
     "commits": [
      {
        "author": {
           //...
        },
        "distinct": true,
        "message": "This is an exmaple commit message",
      }
    ],
//...
}
```

here commits message are typically something we want to see tokenized and indexed.

Right now, setting `message`'s indexing setting is not possible, because it would have to be done by defining a docmapping object.

Because we do not handle array's of objects, anything within `payload.commits[]` cannot be part of the static schema.

This limitation exists to avoid the ambiguity of a composite query attempting to describe a predicate over one specific commit.

For instance, `payload.commits.author:fulmicoton AND payload.commits.message:ornythorinque`.
Quickwit will always reply document matching these two terms query independently from whether they appear on the same commit.

Should we lift this guard and let user configure a field with a `type: array<object>`

**Comment by fmassot** [comment]
We probably can lift the guard. It makes sense to have this type `type: array<object>`.

As I'm very lazy, I'm wondering if defining just a field `payload.commits.message` with `expand_dots: true` will just work without the need for defining a long and tedious object in the `doc_mapping`.

**Comment by fulmicoton** [comment]
Today, it does not work. Expand dots only influences the dynamic stuff.
We can probably tweak the behavior, but there are implications to that too.

For instance, do we allow weird stuff like:

```yaml
payload:
     
payload.commits:
```

**Comment by fulmicoton** [comment]
Discuted offline. Let's go for `array<object>`

**Comment by fulmicoton** [comment]
Ok there is a big technical obstacle to that plan... to generate JSON (to return hits) from tantivy Documents, we need to somehow place the values in the right place of the array... :(

**Comment by fulmicoton** [comment]
Closing as won't fix. We will try to find a better approach for 0.7
