### ISSUE TITLE
Raising the token limit to `255`.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3372]
Make sure the tokenizers in quickwit, and in particular the raw tokenizer has a token limit of 255 (as opposed to 100 today).
(This is enforced by a TokenFilter.)

Extra careful. @PSeitz is introducing a new tokenizer-manager for fast fields. We want to modify both.

Related with #3296

**Comment by PSeitz** [comment]
I assigned myself since I do some changes there anyways

**Comment by PSeitz** [comment]
What about the default and en_stem? They have a limit of 40 currently

**Comment by fulmicoton** [comment]
we can raise to 255 too.

**Comment by fmassot** [comment]
Closed by #3404
