### ISSUE TITLE
Architecture: Deployment considerations - SeaweedFS for tiered storage and metadata storage

### ISSUE THREAD

**Issue by AlexMikhalev** [quickwit-oss/quickwit#338]
The really impressive and inspiring project, one thing may be worth considering for practical deployment: 
1) Have a look at leveraging https://github.com/chrislusf/seaweedfs/wiki for deployment ( I found it after a lot of research in practical distributed storage): 
* Fuller with S3 configuration will give a throughput of nearest SSD disk (-network bandwidth) 
* Seaweed supports tiered storage https://github.com/chrislusf/seaweedfs/wiki/Tiered-Storage which allows to move index from faster to slower storage 
2) Seaweeds metadata storage can be re-used for quickwit triggering indexing and metadata. 

I hope it helps. 

Regards,
Alex

**Comment by fulmicoton** [comment]
We do support any S3 compatible storage using custom endpoint.
