### ISSUE TITLE
[Tracing] Allow users to query trace and spans IDs with hex encoded IDs

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3385]
We should also output them in hex.

**Comment by fulmicoton** [comment]
that certainly makes sense.

**Comment by fmassot** [comment]
I think it’s worth using hex encoding as soon as possible as this is the standard (defined in the open telemetry specification, used in jaeger and grafana). I suggest to move to hex for the 0.6.

**Comment by fulmicoton** [comment]
Ah so we need that for 0.6? ok then.

So we have several issue here:
- output format (what Quickwit is spewing)
- input format
- query format.

Do we want this configurable or always hex?
Can we have an example of what the configuration should look like too?

My 50c, I would follow what we did for dates, and have the input format == query format.

**Comment by fulmicoton** [comment]
Do we want that for 0.6? How painful is with grafana?

**Comment by fmassot** [comment]
Currently, we store the trace ID encoded in base64 in a raw text field. My intent was to encode the trace ID in hex instead of base64 and that's it.

> How painful is with grafana?
We don't use the Grafana trace UI as of today. So no real pain there.
