### ISSUE TITLE
Test AWS credentials with a resource’s IAM role and add it to the documentation

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#340]
Currently, we support AWS credentials by setting env variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`.
It would be nice to support other mechanisms such as credentials with IAM role.

**Comment by guilload** [comment]
We actually got that [right](https://github.com/quickwit-inc/quickwit/blob/c4e20740004a78fd58483d2bd9ca3a8005733ee4/quickwit-storage/src/object_storage/s3_compatible_storage.rs#L74). Our storage implementation relies on a [provider chain](https://docs.rs/rusoto_credential/0.47.0/rusoto_credential/struct.DefaultCredentialsProvider.html), which reads from multiple sources. On the other hand, our documentation is misleading and should be fixed.

**Comment by fmassot** [comment]
Indeed, I would like to test it though, and then update the docs.

**Comment by fmassot** [comment]
I tested it and it works. 
We can add this in the documentation and put the link to rusoto credentials page. 
It's also worth saying that we have common errors because no region or wrong region is set in the env variable.
Are you still on it?

**Comment by guilload** [comment]
Yes, I'll find some time to update the docs.

**Comment by fulmicoton** [comment]
Related with #341 ?
