### ISSUE TITLE
remove range over timestamp_field from ast when extracted to start/end_timestamp

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit#3416]
**Is your feature request related to a problem? Please describe.**

https://github.com/quickwit-oss/quickwit/pull/3400 allow extracting timestamp ranges from the QueryAst, which yields a nice optimization when it allows more pruning. However the range is also kept in the QueryAst, which means matching documents will be filtered twice, which is a bit wasteful.

**Describe the solution you'd like**

In addition to the current const Ast visitor, we should probably implement some form of a mut Ast visitor to allow rewriting easily the query when there are obvious optimizations, such as removing said RangeQuery when it has been copied to the query metadata. 

~~**Describe alternatives you've considered**~~

**Comment by fmassot** [comment]
One remark: split pruning is made with timestamps with a precision in second. If we want to filter at millisecond precision, then... we need in some way to filter at this accuracy. 
I'm just bringing this point here, I did not look at the PR so I don't know if you are already taking care of that.

**Comment by trinity-1686a** [comment]
I did not :confused:

**Comment by trinity-1686a** [comment]
actually this breaks the partial request cache when called from ES api, such as when using the Grafana plugin. Partial request cache is at its best when Quickwit serves a dashboard so it's a shame it doesn't work
