### ISSUE TITLE
Multivalued OTLP attributes are collapsed

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3439]
If someone several attributes with the same name, instead of ending into

```json
{
   "attr": [val1, val2]
}
```

We just keep the last one.
```json
{
   "attr": val1
}
```

**Comment by guilload** [comment]
It's a feature: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute-collections :)
