### ISSUE TITLE
Ensure Bool tags (and possibly others) are not broken by the looser Query lagnage.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3441]
we can now search using true / false instead of 1/0

**Comment by fmassot** [comment]
On edge with gharchive dataset, `public:true` is working.

**Comment by fulmicoton** [comment]
We can add support for `public:1` very easily. This ticket is about the interaction with tags.
Limiting tags to raw string and u64 is probably for the better. (maybe it is already the case)

**Comment by trinity-1686a** [comment]
closed by #3449
