### ISSUE TITLE
I encounter an error and the final data count doesn't match when I attempt to simultaneously run two processes to write this data.

### ISSUE THREAD

**Issue by dongbin86** [quickwit-oss/quickwit#3452]
**Describe the bug**
when i use ```cat hdfs-logs-multitenants.json | ./quickwit tool local-ingest --index hdfs-logs ``` to ingest some data to local quickwit instance running with default config, 
![image](https://github.com/quickwit-oss/quickwit/assets/6269809/37dda409-39f5-4b2c-b7d5-e585176ab5a9)
![image](https://github.com/quickwit-oss/quickwit/assets/6269809/dc744aa0-7219-49f1-9b9a-ccbb024fb095)

**Steps to reproduce (if applicable)**

1.  ./quickwit index create --index-config hdfs_logs_index_config.yaml
2.  start 2 process  for ```cat hdfs-logs-multitenants.json | ./quickwit tool local-ingest --index hdfs-logs ```

**Expected behavior**

**Configuration:**
Please provide:

1. Output of `quickwit --version`  lastest 0.5.1
2. The index_config.yaml
#
# Index config file for hdfs-logs dataset.
#

version: 0.5

index_id: hdfs-logs

doc_mapping:
  field_mappings:
    - name: timestamp
      type: datetime
      input_formats:
        - unix_timestamp
      output_format: unix_timestamp_secs
      precision: seconds
      fast: true
    - name: tenant_id
      type: u64
    - name: severity_text
      type: text
      tokenizer: raw
    - name: body
      type: text
      tokenizer: default
      record: position
    - name: resource
      type: json
      tokenizer: raw
  tag_fields: [tenant_id]
  timestamp_field: timestamp

search_settings:
  default_search_fields: [severity_text, body]
indexing_settings:
  commit_timeout_secs: 1

**Comment by fmassot** [comment]
Hi @dongbin86 thanks for opening the issue.

You are starting Quickwit with a file-backed metastore that supports only one writer... so the results you have are expected.

You can avoid this problem in different ways. For example:
- use a postgresql metastore
- start one server `./quickwit run` and use the ingest API `./quickwit ingest --index my-index`. This way you are sure to have only one writer to the file backed metastore.

Tell me if you need more details.
