### ISSUE TITLE
Support `indices-stats` elasticsearch endpoint

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3526]
[Elasticsearch doc ref](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-stats.html)

Many fields returned by the endpoint do not make sense for Quickwit. For this issue, we will only focus on the following fields:

- `stats.primaries.docs.count`: number of docs in published splits
- `stats.primaries.size_in_bytes`: size in bytes of published  splits
- `stats.total.segments.count`: number of published splits

**Comment by PSeitz** [comment]
I think it should be 
`stats.primaries.store.size_in_bytes`
