### ISSUE TITLE
protoc failed: src/ingest_service.proto: File does not reside within any path specified using --proto_path

### ISSUE THREAD

**Issue by happysalada** [quickwit-oss/quickwit#3533]
**Describe the bug**

A bit of context first. I came accross this error while trying to package this for nixos. This software is great and I believe would be useful for a lot of people.
Admittedly nixos does things a little differently, it tries to build packages from an environment that is isolated, and you have to specify which dependencies are made available.

When trying to compile from source, this is the error I get (with version 0.5.2, but I've verified the error is the same with 0.6).
```
> Caused by:
       >   process didn't exit successfully: `/build/source/quickwit/target/release/build/quickwit-ingest-api-e40e5aa9f1f8c52e/build-script-build` (exit status: 101)
       >   --- stdout
       >   cargo:rerun-if-changed=src/ingest_service.proto
       >
       >   --- stderr
       >   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: protoc failed: src/ingest_service.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
       >   ', quickwit-ingest-api/build.rs:30:6
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
```
I'm not sure in this case what else protoc is expecting.

I've noticed the codegen function takes several arguments https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-codegen/src/codegen.rs#L29
and the last one is the `include`
I've tried patching the code of the quickwit-ingest crate build.rs to supply different arguments as the include, but I haven't found what I should supply for it to work.

you can see in the PR where I'm trying to build this https://github.com/NixOS/nixpkgs/pull/235929/files#diff-8af85cb0961fb9a8124aca5e4d768ef7612a7770cc27e7bb06a90dd9a3b34a57R44
that I'm trying to pass `PROTOC` and `PROTOC_INCLUDE` both as environment variables, but I'm still missing something.
Just to give more details on what the PR is doing , it's running cargo build with `--frozen` and with `vendored dependencies` . ( I can explain why if you are interested in the details, but the gist of it is for reproducibility).

I realize this might not be enough details, I'm happy to provide more if needed, and test things if you have ideas.

Thanks again for this great software!

**Comment by guilload** [comment]
Can you patch the `build.rs` file so that include is an absolute path to the `quickwit-ingest` directory?

```rust
Codegen::run(
        &["src/ingest_service.proto"],
        "src/codegen/",
        "crate::Result",
        "crate::IngestServiceError",
        &["DocBatch.doc_buffer"],
        &["."],
    )
    .unwrap();

**Comment by happysalada** [comment]
the fix you originally suggested worked perfectly!
```
    substituteInPlace ./quickwit-ingest/build.rs \
      --replace '&[]' '&["."]'
    substituteInPlace ./quickwit-control-plane/build.rs \
      --replace '&[]' '&["."]'
    substituteInPlace ./quickwit-codegen/example/build.rs \
      --replace '&[]' '&["."]'
```

Thanks for this.
I should be able to supply the package soon. The next step will be to make a systemd service for it.
Do you have anything already available ? (if not, it's not a problem at all, I just thought I wouldn't try to duplicate existing efforts).

Thanks again for the help!

**Comment by guilload** [comment]
No, we don't have scripts for Systemd yet.

**Comment by kvtb** [comment]
> the fix you originally suggested worked perfectly!
> 
> ```
>     substituteInPlace ./quickwit-ingest/build.rs \
>       --replace '&[]' '&["."]'
>     substituteInPlace ./quickwit-control-plane/build.rs \
>       --replace '&[]' '&["."]'
>     substituteInPlace ./quickwit-codegen/example/build.rs \
>       --replace '&[]' '&["."]'
> ```
> 
> Thanks for this. I should be able to supply the package soon. The next step will be to make a systemd service for it. Do you have anything already available ? (if not, it's not a problem at all, I just thought I wouldn't try to duplicate existing efforts).
> 
> Thanks again for the help!

The patch does not work for `v0.8.0` as the way `protoc` is launched has been changed.

**Comment by kvtb** [comment]
> > the fix you originally suggested worked perfectly!
> > ```
> >     substituteInPlace ./quickwit-ingest/build.rs \
> >       --replace '&[]' '&["."]'
> >     substituteInPlace ./quickwit-control-plane/build.rs \
> >       --replace '&[]' '&["."]'
> >     substituteInPlace ./quickwit-codegen/example/build.rs \
> >       --replace '&[]' '&["."]'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks for this. I should be able to supply the package soon. The next step will be to make a systemd service for it. Do you have anything already available ? (if not, it's not a problem at all, I just thought I wouldn't try to duplicate existing efforts).
> > Thanks again for the help!
> 
> The patch does not work for `v0.8.0` as the way `protoc` is launched has been changed.

```
--replace '.with_protos' '.with_includes(&["."]).with_protos'
```
does help
