### ISSUE TITLE
Support Elasticsearch Scroll API

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3551]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html

We need the scroll API to be able to back an infinite scroll UI efficiently.  We can assume most request with a scroll id will be followed by actually using the scroll_id.

On Elasticsearch side, this feature is getting deprecated for `search_after`.
Emulating the same functionality require however creating a PIT (point in time).

Contrary to elastic we can limit this functionality to 1h (!? need verification)

**Comment by fulmicoton** [comment]
Whether we do it with search_after + PIT or the scroll api we will have some context, implicit or explicit.

For PIT, the context could be implicit if we modify the metastore.
For instance, we could have some autoincremental version number associated to each index.
When the set of splits changes we increment the counter.

The split would then have `publish_version` and a `retire_version`.
The PIT then just becomes the version. 

Getting the list of splits at a given point in time is simply given by picking the list of splits with 
publish_version <= PIT
retire_version == NULL or retire_version > PIT.

The grace period should then ensure that the splits are still present on the metastore.
