### ISSUE TITLE
The strptime datetime parser doesn't support %s

### ISSUE THREAD

**Issue by magnalite** [quickwit-oss/quickwit#3556]
Data I want to ingest has ended up with timestamps formatted as `seconds.milliseconds` eg `1686764678.9197`. I could transform these into ints however for large volumes of data that can be painful. I would instead like to parse it using the strptime parser via `"%s.%f"` however it doesn't recognise `%s` (a unix timestamp in seconds).

**Comment by fulmicoton** [comment]
Also, I'd love to have a sandbox in the UI for people to copy and paste their stuff and get visual feedback of how it is interpreted by quickwit.

**Comment by fulmicoton** [comment]
Ok so after investigating, ideally this means adding support for "%s" in [time-fmt](https://github.com/MiSawa/time-fmt).

**Comment by magnalite** [comment]
> Just to be sure, can you confirm that your data is fed as a JsonString (as opposed to JsonNumber)

I believe it is a JsonNumber. My data looks like this in its raw form
`{ "timestamp":1686764741.2561002, ... }`

I now realise that this is actually beyond millisecond resolution too which is unclear to me if `%f` is happy to deal with or if it can only be milliseconds, eg needs to be truncated to `1686764741.256`.

**Comment by guilload** [comment]
Closed via #3639.
