### ISSUE TITLE
Merge pipeline failed when index has too many splits

### ISSUE THREAD

**Issue by dojiong** [quickwit-oss/quickwit#3576]
**Describe the bug**
quickwit-indexer got this error
```
2023-06-26T07:47:49.057Z  WARN spawn_merge_pipeline{index=xxx-index gen=0}: quickwit_metastore::metastore::retrying_metastore::retry: Request failed attempt_count=5
2023-06-26T07:47:49.057Z ERROR quickwit_indexing::actors::merge_pipeline: Error while spawning indexing pipeline, retrying after some time. error=Internal error: `Error, message length too large: found 50114113 bytes, the limit is: 4194304 bytes` Cause: ``. retry_count=0 retry_delay=2s
```

**Expected behavior**
no error

**Configuration:**
quickwit version: v0.6.1
deploy with helm, default settings (with cpu/memory request/limit increased)

----

I found the same error(message length too large) when request `/api/v1/indexes/<index-id>/splits` on searcher, but successed on metastore. I found this error template in tonic's source, so I guess that error occurs on large grpc response of splits.

**Comment by dojiong** [comment]
MergePipeline query all published splits [merge_pipeline.rs](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-indexing/src/actors/merge_pipeline.rs#L201)
```rust
let query = ListSplitsQuery::for_index(self.params.pipeline_id.index_uid.clone())
    .with_split_state(SplitState::Published);
```

It seems that the mergepipline must be failed in the future because of lots of splits.
Do we need a streaming splits api or just filter splits with start_timestamp (via maturation_period)?

**Comment by fulmicoton** [comment]
Ah interesting. Out of curiosity, how many splits do you have?

**Comment by fmassot** [comment]
Yes, our query that fetches all published splits is a bit stupid.

We could fetch only immature splits, we would need to filter on `split.create_timestamp`.

In the merge pipeline, one of the condition that filters out splits that won't undergo merges is like this:

```rust
if OffsetDateTime::now_utc().unix_timestamp()
            >= split.create_timestamp + self.config.maturation_period.as_secs() as i64
{
    return true;
}
```

**Comment by dojiong** [comment]
> Ah interesting. Out of curiosity, how many splits do you have, and how did you end up in that state?

8w+ splits, this cluster is crashed last night (k8s OOMKilled), 6w+ splits is created last night (oom then restart...then oom)

**Comment by fmassot** [comment]
just to be sure, 8w is for 80 000 right?

**Comment by dojiong** [comment]
> just to be sure, 8w is for 80 000 right?

right

**Comment by geek-frio** [comment]
I have also encountered this situation. The current temporary solution is to increase the limit condition of the query to control the number of pulls at one time. The splits that is out of the limits will never be merged at all...
![图片](https://github.com/quickwit-oss/quickwit/assets/40055215/06ffe623-7252-4f6b-bb9c-221977e0c398)

**Comment by fmassot** [comment]
@fulmicoton we first fetch all splits and then filter out the mature ones.

**Comment by fmassot** [comment]
@geek-frio @dojiong we will fix this as soon as possible.

Another question: to have that many splits, you are probably using partitioning? Do you have long retention too?

**Comment by fmassot** [comment]
@dojiong the fix is released in 0.6.2. It does not solve all the cases, you can still get the same error messages if you search on 10k splits for example. We will push a fix to use gRPC stream and avoid sending big messages.

**Comment by fmassot** [comment]
@geek-frio, it should work for you as well. 
And sorry again for the bad experience, don't hesitate to report other bugs, it's really helping us.

**Comment by fmassot** [comment]
> @geek-frio, it should work for you as well.
> And sorry again for the bad experience, don't hesitate to report other bugs, it's really helping us.

One more thing @dojiong @geek-frio : the upgrade will trigger a postgresql migration. It’s better to make a dump of the db before.
Also I should have done a proper upgrade test, I will check today the upgrade process, it should work but I want to double check that.

**Comment by fmassot** [comment]
Ok, PostgreSQL migration worked fine on our cluster. 
It will add the column `maturity_timestamp` to the `splits` table. By default, the `maturity_timestamp` is set to `1970-01-01 00:00:00`. This means that all your splits will be considered `mature` and won't undergo merge operations. This is mostly true for your splits but... it may be not for splits created recently. You may want to do an additional operation, like set the `maturity_timestamp` of recent splits that has a low number of documents to a timestamp in the future, like `now + 48h`.

**Comment by dojiong** [comment]
@fmassot I tested on my cluster, it works as expected!
