### ISSUE TITLE
indexer failed to start when WAL file is corrupted

### ISSUE THREAD

**Issue by dojiong** [quickwit-oss/quickwit#3589]
**Describe the bug**
quickwit-indexer failed to start when WAL file is corrupted

**Steps to reproduce (if applicable)**
quickwit-indexer killed by kubernetes's OOMKiller, then restart failed

**Expected behavior**
no error

**Configuration:**
quickwit v0.6.1

----

I download the WAL file, and write a test below to reproduce the key problem (got the same Corruption error):
```rust
#[tokio::main]
async fn main() -> Result<(), Error> {
    let path = Path::new("./queues");
    let _queue = MultiRecordLog::open(path).await?;
    Ok(())
}
```

I found that a frame of WAL have a invalid CRC checksum, because of half data written. I think the indexer is killed when write to the WAL, that frame is not finished.

Maybe the indexer should discard the invalid frame?

**Comment by fulmicoton** [comment]
The indexer should have discarded that frame indeed. This is most likely a bug.
