### ISSUE TITLE
GCS configuration does not seem up to date.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3693]
Right now a user wanting to configure GCS will likely end up here
https://quickwit.io/docs/guides/storage-setup/gcs-setup/#get-access-and-secret-keys-from-google-console-cloud

when really we would prefer them to use the node config for this and enjoy flavors 
https://quickwit.io/docs/configuration/node-config#storage-configuration

**Comment by guilload** [comment]
Closed via #3520.
