### ISSUE TITLE
Fast field column index based field presence.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3721]
We recently introduced field presence by indexing a special field presence field.

This however comes at a cost. That field presence field is redundant with the docvalue column index if the field is a docvalue.
In that case, we should not populate the special field presence field and instead return a DocSet built using the `DocSet` leveraging the ColumnIndex.

**Comment by fulmicoton** [comment]
unassigning

**Comment by PSeitz** [comment]
@fulmicoton  What does reserved mean?

**Comment by imotov** [comment]
Should we add this as a new query to tantivy first and then hook it up in quickwit or do you want to keep everything in quickwit? In case the initial presence-field based implementation, this query was translated into existing term query. But I don't see a way to return this special DocSet without introducing a new query and I don't see an issue for such query in tantivy. Hence my question.
