### ISSUE TITLE
Add documentation for the ES multimatch query and the phrase match query.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3728]
Documentation page: [es_compatible_api.md](https://github.com/quickwit-oss/quickwit/blob/main/docs/reference/es_compatible_api.md)

Multi match query: [Elastic ref](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html)

Match phrase query: [Elastic ref](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html)

TODO: 
- [ ] Add multi-match query docs in `es_compatible_api.md`
- [ ] Add match phrase query docs in `es_compatible_api.md`
- [ ] Check endpoints on a small dataset

**Comment by JerryKwan** [comment]
@fmassot Please assign it to me, thank you

**Comment by JerryKwan** [comment]
@fmassot 
Please help to review the PR https://github.com/quickwit-oss/quickwit/pull/3873 , thank you
