### ISSUE TITLE
Add a gRPC batch leaf requests endpoint

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3757]
In #3734, we added the multi indexes search.

The root search node now sends leaf requests for each index to leaf nodes. Consequently, the root node will need to merge more leaf responses. This can put a lot of pressure on the root node.

To avoid that, we should introduce a gRPC batch leaf request endpoint so the root node can send multiple leaf requests to a given leaf node. The leaf node will then execute the search on those leaf requests and pre-merge their results before sending the result back to the root.

**Comment by fmassot** [comment]
Using the same pattern as suggested by @guilload [here](https://github.com/quickwit-oss/quickwit/issues/3755#issuecomment-1682598850), sounds a good idea to solve this issue too.

**Comment by guilload** [comment]
Closed via #4962.
