### ISSUE TITLE
Craft SQL queries with query builder instead of manual string wrangling

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3758]
[SeaQuery](https://docs.rs/sea-query/latest/sea_query/)?

**Comment by divinenaman** [comment]
@guilload can I work on this ?

**Comment by kamalesh0406** [comment]
Can you assign this to me, I will take a look!

**Comment by guilload** [comment]
Close via #3959. Thanks again @kamalesh0406!
