### ISSUE TITLE
Normalize error messages

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3759]
> The error message given by the Display representation of an error type should be lowercase without trailing punctuation and typically concise.

> [Examples of error messages](https://rust-lang.github.io/api-guidelines/interoperability.html#examples-of-error-messages)
"unexpected end of file"
"provided string was not `true` or `false`"
"invalid IP address syntax"
"second time provided was later than self"
"invalid UTF-8 sequence of {} bytes from index {}"
"environment variable was not valid unicode: {:?}"

As per [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html), this will reduce noise during code reviews.

**Comment by fmassot** [comment]
We should update our [code style](https://github.com/quickwit-oss/quickwit/blob/main/CODE_STYLE.md) doc with that too.
