### ISSUE TITLE
Store split manifest metadata within bundle file footer

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#376]
With the introduction of bundle files, storing a split manifest as a separate JSON file within a bundle makes little sense. Instead, the bundle footer seems like a natural candidate for hosting a split's metadata (serialized protobuf?).

**Comment by PSeitz** [comment]
`Manifest` seems to be used only when removing the files currently, and that doesn't make sense anymore with a single file bundle.

So there would be no usage left, which would make it odd to carry it in the footer all the time. 

Conceptually we could allow to add files to the bundle footer, so that we could put small files there and read them all in a single read.

**Comment by guilload** [comment]
The main idea behind the manifest was to be able to completely recover a metastore from the raw data on object storage (except for split state). This also allows batch jobs performed with compute engines such as Presto or Spark to process splits (merge, delete) with fewer accesses to the metastore. Those are very desirable capabilities.

**Comment by PSeitz** [comment]
There is a dependency conflict currently. To open a BundleStorage we use the offset information stored in the metastore, to know where the footer is located.

Generally this is also possible without that information, but we would need to extend the storage api to return files sizes. This would require then 2 storage calls, one to get the footer size (last 8bytes) and one to get the the footer itself.

**Comment by fulmicoton** [comment]
I think @guilload would like to make sure we can extra the information from the split file without querying the metastore, provided we have access to the entire file.

I think you  already append a footer length to the bundle file. Can we make sure we have the API to open and read the bundle?

**Comment by fmassot** [comment]
@PSeitz can you check that we have an api for that?

**Comment by PSeitz** [comment]
With https://github.com/quickwit-inc/quickwit/issues/625 and https://github.com/quickwit-inc/quickwit/pull/570, getting stats and extraction of a split is possible without the metastore

**Comment by guilload** [comment]
I'm going to reopen the issue because `inspect split` and `extract split` only partially solve the issue. Metadata such as the number of docs in the split, tags, time ranges are still missing.
