### ISSUE TITLE
Add multi-target syntax + multi indexes search in elasticsearch docs

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3763]
We partly support multi-target syntax for search. Only [glob-like](https://en.wikipedia.org/wiki/Glob_(programming)) wildcard (*) are currently supported.

We should add a section on the supported multi-target and a section on how to search on multiple indexes like [in ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multiple-indices.html#:~:text=To%20search%20multiple%20data%20streams,my%2Dindex%2D000002%20indices.&text=You%20can%20also%20search%20multiple,indices%20using%20an%20index%20pattern.).

For reference: [elasticsearch muti target doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#api-multi-index)

**Comment by JerryKwan** [comment]
@fmassot Please assign this task to me, thank you

**Comment by fmassot** [comment]
We can the multi target doc in the [rest API doc](https://github.com/quickwit-oss/quickwit/blob/main/docs/reference/rest-api.md) too as quickwit supports it

**Comment by JerryKwan** [comment]
@fmassot 
Would you please help to review the PR https://github.com/quickwit-oss/quickwit/pull/3881
