### ISSUE TITLE
Add support for the cardinality aggregation.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3779]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html
I am not sure what the right approach should be here.

Do we want an approximate sketch for cardinality that supports union, or do we just want to carry sets of hashes?

**Comment by fulmicoton** [comment]
Yes. Maybe we can even use the delta encoding to compute the hashes a little bit faster.

**Comment by mcmarkj** [comment]
Hi folks. I'm just throwing my support onto this ticket, as this is the only thing blocking us from moving from Elastic to Quickwit. Essentially all of our dashboards group by a term, be that a userId or errorCodes etc. 

I'm just checking to see if this on a roadmap?

**Comment by guilload** [comment]
It seems like the [PR](https://github.com/quickwit-oss/tantivy/pull/2337) adding support for the cardinality aggregation in tantivy is in good shape, so we should be able to ship that feature in the next release scheduled for July.

@PSeitz, do you think you can help push that tantivy PR across the finish line and perform the integration work in Quickwit (mostly documentation, I assume) in the next few weeks?

**Comment by PSeitz** [comment]
Yes, that should be possible

**Comment by PSeitz** [comment]
https://github.com/quickwit-oss/quickwit/pull/5204
