### ISSUE TITLE
Allow larger payload in the Rest API.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3797]
Currently we limit payload to 10MB by default.

Some clients needs the limit to be increased. Ideally we would prefer to have this configurable.

**Comment by kamalesh0406** [comment]
@fulmicoton are you working on this or can I take up the task?

**Comment by fulmicoton** [comment]
You can take the task! I just assigned it to you. Thanks

**Comment by guilload** [comment]
Closed via #3905.
