### ISSUE TITLE
Implement shard API for PostgreSQL metastore

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3810]
- [x] `open_shards`
- [x] `acquire_shards`
- [x]  `list_shards` 
- [x] `delete_shards`

**Comment by guilload** [comment]
@fmassot, @kamalesh0406 is going to give you a hand for this one. There are four calls to implement: `open_shards`, `acquire_shards`, `list_shards`,  and `delete_shards`. Let's open one PR for each so it's easy to split the work between you. Please leave a comment here and update the to-do when one of you starts working on a new one.

Implementation pointers:
- there already exists a [reference implementation](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/shards.rs) for the file-backed metastore
- the test suite for the Shard API lives in [this file](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-metastore/src/tests/shard.rs): please fill in the blanks and add more tests as you see fit.

**Comment by kamalesh0406** [comment]
I am starting the work for the `open_shards` @fmassot

**Comment by kamalesh0406** [comment]
I added the implementation for list_shards(unit test pending :) ) to my existing PR as well. I will see if I can get delete/acquire_shards done over the next couple of days.

**Comment by guilload** [comment]
Closed via #4403.
