### ISSUE TITLE
Auto-close inactive shards

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3817]
Currently, it's not possible to disable the ingest API source.

As the ingest API source is always enabled, we spawn an indexing pipeline for each index. If you have thousands of indexes and many of them are used only for search, it's a waste of resources.

**Comment by guilload** [comment]
If you have thousands of indexes, you want to avoid manually turning on/off ingest API sources. I'd rather focus on making the sources cost-free when they are unused.

In the ingest V2 world, shards are created lazily, and indexing pipelines are only spun up for ingest sources with at least one shard. In addition, we could automatically close shards when no documents are received for some amount of time.

**Comment by guilload** [comment]
Closed via #4643.
