### ISSUE TITLE
Organize and manage more commonly used utility scripts

### ISSUE THREAD

**Issue by JerryKwan** [quickwit-oss/quickwit#3866]
**Is your feature request related to a problem? Please describe.**
Organize and manage more commonly used utility scripts, including:

1. Installation scripts.
2. Compilation and deployment scripts.
3. Pre-commit inspection scripts (including code formatting checks, code quality analysis, change file overview, etc.).
4. And the others

Having more organized scripts like these will help improve work efficiency.

**Describe the solution you'd like**
1. Create a directory named 'scripts' under the root directory
2. Refactor and move install.sh to scripts/
3. Refactor files under quickwit/scripts and move to scripts/
4. Create a new file named dev_setup.sh which installs necessary development environments
5. Create a new file named check_commit.sh which runs cargo fmt, cargo clippy, run some tests, show changed files 
6. And more utilities

**Describe alternatives you've considered**

**Additional context**
Add any other context or information about the feature request here.

**Comment by fulmicoton** [comment]
THis is too low prioirty and we won't have time to review this.
