### ISSUE TITLE
Bound memory and disk usage of mrecordlog in ingest v2

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3885]
The current logic no longer applies because leaders and followers may host different shards.

**Comment by kamalesh0406** [comment]
@guilload I can take this task up if no one is looking into it yet.

**Comment by guilload** [comment]
@fulmicoton and I have already started designing a solution. If you'd like to ping me on Discord, I can help you find another issue that matches your preferences.

**Comment by guilload** [comment]
Ressources cap for ingesters spec:
1. Leader receives persist request and checks whether payload fits in available resources (ram, disk), if 
not, returns `PersistFailure::RESOURCE_EXHAUSTED ` to router
1. Leader forwards request to follower
1. Follower checks whether payload fits in available resources (ram, disk), if 
not, returns `PersistFailure::` to leader, leader forwards to router
1. Follower write request to local WAL
1. Follower ack write to leader
1. Leader write request to local WAL
1. Leader ack write to router

**Comment by guilload** [comment]
Close via #4100.
