### ISSUE TITLE
Expose REST API endpoint for listing (and filtering) splits

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3907]
- Add REST endpoint in the Open API spec and update the docs.
- Add cursor pagination based on split ID.
- Update the response format to have `{"size": 1000, "results": [...]}`.

**Comment by JerryKwan** [comment]
@guilload @fmassot 
Would you please help to briefly describe the expected outcome of the endpoint? thank you

**Comment by JerryKwan** [comment]
I think we should expose the functions provided by ListSplitsQuery ?
https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-metastore/src/metastore/mod.rs#L362

**Comment by fmassot** [comment]
So in fact we already have some filters in the code @guilload. I totally forgot that.

The annoying part right now is that we cannot do pagination and we should return an object and not a list as reported in #2491.

Some things we have to keep in mind for this issue:
- we could return tens of thousands of splits, even more... Doing pagination with offset can be an issue. I would prefer to use sorting on a unique key and paginate with a filter.
- we want a response format consistent for the different resources: indexes, splits, and checkpoints (maybe others?).
- we can use the main filters available in the `ListSplitsQuery` struct.


Endpoint REST: 
`GET /api/v1/indexes/{my-index}/splits?split_states=Published&start_timestamp=&end_timestamp=`

Response format:

```json
{
   "size": 1000,
   "results": [...]
}
```

**Comment by JerryKwan** [comment]
@fmassot 
Thanks for the information
I have checked the codes in index rest handler, and it seems like there has already some codes about the endpoint
https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-serve/src/index_api/rest_handler.rs#L280-L313

**Comment by fmassot** [comment]
> Do we need to refactor the output data format and add paginate support?
Yes.

**Comment by guilload** [comment]
I missed that endpoint because it's not documented in our Open API spec. Let's add it.

Also, we can easily implement cursor pagination instead of offset pagination with split IDs.

**Comment by fmassot** [comment]
> Also, we can easily implement cursor pagination instead of offset pagination with split IDs.

Oh indeed, I just checked the properties of ulid and this is perfect for pagination.

**Comment by fmassot** [comment]
@JerryKwan I updated the issue description.

**Comment by JerryKwan** [comment]
@fmassot @guilload 
Thanks for helping, I will work on it asap, thank you

**Comment by JerryKwan** [comment]
@fmassot @guilload 
According to the current implementation of postgresql_metastore and file_backed_metastore, I am afraid it's not easy to change pagination from offset/limit to cursor/limit using splitID. Any suggestions?
https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs#L245-L343
https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs#L382-L396

**Comment by fmassot** [comment]
The pagination feature is useful for the REST API, we don't want to modify the metastore trait. 

I would go for a simpler solution:
- expose a filter on split IDs on the REST API
- expose a sort by split IDs desc/asc  on the REST API
- update the JSON response format as described above

A correct pagination can then be handled by the UI.
