### ISSUE TITLE
Make partitions balanced

### ISSUE THREAD

**Issue by dojiong** [quickwit-oss/quickwit#3925]
I found that the indexer direct use doc's partition hash as split's partion-id: [indexer.rs](https://github.com/quickwit-oss/quickwit/blob/e05b7081817062cec151835a1b6de9e70404c8e4/quickwit/quickwit-indexing/src/actors/indexer.rs#L285)

The problem is that many documents will put into `OTHER` partition if the index have a small max-num-partitions: [index.rs](https://github.com/quickwit-oss/quickwit/blob/e05b7081817062cec151835a1b6de9e70404c8e4/quickwit/quickwit-indexing/src/actors/indexer.rs#L143C12-L143C12)

```rust
if num_splits as u32 >= self.max_num_partitions.get() {
        // In order to avoid exceeding max_num_partitions, we map the document to the
        // `OTHER` special partition.
        if other_split_opt.is_none() {
            warn!(
                num_docs_in_workbench = counter.num_docs_in_workbench,
                max_num_partition = self.max_num_partitions.get(),
                "Exceeding max_num_partition"
            );
            .....
        }
        ......
}
```

Should we use `partition % max_num_partitions` as partition id to make partitions balanced?

**Comment by guilload** [comment]
Yes, we recommend not going over a few hundred partitions and using a modulo in the partition expression, for instance `hash_mod(app_id, 200)`, beyond that.

Out of curiosity, how many partitions do you have?

**Comment by dojiong** [comment]
I got it! I should use `hash_mod(key, max_partitions)` instead of `key`.

I set the `max_num_partitions ` to 32 previously, the number of partitions is about 400 before `max_num_partitions` limit.
