### ISSUE TITLE
Rename fast field `precision` parameter to `fast_precision`

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3946]
There is some confusion between the stored precision, which is always in nanoseconds, vs. the fast field precision which is configurable. The current naming scheme does not help.

Let's rename the fast field `precision` parameter to `fast_precision`. We can do so in a backward-compatible manner. The fix should also update the docs and the configuration examples in `config/` and other places (`rg` for `precision: sec|mil|mic|nan`).

See discussion in #3940.

**Comment by Harsh1s** [comment]
> There is some confusion between the stored precision, which is always in nanoseconds, vs. the fast field precision which is configurable. The current naming scheme does not help.
> 
> Let's rename the fast field `precision` parameter to `fast_precision`. We can do so in a backward-compatible manner. The fix should also update the docs and the configuration examples in `config/` and other places (`rg` for `precision: sec|mil|mic|nan`).
> 
> See discussion in #3940.

Hello there, I am kind of new to Rust and trying explore good first issues to get myself acquainted with it. I stumbled upon this issue and quickwit caught my eye. I want to try and solve this issue but am confused about something. Here are the steps that I figured I'll have to do:

1.Update the Mapping File: Modify the index configuration mapping file, replacing the occurrence of precision with fast_precision.
2.Update Code References: Wherever code references the precision field, update it to use fast_precision instead.
3.Documentation: Update documentation to reflect the change from precision to fast_precision.

Now forgive me if I sound stupid but should this be enough or is there something specific I'll have to do for the backward compatibility? That is the part that confuses me, what exactly is needed to be done to ensure backward compatibility?

**Comment by guilload** [comment]
Hello @Harsh1s,

Yes, for preserving backward compatibility, we need to add a [serde alias attribute](https://serde.rs/field-attrs.html#alias) on the renamed `fast_precision` [field](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs#L46), so it also deserializes old index configs successfully. This is unit-testable.
