### ISSUE TITLE
Cache the creation of the http client in the S3 storage 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3958]
Right now the client creation happens at the creation of the storage, so for each query.
We could keep a pool at the factory level.

Establishing the connection takes up to 5ms.

**Comment by guilload** [comment]
Do you know why caching the Hyper connection pool is not sufficient? Does the S3 client close its connection on drop?

**Comment by fulmicoton** [comment]
Yes it is already doing that.
`get_aws_config()` creates the connection pool.
