### ISSUE TITLE
Recycle the s3 client.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3965]
The S3 client hosts a connection pool.
Right now this connection pool is instantiated at the creation of the Storage which itself happens once per leaf_search.

Establishing connection takes several ms. We should build only one s3 client per configuration.

**Comment by fulmicoton** [comment]
![s3classic](https://github.com/quickwit-oss/quickwit/assets/1021506/8d40b129-c87a-4ed7-bf9c-cf8ab86a2a2e)

reopening...
tracing shows 2 to 3ms spent in the when resolving the object storage uri. This happens twice in the same request (search + fetch_docs). On an experimental s3 storage that simply recycles a http client, this takes a few microsecs.

**Comment by fulmicoton** [comment]
Supposedly this is already done. The http connector is initiated once in the aws_config.
We need to double check if we still have the problem, and whether this is really a client recycling problem.

**Comment by trinity-1686a** [comment]
tested with Wireshark. When doing multiple queries in sequence, we don't get a new tcp/tls handshake for each query. Doing 1 query per second over 300s, I get 9 handshakes. If querying another index sharing the same storage config, no new handshake is made. Connection pooling works as intended.
