### ISSUE TITLE
No messages outputted when indexing malformed json data

### ISSUE THREAD

**Issue by JerryKwan** [quickwit-oss/quickwit#3981]
**Describe the bug**
When I tried to sent data to be indexed using the following command
```
curl -v  -X POST http://127.0.0.1:7280/api/v1/datahub/ingest -d @datahub.json
```
The ingest API responses with 
```
{
  "num_docs_for_processing": 1
}
```
And after some seconds I checked the index using 
```
quickwit index describe --index datahub
```
I got Number of published documents: 0
I tried to find out why the documents are not indexed. I checked the logs of quickwit, and does not find out any errors. 
I checked the codes, added some more detailed logs, and found out that: 
1. curl -d removed line breaks when posting, it would be better to use curl --data-binary 
2. quickwit output nothing when there is error when converting InputDoc to JsonObject invoking serde_json::from_slice::<JsonObject>(&doc_bytes)?
Currently it only records the parsing error using DocProcessorCounters

**Expected behavior**
It would be better to output the errors when processing documents, and it would be helpful to diagnose the problem

**Comment by JerryKwan** [comment]
Maybe we can output errors in https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-indexing/src/actors/doc_processor.rs#L324

**Comment by fmassot** [comment]
thanks for the issue @JerryKwan ! This is in fact related to this issue #3743

We will tackle this problem once we landed the new ingest API.
