### ISSUE TITLE
Support compressed HTTP request bodies in REST API

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3990]
Implementation pointers:
- the HTTP server for the REST API is set up [here](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-serve/src/rest.rs).
- ~~add [this Tower layer](https://docs.rs/tower-http/latest/tower_http/decompression/struct.RequestDecompressionLayer.html) should do the trick~~

**Comment by unpervertedkid** [comment]
@guilload can i take this up?

**Comment by etolbakov** [comment]
@unpervertedkid I assume you had a look at the linked https://github.com/quickwit-oss/quickwit/pull/4003 comment section about warp limitation and will tackle that problem differently.

**Comment by guilload** [comment]
Hello @unpervertedkid,

I saw you opened a PR to add support for decompression directly in `warp`. Super cool and thank you! I don't know how long it'll take for the review/merge/release process to complete. In the meantime, we could use your `warp::Filter` in Quickwit directly. The only missing piece is to dynamically decompress the payload depending on the value of the `Content-Encoding` header (or its absence).

**Comment by unpervertedkid** [comment]
Sure @guilload . Although I might take a week or two pick it up so in the mean time if anyone is willing to pick it up feel free to go ahead.
Refer to [this pr](https://github.com/seanmonstar/warp/pull/1080).

**Comment by DCjanus** [comment]
> A malicious user can compose a request using gzip that has a compression ratio > 1000x, meaning a body of 1MB could expand >1GB. When the server processes these requests, it's very likely to saturate the memory capacity and cause an outage.
-- https://medium.com/@abhinav.ittekot/why-http-request-compression-is-almost-never-supported-5de68067b245

Maybe we should be carefully handle this situation.

**Comment by fmassot** [comment]
Friendly ping @unpervertedkid

**Comment by unpervertedkid** [comment]
@fmassot I think you should assign this to someone else.
My bandwidth is currently pretty limited😥.
