### ISSUE TITLE
Implement per shard rate limiting

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3993]
- [x] ingesters should limit the ingestion rate per shard (5MiB/s) and return `PersistFailure::RATE_LIMITED` to routers
- [ ] routers should report rate limited shards to CP

**Comment by guilload** [comment]
Closed via #4105.

**Comment by vinhjaxt** [comment]
Why add this rate limit? As a user, I just want to push to quickwit as much as possible. 😧
