### ISSUE TITLE
Add _index field in elasticsearch hits

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4015]
In the elasticsearch docs, hits contained in a search response have an `_index` field.
This is useful when you can hit several indexes.

From the docs https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html

```
 _index
    (string) Name of the index containing the returned document. 
```

**Comment by fulmicoton** [comment]
Added PR with integration test https://github.com/quickwit-oss/quickwit/pull/4017
