### ISSUE TITLE
Elasticsearch compatible search endpoint should return an empty set when no matching index is found

### ISSUE THREAD

**Issue by esatterwhite** [quickwit-oss/quickwit#4042]
**Is your feature request related to a problem? Please describe.**
Return empty hits arrays if index search patterns do not match any indexes

**Describe the solution you'd like**
* If none of the index patterns match an index. return an empty hits array.
* If some of the patterns match an index, return results for the indexes that are found.

**Describe alternatives you've considered**

**Additional context**
Currently if an index pattern doesn't match any index in quickwit it will fail the entire request. This is difficult to handle when using a CSV of globbed index patterns.  In most cases, we use globs because we are unsure if certain indexes exists or not. In the current state, it will return a 404 where as elasticsearch will return a 200 and an empty hits array

**Comment by esatterwhite** [comment]
#### Example

```json
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "hits": []
  }
}
```

**Comment by fulmicoton** [comment]
Created integration tests here:
https://github.com/quickwit-oss/quickwit/pull/4048
