### ISSUE TITLE
Improve handling of on empty metadata action payload or document payload in bulk request

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4114]
**Case 1**: a line is inserted between the metadata action and the doc

- if the line is empty, quickwit and OpenSearch will do the parsing correctly.
- If the line contains some spaces, both will fail.

OpenSearch returns this error

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Malformed action/metadata line [3], expected one of [create, delete, index, update] but found [_line]"}],"type":"illegal_argument_exception","reason":"Malformed action/metadata line [3], expected one of [create, delete, index, update] but found [_line]"},"status":400}
```

Quickwit returns this unhelpful error

```
{"message":"failed to parse action `expected value at line 1 column 1`"}
```

**Case 2**: a line is inserted before the metadata action.

- if the line is empty, quickwit and OpenSearch will do the parsing correctly.
- If the line contains some spaces, only quickwit will fail with an unhelpful error

**TODO**
Align Quickwit behavior on OpenSearch behavior and improve error message.

**Comment by etolbakov** [comment]
@fmassot if that's as straightforward as it sounds and it's not super urgent I would like to give it a go.

**Comment by fmassot** [comment]
Sure! I'm assigning it to you. Thanks for your help!

**Comment by esatterwhite** [comment]
I'm pretty certain these failures return back the `_id` value that was included in the meta doc. Other wise it becomes difficult to understand which item was invalid.

**Comment by fmassot** [comment]
Here is the payload I used to test Quickwit and OpenSearch behavior:

```json
{"create": {"_index": "hello-world", "_id": "1674834324802805760"}}
  
{"_line": {"message": "hello-world"}}
```
