### ISSUE TITLE
The ES compatible API accepts malformed requests

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4132]
Example of a request that should return a 400 error:

```
{"term": {"actor.id": {"value": "95077794"}}}
```

This is converted into a match all query.

The correct query is:

```
{"query": {"term": {"actor.id": "95077794"}}}
```

**Comment by tuziben** [comment]
```
{
    "query": {
        "term": {
            "actor.id": {
                "value": "95077794"
            }
        }
    }
}
```
BTW, this is also a valid DSL format

**Comment by fulmicoton** [comment]
Yes ! and we accept both.
https://github.com/quickwit-oss/quickwit/blob/main/quickwit/rest-api-tests/scenarii/es_compatibility/0006-term_query.yaml

I think @fmassot's point is that the doc should probably give the full payload (starting from "query")

**Comment by fmassot** [comment]
We could add `deny_unknown_fields` to the [search body struct](https://github.com/quickwit-oss/quickwit/blob/131f64be0d72f353fc1da6582748978f79ebb4b7/quickwit/quickwit-serve/src/elastic_search_api/model/search_body.rs#L56).

@fulmicoton I'm wondering if you did not use it deliberately, can you confirm?

**Comment by fulmicoton** [comment]
It was not deliberate.

**Comment by fulmicoton** [comment]
Thank you @etolbakov !
