### ISSUE TITLE
Complete the Query DSL doc to make sure it starts by query

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4134]
```json
{"query": {...}}
```

**Comment by tuziben** [comment]
How about let me refine this part in docs?

**Comment by fmassot** [comment]
sure!

**Comment by fmassot** [comment]
the doc page is here: https://github.com/quickwit-oss/quickwit/blob/main/docs/reference/es_compatible_api.md

**Comment by fulmicoton** [comment]
That would be awesome!

**Comment by tuziben** [comment]
I made a PR here https://github.com/quickwit-oss/quickwit/pull/4162 . Please take a look @fmassot 

I will continue to improve the documentation using the GitHub dataset.
