### ISSUE TITLE
ticking bomb? EOF record would prevents truncation (!?)

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4135]
This is on the same register as all of the on-disk data truncation problems, and this probably suggests a common solution.

Shortcut Suggestion: 
We could delete queues upon reception of suggest_truncate to EOF.

@guilload This requires however to push #4099 and remove the autocreation of queues upon reception of first log from ingesters

**Comment by guilload** [comment]
Closed via #4238.
