### ISSUE TITLE
 [Dev Experience] Add dev container configuration for GitHub Codespaces

### ISSUE THREAD

**Issue by unpervertedkid** [quickwit-oss/quickwit#4163]
## Motivation

 I would like to propose adding a dev container configuration for GitHub Codespaces. This would make it easier for developers to set up their environment and work on the project without much hassle and effort. Setting up the project for the first time requires CMake, Docker, node, yarn, awslocal protoc and other tools. However, installing and configuring these tools manually can be time-consuming and error-prone, especially for new contributors or low-end machines. 

## Solution

 It would be nice to have a dev container configuration for GitHub Codespaces that would automate the setup of the development environment and provide a consistent and reproducible experience. This would make contributing to the project easier as it would:
 
- Lower the barrier to entry for new contributors due to the ability to quickly spin up a fully set up environment and focus on making a contribution instead of spending hours trying to get the right version of some tool installed. 

## Tasks to make this happen

- [x] Add dev Container configuration
- [ ] Update `README.md` and `CONTRIBUTING.md` to include information on how to get started with a codespace

**Comment by fulmicoton** [comment]
That sounds like a good idea!

**Comment by unpervertedkid** [comment]
Okay! I'll get started on it.
