### ISSUE TITLE
Add a mechanism to cap the number of shard we open (maybe?)

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4231]
So right now we open a new shard for a queue whenever the ingester rate exceeds a given amount.
Do we want to cap this?

Are we confident of the behavior of the system when indexing cannot keep up?

@guilload

**Comment by guilload** [comment]
I asked myself the same question. We have some users that index at 1+ Gib/s, that's ~200 shards; what should the default limit be, 500? 1,000?
