### ISSUE TITLE
Add native support for Google Storage

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4236]
Right now Quickwit supports Google storage via its S3 interoperability layer.
This works great but this has three downsides:
- Users have to generate interoperabilitiy access/secret tokens and somehow pass them to their instances, instead of simply using Application Default Credentials 
- Some environment (restack for instance) do not even make it possible to get S3 interoperabillity Access tokens
- We cannot use http2.

https://crates.io/crates/google-cloud-storage is probably our best bet.

**Comment by guilload** [comment]
What does that mean?

**Comment by fulmicoton** [comment]
@guilload I edited the description.

**Comment by fmassot** [comment]
I think [OpenDAL](https://github.com/apache/incubator-opendal) is interesting, could be a good opportunity to test, it opens up many new storage backend too.

**Comment by Xuanwo** [comment]
Interesting. Let me give it a try. 

Initially, I planned to focus on webhdfs support as outlined in https://github.com/quickwit-oss/quickwit/issues/2655; however, I now believe that native GCS support would be more beneficial.

After our opendal storage has been implemented, extend it to webhdfs should be super easy :love_letter:
