### ISSUE TITLE
Return a 429 for all of the back pressure stuff.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4289]
Right there are some case where we return a 500 when really it should have been a 429.

For instance, the router to count the number of request queue and circuit break when too many clients are waiting.
This results in the proper gRPC status code, but somehow the conversion somewhere along the chain is wrong and we return a 500 instead of a 429

**Comment by PSeitz** [comment]
https://github.com/quickwit-oss/quickwit/pull/4294 should fix the issue, but I don't know how to trigger the router code mentioned in the ticket. A regular ingest does not.

```rust
#[async_trait]
impl IngestRouterService for IngestRouter {
    async fn ingest(
        &mut self,
        ingest_request: IngestRequestV2,
    ) -> IngestV2Result<IngestResponseV2>{..}
```

**Comment by PSeitz** [comment]
I could confirm that 429 is getting returned for queue full and the semaphore in the router.
