### ISSUE TITLE
Wildcard lucene search

### ISSUE THREAD

**Issue by kfirfer** [quickwit-oss/quickwit#4312]
Hello

We are using Quickwit with Grafana as UI, and we couldnt set wildcard searches in lucene, for example:
```
cluster:"prod-*" AND error.exception: * 
```
the `error.exception: * ` is for existence filter , only docs that the field are exists there

If its exists somehow, would like to get some docs how to do it

Would be much appriciate !

**Comment by fmassot** [comment]
If you use the docker edge version or the nightly-built version, you should be able to use:
- `cluster:"prod-"*`
- `error.exception:""*`

This syntax is a bit weird and we may change it before the version 0.7 that should be release first week or second week of January.

**Comment by kfirfer** [comment]
tested on 0.7 and it's works , thanks !
