### ISSUE TITLE
Jaeger REST API missing parameters in API playground

### ISSUE THREAD

**Issue by ddelemeny** [quickwit-oss/quickwit#4329]
**Describe the bug**
In the API playground, some endpoints of the Jaeger API are missing parameters to execute properly.
- `/api/v1/otel-traces-v0_6/jaeger/api/services/{service}/operations`
- `/api/v1/otel-traces-v0_6/jaeger/api/traces/{id}`

![image](https://github.com/quickwit-oss/quickwit/assets/1690574/22806217-1315-4a3a-92d0-4f5f9374e906)

**Expected behavior**
Parameter fields should show up in the tryout forms for those endpoints.

**Configuration:**
Quickwit 0.6.5-dev-nightly (77b0e17 2023-12-27T12:26:00Z)

**Comment by etolbakov** [comment]
Hi @ddelemeny thanks for raising that!
@fmassot I believe this is something that is missing in swagger configuration. I'll try looking at it today.

**Comment by fmassot** [comment]
@etolbakov I'm making changes today on the Jaeger rest code, I will try to fix that.
