### ISSUE TITLE
env var override or overriden?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4355]
Following a discussion on https://github.com/quickwit-oss/quickwit/pull/4344

In presence of a config value AND an environment variable, which one should we prioritize?
I think we tend to do 
- config first
- environment variable second.

Azure, S3, however, seem to do the other way around.

Is that picture correct, and should we align the logic?

**Comment by guilload** [comment]
Interesting. I think we tend to do the opposite:
- environment variable first
- config second

We do [so](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-config/src/config_value.rs#L74) for all the `QW_` en vars.

The AWS SDK works the same way as most of the systems I previously worked with (Hive, Spark, Presto, Airflow).

**Comment by guilload** [comment]
Def environment variable first.
