### ISSUE TITLE
0.7.0 Searcher web UI fails to parse multi-line queries

### ISSUE THREAD

**Issue by to266** [quickwit-oss/quickwit#4408]
**Describe the bug**
Searcher web UI fails to parse multi-line queries

**Steps to reproduce (if applicable)**

1. Deploy to k8s via https://github.com/quickwit-oss/helm-charts/releases/tag/quickwit-0.5.3
2. Start feeding otel logs
3. Attempt to query
```
ERROR 
AND resource_attributes.k8s.deployment.name:something
```
4. Get error
```
Error: { "message": "failed to parse query: `ERROR \nAND resource_attributes.k8s.deployment.name:something`" }
```

**Expected behavior**
With 0.6.4 it used to work seamlessly

**Configuration:**
Please provide:

1. Output of `quickwit --version`
```
Quickwit v0.7.0 (f218294 2024-01-05T02:11:51Z
```
2. The index_config.yaml
Actually the default whatever quickwit creates. Even with 0.7.0 it still creates `otel-logs-v0_6`, despite the release notes

**Comment by trinity-1686a** [comment]
not actually fixed until we pull the new commit form tantivy in quickwit

**Comment by guilload** [comment]
@to266, FYI, we're planning on releasing Quickwit 0.7.1 this week.
