### ISSUE TITLE
Resuming ingest on compressed file source fails

### ISSUE THREAD

**Issue by rdettai** [quickwit-oss/quickwit#4455]
**Describe the bug**
I get the following error when resuming the ingest on a gzipped file 

```
{
    "timestamp": "2024-01-24T14:16:45.576Z",
    "level": "ERROR",
    "fields": {
        "message": "error while spawning indexing pipeline, retrying after some time",
        "error": "failed to create source `_ingest-cli-source` of type `file`. Cause: offset 7194479974 can't be greater than the file size 470061890\n\nCaused by:\n    offset 7194479974 can't be greater than the file size 470061890",
        "retry_count": 0,
        "retry_delay": "2s"
    },
    "target": "quickwit_indexing::actors::indexing_pipeline"
}
```

The error occurs here: https://github.com/quickwit-oss/quickwit/blob/51cab3a13e6c67d289435ee6023667d894529720/quickwit/quickwit-indexing/src/source/file_source.rs#L155-L162

**Steps to reproduce (if applicable)**
Didn't try but I would assume this should occur when trying to ingest the same gzipped file twice.

**Comment by fmassot** [comment]
Yes, the check makes no sense for a compressed file. I committed this check; my fault :/
