### ISSUE TITLE
README update about support for ES query DSL

### ISSUE THREAD

**Issue by clarus** [quickwit-oss/quickwit#4511]
In the README https://github.com/quickwit-oss/quickwit?tab=readme-ov-file#how-can-i-switch-from-elasticsearch-to-quickwit it is written:

> However, we only support [ES aggregation DSL](https://quickwit.io/docs/reference/aggregation), the query DSL support is planned for Q2 2023.

What is the update of this part for 2024?

Thanks!

**Comment by fulmicoton** [comment]
Oh thanks for catching this! This is obsolete indeed. Quickwit supports a lot of elastic/opensearch API.

**Comment by clarus** [comment]
OK thanks!
