### ISSUE TITLE
Log quickwit version on startup

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4526]
the thing on display on --version will do the job

**Comment by etolbakov** [comment]
Hell @fulmicoton @PSeitz 
I was just curious if this is something you were expecting:
<img width="1263" alt="Screenshot 2024-02-06 at 20 40 39" src="https://github.com/quickwit-oss/quickwit/assets/3762201/e986cba9-152b-4f97-925c-b70d75210e67">
Provided that this ticket has been already assigned please let me know if you'd like me to push the change.

Regards, Eugene

**Comment by etolbakov** [comment]
I've managed to place it at the very beginning: 
<img width="1249" alt="Screenshot 2024-02-06 at 21 17 59" src="https://github.com/quickwit-oss/quickwit/assets/3762201/1bc94007-7adb-4e11-8f49-19b67f7d87aa">
