### ISSUE TITLE
document all query dsl features

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit#4533]
our Query language documentation misses a few things:
- phrase prefix queries ( #4315 )
- wildcard in suffix position ( #4315 too?)
- exist queries
- range query with `>=`, `<=` `>` and `<`
- other things I forgot?

**Comment by fmassot** [comment]
We should probably review the whole page.

**Comment by trinity-1686a** [comment]
fixed by #4726
