### ISSUE TITLE
Parse error on `john AND -doe` 

### ISSUE THREAD

**Issue by ddelemeny** [quickwit-oss/quickwit#4541]
**Describe the bug**

From quickwit-oss/quickwit-datasource#56

Quickwit fails to parse `john AND -doe` :

![image](https://github.com/quickwit-oss/quickwit/assets/1690574/66e7b33d-f922-4cfa-adeb-60d1c38b25b2)

However, the equivalent following queries parse correctly
`john AND (-doe)`
`john -doe`
`john AND NOT doe`

**Configuration:**
Quickwit 0.7.1 (0.7.1 2024-02-07T11:47:08Z)

**Comment by ddelemeny** [comment]
Okay,thanks @trinity-1686a, that explains it.

Should we outline the limitation in [the docs](https://github.com/quickwit-oss/quickwit/blob/main/docs/reference/query-language.md#boolean-operators) ?

**Comment by fulmicoton** [comment]
@trinity-1686a could we allow this in the non-lenient parser? It seems unambiguous.

**Comment by trinity-1686a** [comment]
@ddelemeny if it stays that way, probably

@fulmicoton  previously we didn't have any logic to manage that kind of situation, now that we have (for the purpose of the lenient parser), having it for the strict parse sounds like a good idea

**Comment by fmassot** [comment]
+1 to handle that in the strict parser.
