### ISSUE TITLE
Field concatenation

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4548]
It would be nice to have a "concatenate" field type.

The idea is to have it as a default field on search, to enable the use case of users searching for a given id.
If different tokenizer are required depending on the field, the user will have to create on tokenizer per concatenate field.

That field will be non-fast, non-stored but indexed.
For numeric types or dates, we should coerce them to string. Maybe we can skip float (!?) as they will likely not be retrievable anyway.

```
type: concatenate
name: "my_default_field"
concatenated_fields:
      - text
      - body
      - params_* # we allow params
      - _dynamic # json field will be browsed
tokenizer: default # tokenizing by default should make sense too
record: basic # by default basic should make sense
```

Open questions:
Should we do RFC-3339 with a space instead of the T between date an hour.
SHould we index positions for RFC-3339?
Any creative ideas there?

**Comment by trinity-1686a** [comment]
>  Should we do RFC-3339 with a space instead of the T between date an hour.
Should we index positions for RFC-3339?

being able to search `2023-02-09` to match `2024-02-09T10:30:00` seems convenient. I think we could emit multiple tokens (at least `2024-02-09` and `2024-02-09T10:30:00`, but maybe more?).
We will have to do something smart on the query side. With the default tokenizer, a query `2024-09` would be split to `["2024","09"]`, if we tokenize dates. This means `2024-02-09` would match, which is surprising. But if we don't, it means `2024-09-01` would *not* match `2024-09` which isn't great (actually `2024-09-01` wouldn't even match itself).
