### ISSUE TITLE
RAM usage is too high on indexers when ingesting at maximum throughput.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4578]
Observed on fly. When starting ingestion, we receive a buffer worth of data all at once, and observe a temporary peak in RAM usage.

Generally speaking this probably happens whenever someone attempts to ingest at max throughput (until getting 429s).
The most probable cause is the queue capacities we have in the different indexing pipelines.
(1000s of indexing pipeline amounts to GBs)

**Comment by trinity-1686a** [comment]
might be related to #4629

**Comment by guilload** [comment]
Fixed via quickwit-oss/tantivy#2402
