### ISSUE TITLE
Simplify cache metrics

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4583]
We have separate metrics for fastfields, shortlived, splitfooter caches.

We could just use labels `fastfields`, `shortlived`, `splitfooter` instead.

So in end we have the following metrics:
- `quickwit_cache_in_cache_count`
- `quickwit_cache_in_cache_num_bytes`
- `quickwit_cache_hit_total`
- `quickwit_cache_ hits_bytes`
- `quickwit_cache_miss_total`

**Comment by Surya361** [comment]
Is this only for `fastfields`, `shortlived` and `splitfooter` metrics or should we extend it to all cache metrics such as `fdcache`, `partial_request` etc.
