### ISSUE TITLE
Using OTEL with Helm seems outdated

### ISSUE THREAD

**Issue by nicrosengren** [quickwit-oss/quickwit#4599]
Hi, I'm trying to deploy quickwit with OTEL using their helm charts following the guide ([Using OTEL with Helm](https://quickwit.io/docs/log-management/send-logs/using-otel-collector-with-helm).

I had to change much from the quickwit values for the helm chart before getting it to accept the S3 connection.
As an example, the s3 confiuration seems to have moved into the object `storage` within `config`.

Since I'm not very well versed in Helm charts I might have missed something but the guide seems outdated.

It started fine now but no logs are stored and the indexer keeps spewing out error messages like:
```
ERROR quickwit_indexing::actors::indexing_service: Failed to spawn pipeline: index otel-traces-v0_7:01HPTB5VN3RK2FRCEJNKB9WH4V no longer exists.
```

Not sure how to proceed since the word otlp no longer exists in the helm values for quickwit.

**Comment by fmassot** [comment]
thank you for the feedback; I will update this tutorial.

**Comment by fmassot** [comment]
@nicrosengren, I updated the tutorial. Sorry for the bad experience.

**Comment by nicrosengren** [comment]
Damn, a reply and fix that quick. No problem at all, thank you so much!

It seems my digging in the chart repo lead me to the same config as the updated one.

Again, I'm not fully versed in Helm but does the chart really accept the
`enable_otlp_endpoint` on the indexer from this block:
```
  # Indexer settings
  indexer:
    # By activating the OTEL service, Quickwit will be able
    # to receive gRPC requests from OTEL collectors.
    enable_otlp_endpoint: true
```

Searching true the values for the chart it does not exist.

**Comment by fmassot** [comment]
@nicrosengren you will see in the configmap generated by the helm chart though as we do in the chart this:

```
{{- with .Values.config.indexer }}
    indexer:
      {{- toYaml . | nindent 6 }}
{{- end }}
```

**Comment by fmassot** [comment]
@nicrosengren for the helm chart name, yes, it's  called `opentelemetry-collector`. In the tutorial I think we use the right name, here is the snippet from the tutorial:

`helm install otel-collector open-telemetry/opentelemetry-collector`
