### ISSUE TITLE
Garbage collect ingested files in the metastore in Lambda indexer

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4613]
Each time we invoke the lambda indexer to ingest a file, it will index it and store a new checkpoint with the file's name.

The metastore file will become bigger and bigger. We can remove the checkpoints after indexing and leave the responsibility to the caller to not index the same file twice. It could also be a parameter that we can pass to the indexer.

**Comment by rdettai** [comment]
a few points:
- I think deleting the checkpoint right after the indexing is a bit dangerous, as it is not uncommon that triggering events get duplicated and without the checkpoint safe guard, the file would be ingested twice. I propose using a background cleanup process that removes the checkpoint after X hours.
- we identified this issue when doing file based ingestion in Lambda, but in the end it might happen with file based ingestion scripts executed on regular indexers as well. I wonder whether this cleanup code should be part of the Lambda package or rather some general purpose package like the janitor.

**Comment by rdettai** [comment]
> I propose using a background cleanup process that removes the partition checkpoints after X hours

After taking a deeper look, the timestamp info is not available for checkpoints, so doing a time based pruning is not really practical. Unfortunately, pruning by keeping only the last N partitions is not much better, because the partition entries are sorted in lexicographical order and not by insertion. I suggest changing the partition checkpoint order to insertion order (backing in memory data structure to be decided).

**Comment by rdettai** [comment]
We agreed with @fmassot to use the source id to store the timestamp when indexing a file in Lambda and perform time based pruning at the source level instead of the partition level. This has the benefit of containing the workaround to the Lambda package for now.

**Comment by rdettai** [comment]
After running the solution proposed above, we realized the merges were not performed anymore. Indeed, merges are only performed within a source: https://github.com/quickwit-oss/quickwit/blob/f6065a4f4c96d17189c9fac7935a04da8076a309/quickwit/quickwit-indexing/src/actors/merge_planner.rs#L299-L304.

We agreed with @fmassot to go for a more drastic solution where the entire checkpoint list is purged after a limit is reached (default QW_LAMBDA_MAX_CHECKPOINTS=100). In very rare cases, if a duplicate file notification arrives right after the purge, the associated data might be ingested twice, but this should be extremely rare.
