### ISSUE TITLE
Remove `max_num_pipelines_per_indexer`

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4624]
It is not used anymore. (well double check that beforehands)

**Comment by dojiong** [comment]
What changes will happen to kafka-source’s scheduling?

**Comment by fmassot** [comment]
@dojiong which quickwit version are you using?

**Comment by dojiong** [comment]
I upgrade to 0.7.1 from 0.6 recently.

I the `max_num_pipelines_per_indexer ` is not used anynow, how can I control the num of pipelines for kafka-source?

**Comment by fulmicoton** [comment]
`desired_num_pipelines` in your source config let's you decide the number of pipelines. (Make it a divisor of your number of partitions)

The control plane will then decide how to place the pipeline on your indexers.
If you insist on having your pipeline spread evenly, you can set 
`cpu_capacity` in the indexer config (in your quickwit.yaml) to something arbitrary low, like 

```
indexer:
  cpu_capacity: 1m
```

**Comment by dojiong** [comment]
I got a balance problem about kafka-source:
I have two kafka-source index in my cluster, one source have about 5 times throughput than another, the quickwit's scheduler treat then consuming the same cpu. So some indexer nodes consumes much more cpu than others.

**Comment by fulmicoton** [comment]
Have you tried setting `cpu_capacity: 1m` as I suggested above?

Concretely, why is this a problem? You have too much CPU for your data. In that case Quickwit tries to do everything on the same node to improve split pruning.

**Comment by dojiong** [comment]
I don't set the cpu-capacity, that won't fix the balance problem, the key problem is that quickwit treat all the source cost the same cpu(now is `PIPELINE_FULL_CAPACITY`).

Will the load_per_pipeline will fix in 0.8?

`quickwit-control-plain::indexing_scheduler::get_sources_to_schedule`
```rust
                    source_type: SourceToScheduleType::NonSharded {
                        num_pipelines: source_config.desired_num_pipelines.get() as u32,
                        // FIXME
                        load_per_pipeline: NonZeroU32::new(PIPELINE_FULL_CAPACITY.cpu_millis())
                            .unwrap(),
                    },
```

-------

I have 6 indexer node and 2 kafka-source index(each have 6 desired_num_pipelines).
each indexer node have 6-core cpu limited, with current scheduling algorithem, the node state is:

* node-0 { source-0: 2 pipeline}
* node-1 { source-0: 2 pipeline}
* node-2 { source-0: 2 pipeline}
* node-3 { source-1: 2 pipeline}
* node-4 { source-1: 2 pipeline}
* node-5 { source-1: 2 pipeline}

Now I changed the algorithem to make it more evenly distributed in the cluster, the node state is:

* node-0 { source-0: 1 pipeline, source-1: 1 pipeline}
* node-1 { source-0: 1 pipeline, source-1: 1 pipeline}
* node-2 { source-0: 1 pipeline, source-1: 1 pipeline}
* node-3 { source-0: 1 pipeline, source-1: 1 pipeline}
* node-4 { source-0: 1 pipeline, source-1: 1 pipeline}
* node-5 { source-0: 1 pipeline, source-1: 1 pipeline}

------------
waht I changed:
1. set all the source shards to 1 before Phase 1
```rust
fn reset_source_shards(solution: &mut SchedulingSolution) {
    for assign in &mut solution.indexer_assignments {
        for count in assign.num_shards_per_source.values_mut() {
            *count = 1;
        }
    }
}
```

2. only add one shard per step in `place_unassigned_shards_single_source`
```rust
fn place_unassigned_shards_single_source(
    source: &Source,
    indexer_available_capacities: &mut BinaryHeap<(CpuCapacity, IndexerOrd)>,
    solution: &mut SchedulingSolution,
) -> Result<(), NotEnoughCapacity> {
    let mut num_shards = source.num_shards;
    while num_shards > 0 {
        let mut node_with_most_capacity = indexer_available_capacities.peek_mut().unwrap();
        let node_id = node_with_most_capacity.1;
        let available_capacity = &mut node_with_most_capacity.0;
        if available_capacity.cpu_millis() < source.load_per_shard.get() {
            return Err(NotEnoughCapacity);
        }
        // TODO take in account colocation.
        // Update the solution, the shard load, and the number of shards to place.
        solution.indexer_assignments[node_id].add_shards(source.source_ord, 1);
        *available_capacity =
            *available_capacity - CpuCapacity::from_cpu_millis(source.load_per_shard.get());
        num_shards -= 1;
    }
    Ok(())
}
```

**Comment by dojiong** [comment]
The patch I post above is a temporary patch for my scense, I think there maybe a way to set or calc the load of a source to make nodes more balanced

**Comment by fulmicoton** [comment]
I see. It won't be fixed for 0.8. We do expose the load through chitchat. We just need to plug it in the algorithm. It has not been done yet.

**Comment by dojiong** [comment]
the load expose to chitchat is the node's load or source's load?

If that is the node's load, how to fingure out which source-shards to reduce when load is high?

If that is the source's load, what is the algorithem to measure the load of source?

**Comment by fulmicoton** [comment]
We expose a load per shard in chitchat.

**Comment by dojiong** [comment]
got it
