### ISSUE TITLE
when listing splits from multiple index in postgres metastore, use IN instead of many OR

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/quickwit#4666]
when querying many indexes at once, the list split query on metastore create an sql request that looks like the following:
```sql
SELECT * FROM "splits" WHERE 
("index_uid" = $1 OR "index_uid" = $2 OR "index_uid" = $3 OR "index_uid" = $4 OR "index_uid" = $5 OR ...) 
AND ...
```
a request based on `IN` is [reportedly faster](https://ottertune.com/blog/query-best-practices-when-should-you-use-the-in-instead-of-the-or-operator)
```sql
SELECT * FROM "splits" WHERE 
"index_uid" IN ($1, $2, $3, $4, $5,...)
AND ...
```

**Comment by ChillFish8** [comment]
Maybe the generated SQL should use Pg's `index_uid = any($1)` array lookup rather than generating a new param for each id.
