### ISSUE TITLE
Default doc mapping mode

### ISSUE THREAD

**Issue by v-spassky** [quickwit-oss/quickwit#4679]
[Here](https://quickwit.io/docs/guides/schemaless#a-strict-mapping) the docs say that the `mode` attribute by default takes the `lenient` value:

![image](https://github.com/quickwit-oss/quickwit/assets/68805512/b56264b6-9919-4eca-8913-5a341a041966)

However, [here](https://quickwit.io/docs/main-branch/configuration/index-config#doc-mapping) it says that `mode` is `dynamic` by default:

![image](https://github.com/quickwit-oss/quickwit/assets/68805512/8ee86ae0-e244-41b8-91b7-d3308ee07b8f)

Is it a mismatch or am I missing something?

**Comment by fulmicoton** [comment]
Thanks for reporting. A PR fix is on the way.

The default mode is the dynamic mode.
