### ISSUE TITLE
Retry upload on error.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4786]
Some object storage can fail from to time. In that case we should retry instead of restarting the pipeline and losing all of the work done.

**Comment by fulmicoton** [comment]
This is low priority.

**Comment by trinity-1686a** [comment]
we already have retries on the storage for writes, up to 5 times. Some error were not retried, but now are since https://github.com/quickwit-oss/quickwit/pull/5384, so I think this ticket can be closed

**Comment by fulmicoton** [comment]
@trinity-1686a Do we retry on S3 internal errors?

**Comment by trinity-1686a** [comment]
we retry based on what the sdk defines as transient and throttling errors, list here: https://docs.rs/aws-runtime/1.4.3/src/aws_runtime/retries/classifiers.rs.html#18-36
It doesn't include InternalError, so we don't retry on that
