### ISSUE TITLE
support for Boolean query `minimum_should_match` in Elasticsearch API

### ISSUE THREAD

**Issue by tylerkovacs** [quickwit-oss/quickwit#4829]
Elasticsearch's Boolean queries support a `minimum_should_match` parameter:

Documentation can be found here:
https://www.elastic.co/guide/en/elasticsearch/reference/8.8/query-dsl-bool-query.html#bool-min-should-match

```
You can use the minimum_should_match parameter to specify the number or percentage of
should clauses returned documents must match.

If the bool query includes at least one should clause and no must or filter clauses, the default
value is 1. Otherwise, the default value is 0.
```

**Is your feature request related to a problem? Please describe.**
I'm trying to convert some Elasticsearch queries to a quickwit backend and this missing feature is a blocker. Queries that include a `minimum_should_match` value return the following error.

```
unknown field `minimum_should_match`, expected one of `must`, `must_not`, `should`, `filter`, `boost` at line 1 column 425
```

**Describe the solution you'd like**
Implement support for `minimum_should_match` in the Elasticsearch compatible API.

**Describe alternatives you've considered**
There are no known alternatives. If `minimum_should_match` is removed from the request, the query succeeds but returns the wrong results.

**Comment by fulmicoton** [comment]
Created an equivalent issue in tantivy ahttps://github.com/quickwit-oss/tantivy/issues/2398

**Comment by tylerkovacs** [comment]
@fulmicoton I see that this issue was closed. What is ever implemented in a released version of quickwit? My understanding is that it was never shipped.

**Comment by fulmicoton** [comment]
It is not released in an official version, but it is merged in main and available in the edge docker image. The release of 0.9 is getting delayed because we have gotten report about a problems a user encounterred with the edge image. 

We have not been able to reproduce yet, even on their environment.
