### ISSUE TITLE
tool local-ingest misclassifies FDs as directories

### ISSUE THREAD

**Issue by nh2** [quickwit-oss/quickwit#4834]
quickwith 0.8.0.

```sh
quickwit tool local-ingest --index benaco_server_logs --input-path <(echo '{"message": "abc1234"}')
```

errors with:

```
 ✖ _ingest-cli-source
storage error(kind=NotFound, source=file `11` is actually a directory)
```

But this error is wrong. It's not "actually a directory". Process substitution creates a _file_ descriptor pointing to a pipe, e.g.

```
# ls -l <(echo '{"message": "abc1234"}')
lr-x------ 1 root root 64 Apr  3 21:54 /proc/self/fd/11 -> 'pipe:[304371985]'
```

so it's certainly not a directory.

Most likely the error should be that that pipe is not seekable, because ingestion likely uses seeking because it stores an offset in the metadata, for resumption.

The syscall made, as shown by `strace -fy`, is:

```
statx(AT_FDCWD</root/tmp/quickwit-test-position>, "/proc/self/fd/11", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFIFO|0600, stx_size=0, ...}) = 0
```

I suspect that some wrong code does something like

```
if is_regular_file:
   ...
else:
  error("is actually a directory")
```

so the second branch triggers on `stx_mode=S_IFIFO`. If that is the case, the error should say instead that its "not a regular file".

**Comment by guilload** [comment]
Hello @nh2,

Would you be interested in contributing the fixes you suggested to your recently opened issues? Unfortunately, I don't think we have the bandwidth to fix them right now :/

**Comment by nh2** [comment]
@guilload Looks like I guessed right, PR: #4835
