### ISSUE TITLE
`test_ingester_persist_replicate_*` are flaky

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#4837]
They almost never pass on `main` when I run them locally, but they do when I checkout the commit right before #4804.

**Comment by trinity-1686a** [comment]
is there anything particular about your setup? The only way I managed to get `test_ingester_persist_replicate_grpc` to be flaky on my device is to have a `stress -c 24` running in the background, but I get a few other tests already failing with lower stress, and `test_ingester_persist_replicate_grpc` is also failing when trying 43842ace with that same stress :confused:

**Comment by guilload** [comment]
Yeah, I'm on a Macbook Air M2. It must be OS-related. That would also explain why CI workflows are also not impacted.

The failure rate is stupid on my machine:
![Screenshot 2024-04-08 at 3 32 39 PM](https://github.com/quickwit-oss/quickwit/assets/3011588/e5a69513-653a-4648-9452-c81ee629d7e9)

![Screenshot 2024-04-08 at 3 34 53 PM](https://github.com/quickwit-oss/quickwit/assets/3011588/fdc1a2ef-2a17-4a52-8f27-6b36b3c2e002)

**Comment by trinity-1686a** [comment]
We now always flush+fsync on some key operations (create_queue, delete_queue, record_empty_queue_position), and I recall reading fsync is stupid slow Apple's ssd. I suspect that might be the cause of this issue.
I've made a [`disable-all-fsync`](https://github.com/quickwit-oss/mrecordlog/tree/disable-all-fsync) branch on mrecordlog, can you try running test using it?
Also, can you try running test in release mode to rule out pathologically slow non-optimized builds on specific targets?

**Comment by trinity-1686a** [comment]
I tried reproducing locally using the dmsetup delay target (simulate a block device with added latency).
```sh
dd if=/dev/zero of=delay.ext4 bs=1M count=2048 oflag=direct conv=fsync
losetup loop0 /tmp/delay.ext4
# add 20ms on flush to disk operations, and 0ms on read/write
echo "0 `blockdev --getsz /dev/loop0` delay /dev/loop0 0 0 /dev/loop0 0 0 /dev/loop0 0 20" | dmsetup create delayed
mkfs.ext4 /mnt/mapper/delayed
mount /dev/mapper/delayed /mnt/test
mkdir /mnt/test/tmp
chmod 777 /mnt/test/tmp

#  run tests here, modified to use /mnt/test/tmp instead of /tmp

# update latency to be zero
dmsetup suspend delayed
echo "0 `blockdev --getsz /dev/loop0` delay /dev/loop0 0 0 /dev/loop0 0 0 /dev/loop0 0 0" | dmsetup reload delayed
dmsetup resume delayed

# run tests again
```
When running with added latency on flush on newer commits, I do get consistent failures. When running with no added latency and/or old commits without fsync, tests seems to pass consistently.
There are probably too tight deadlines in these tests (possibly in the code called by these tests) which makes them very reliant on mrecordlog returning very quickly

**Comment by guilload** [comment]
I tested your branch, and it fixed the flaky tests. This experience is a good reminder that `fsync` is slow on macOS. I'll take that into account next time I write unit tests. Thanks for your help!
