### ISSUE TITLE
Hello, may I ask if there will be any charges in the future

### ISSUE THREAD

**Issue by zhangxuebao** [quickwit-oss/quickwit#4895]
Hello
Thank you for your open-source quickwit, it works very well.
But I'm also worried, can you ask if this project will continue to be open source?
Or will you charge for it in the future?
Finally, thank you again.

**Comment by fulmicoton** [comment]
We will likely adopt an opencore model in the future: some of the features will be available under a different license, while the core will remain under an AGPL License.

If your business relies heavily on Quickwit, consider becoming our customer to support the project, have your say on our roadmap, and get our support.

**Comment by zhangxuebao** [comment]
Thank
