### ISSUE TITLE
[Docker] Clarify tags latest (0.8.0) not being "latest" v0.8.1?

### ISSUE THREAD

**Issue by thePanz** [quickwit-oss/quickwit#4903]
**Describe the bug**
Pulling the docker image `quickwit/quickwit` gives v0.8.0 which is not the latest tag v0.8.1

Example:
```
docker run --rm quickwit/quickwit:latest --version
Quickwit 0.8.0 (x86_64-unknown-linux-gnu 2024-04-23T08:28:44Z 6fd8dc8)
```

While:
```
docker run --rm quickwit/quickwit:0.8.1 --version
Quickwit 0.8.1 (x86_64-unknown-linux-gnu 2024-03-29T14:09:41Z e6c5396)
```

The build date for v0.8.1 is before v0.8.0 tho :thinking: 

**Expected behavior**
Having a clear and semantic versioning of the docker images would help docker deployments :)

**Comment by guilload** [comment]
I've just fixed the CI workflow and republished the `latest` tag to point to the `0.8.1` release.
