### ISSUE TITLE
key may not contain the 0 byte

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#4915]
```
Apr 25 12:19:34 quickwit-indexer-17 quickwit-indexer thread 'blocking-5' panicked at /usr/local/cargo/git/checkouts/tantivy-f70b7ea03dadae9a/ff40764/columnar/src/columnar/writer/mod.rs:71:5:
Apr 25 12:19:34 quickwit-indexer-17 quickwit-indexer key may not contain the 0 byte
```

**Comment by trinity-1686a** [comment]
this looks related to https://github.com/quickwit-oss/tantivy/pull/2345 / https://github.com/quickwit-oss/tantivy/issues/2340

**Comment by PSeitz** [comment]
https://github.com/quickwit-oss/tantivy/pull/2379 Fixes the issue.

non-text fields had a different path for adding the column to the hashmap in the columnar storage. This path contained a 0-byte check. Zero bytes are converted during serialization in columnar, and this check can be removed.
