### ISSUE TITLE
Add documentation page to help user to size a cluster

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4971]
Several users can struggle to set the right resources for indexers and other components and choose the right number of indexers/searchers for a given ingestion throughput.

We should add a page with some guidelines. We could start very simply, as having something is always better than nothing.

Some idea:
- One indexer max throughput is around 20MB/s et 40MB/s for 4vCPU and 10GB of memory.
- For an indexer with a Kafka data source, use 100GB of ephemeral storage
- For an indexer receiving ingest requests on the ingest API, targeting EBS of 100GB should be enough.
- and more

**Comment by fmassot** [comment]
@rdettai can we clsoe this?

**Comment by rdettai** [comment]
I think so https://quickwit.io/docs/deployment/cluster-sizing should cover most items
