### ISSUE TITLE
Add metrics to track split affinity ratio

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4996]
It would be interesting to know how often we end up picking the searcher with the best affinity.

**Comment by trinity-1686a** [comment]
i think this metric will be non-trivial to interpret. If it's at 100% or 0%, we are definitely doing perfectly, the worst case seemingly being 50%. But if every other split uses the 2nd best affinity, and does so consistency, we'll see 50% on that metric, yet 100% hit in practice.
