### ISSUE TITLE
Add support for `time_series_dimension` flag in `_elastic/{index}/_field_caps` API method

### ISSUE THREAD

**Issue by kuzaxak** [quickwit-oss/quickwit#5003]
Opensearch Dashboards calling `_field_caps` to build an index pattern. To use quickwit natively as an external data source for it dashboards need to determine a timestamp field to render histogram, such fields listed on [index pattern settings page][2]. For that it relies on a `time_series_dimension` flag in `<field>.<type>.time_series_dimension`.

Link to the [doc][1].

**Describe the solution you'd like**

Filed chosen as `timestamp_field` in index should be marked as `time_series_dimension` in `_field_caps` output.

**Describe alternatives you've considered**

I've made a little proxy to query `/api/v1/indexes?index_id_patterns=` and patch response of `_field_caps` method.

**Additional context**

I'm working on integrating quickwit as an Opensearch Dashboards backend to replace existing setup which is using regular Opensearch.

[1]: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html#search-field-caps-api-response-body
[2]: https://opensearch.org/docs/latest/dashboards/management/index-patterns/

**Comment by fulmicoton** [comment]
@kuzaxak have you started experimenting with adding opendashboard support by any chance? I'd love to exchange if you have more info on other missing pieces.

**Comment by kuzaxak** [comment]
> @kuzaxak have you started experimenting with adding opendashboard support by any chance? I'd love to exchange if you have more info on other missing pieces.

Yes, I was able to migrate our Open search dashboard completely to quickwit backend. But I'm using a proxy to monkey patch some responses of quickwit.

I can share a proxy code, it is a simple python flask app.

**Comment by kuzaxak** [comment]
@fulmicoton [here](https://gist.github.com/kuzaxak/ce6178c185073f69f9836c30e0ea08d9) you can find a proxy server code. 

I'm using quickwit as an external source not to deal with auth, dashboards storage, etc.

1. Enable this feature for OSD:
```
data_source.enabled: true
```

2. Add proxy as an additional datasource:
<img width="1217" alt="image" src="https://github.com/quickwit-oss/quickwit/assets/5330267/14be19be-2e2f-43fc-ade4-96bf991e36b8">

3. Add Index pattern using external source:
<img width="1217" alt="image" src="https://github.com/quickwit-oss/quickwit/assets/5330267/e2775c73-a9e1-4a05-9efe-53fb5984d9e5">

This way I'm using security features and SAML from OSD and logs storage and querying from Quickwit.

**Comment by fulmicoton** [comment]
@kuzaxak That's absolutely awesome, thank you for sharing the script, the approach and the screenshot, The hack is really cool!
