### ISSUE TITLE
[Doc] IAM permissions in the aws-setup doc page may be incorrect

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#5005]
Feedback from a user.

In the example provided [here](https://quickwit.io/docs/guides/aws-setup#iam-permissions), we include `S3:ListObjects` , however this does not seem to be a valid action.

```
Kindly note ListObjects or ListObjectsV2 is the name of the API call that lists the objects in a bucket. You will need to use s3:ListBucket in the action element to allow a user to list the objects in a bucket.
```

Copied from https://repost.aws/knowledge-center/s3-access-denied-listobjects-sync

**Comment by guilload** [comment]
Fixed via [`8ee25c9`](https://github.com/quickwit-oss/quickwit/commit/8ee25c972013e1f5f3acbb2c2cef23036cd5a6e9).
