### ISSUE TITLE
Add `GET api/v1/indexes` to Lambda searcher

### ISSUE THREAD

**Issue by rdettai** [quickwit-oss/quickwit#5039]
**Is your feature request related to a problem? Please describe.**
To use the Lambda distribution as Grafana datasource, we need the `GET api/v1/indexes` endpoint

**Describe the solution you'd like**
Expose it like the search and elasticsearch endpoints

**Describe alternatives you've considered**
NA

**Additional context**
It is worth noting that this change is required for the Grafana datasource to work, but there might be other (currently unidentified) requirements.

**Comment by tyrwzl** [comment]
@rdettai 
Hi,
I have created Pull Request for this issue. Could you please take a look at my Pull Request?
Thank you!
