### ISSUE TITLE
A deletion task was created, but it doesn't seem to have been executed. The document still exists.

### ISSUE THREAD

**Issue by yanlong-li** [quickwit-oss/quickwit#5050]
### delete
/api/v1/test_article/delete-tasks

<<<
{
  "query": "*"
}

>>>

{
    "create_timestamp": 1717058008,
    "opstamp": 5,
    "delete_query": {
      "index_uid": "test_article:01HZ47644K4ZFWMRQK25A31627",
      "query_ast": "{\"type\":\"match_all\"}"
    }
  }

### query
/api/v1/test_article/search?query=*
>>>
{
  "num_hits": 1,
  "hits": [
   ...
  ],
  "elapsed_time_micros": 1851,
  "errors": []
}

**Comment by trinity-1686a** [comment]
Deletion has [limitations](https://quickwit.io/docs/overview/concepts/deletes#pitfalls) such as applying only to mature splits and being executed asynchronously. Can you confirm that this isn't what happens?

Note that if you want to clear the entire index, `PUT /api/v1/indexes/{index_id}/clear` is more efficient than a delete task deleting everything.
