### ISSUE TITLE
Field "parent_span_id" is not indexed in otel traces index 

### ISSUE THREAD

**Issue by Sh4d1** [quickwit-oss/quickwit#5122]
**Describe the bug**
I get a 500 when filtering on the `parent_span_id`:
```
Error: { "message": "internal error: `(internal error: `tantivy error: Schema error: 'Field \"parent_span_id\" is not indexed.'`, split_id: 01J08YXJCERKN0JK3BYWNPB8A0), (internal error: [...]
```

**Steps to reproduce (if applicable)**

1. Create an otel index for traces
2. Filter on the parent_span_id field

**Expected behavior**
A working search

**Configuration:**
I'm running the helm chart, version 0.5.15

**Comment by rdettai** [comment]
Hi Patrik! Could you tell us a bit more about your usecase. In general, it is not necessary to have indices on spans because when you know a `span_id` you usually also know its `trace_id`, so you can query an entire trace by its id then perform the span search locally.

**Comment by Sh4d1** [comment]
@rdettai hey! Yeah, it's to perform some listing on the traces (ie list only the top level traces, and do some operation of them), not sure I'm clear!

**Comment by rdettai** [comment]
Are you saying you are expecting a span tree that has multiple trace ids?

**Comment by Sh4d1** [comment]
Nop, but the trace ID is on all the spans, so I can't query all root IDs. What I'm doing is kinda a log dashboard, but with top level spans

**Comment by rdettai** [comment]
Ok, understood. Using the presence or absence of the `parent_span_id` is your way of getting the root spans, right? I think the usual way to do this is by using `span_name`. Is that not possible for you?

**Comment by Sh4d1** [comment]
It could be possible but not that practical! But I ended up rolling my own index (yay retention 😄), so I'm not sure it should be needed as a default!

**Comment by rdettai** [comment]
I'll close this then. Let's see if this is requested again!
