### ISSUE TITLE
Number of vCPUs detection on k8s.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5133]
Need to investigate: The code detecting the number of vCPUs may not be correct in cgroups.

**Comment by trinity-1686a** [comment]
I reviewed some changes for which i had doubts at some point. We use [`std::thread::available_parallelism`](https://doc.rust-lang.org/std/thread/fn.available_parallelism.html). It's documentation made me feel like it was doing the best it can in that regard (though the best might not be enough?)
> On Linux:
> -    It may overcount the amount of parallelism available when limited by a process-wide affinity mask or cgroup quotas and sched_getaffinity() or cgroup fs can’t be queried, e.g. due to sandboxing.

**Comment by fulmicoton** [comment]
That's my impression too. The code misbehaving was observed on a customer on GKE which is why I opened this ticket.

I just tested 0.8.0, 0.8.1 and main. The detected value was the "limit" supplied to k8s.
