### ISSUE TITLE
Date time format is incompatible with elasticsearch/opensearch date format.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5228]
We introduced the support of date time format in range queries, unfortunately the date time format we support is not that of elastic.

Elasticsearch expect a `yyyymmdd` format  while quickwit expected strptime (`%Y-%M-%d`)
For instance the following pattern is correct for elasticsearch
```yyyy|MM|dd 'T'HH:mm:ss.SSSSSS'Z'```

but incorrect for quickwit's range filter as illustrated by https://github.com/quickwit-oss/quickwit/pull/5227

related story: https://github.com/quickwit-oss/quickwit/issues/5109

**Comment by kuzaxak** [comment]
Implemented in https://github.com/quickwit-oss/quickwit/pull/5462
