### ISSUE TITLE
flaky test spotted locally: test_delete_shard_on_eof

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5286]
---- control_plane::tests::test_delete_shard_on_eof stdout ----
thread 'control_plane::tests::test_delete_shard_on_eof' panicked at quickwit-control-plane/src/control_plane.rs:1702:13:
assertion failed: apply_plan_request.indexing_tasks.is_empty()

**Comment by guilload** [comment]
Duplicate of [#4699](https://github.com/quickwit-oss/quickwit/issues/4699).
