### ISSUE TITLE
Quickwit Should Ignore Field queries with a mismatch type

### ISSUE THREAD

**Issue by esatterwhite** [quickwit-oss/quickwit#5302]
**Describe the bug**
When querying against multiple fields, when field has a defined index mapping type, querying for a field that does not exist creates an error. For example, querying for a nested field against a text field will result in an error

```txl
invalid query: field does not exist: `<field>`
```

**Steps to reproduce (if applicable)**

1. define an index with a text field named `_app` as a text field
```json5
    , {
        name: '_app'
      , type: 'text'
      , tokenizer: 'raw_lowercase'
      , fast: {
          normalizer: 'lowercase'
        }
      }
```
2. insert a document with an object field`{o_app: {name: 'test-app'}}`
3. query for `test-app` against `_app.name` or `o_app.name`

```json5
{
  query: {
    bool: {
      must: [
        { range: { _ts: { gte: 1722876383510 } } },
        { range: { _ts: { lt: 1722879983744 } } },
        {
          query_string: {
            fields: [ '_app.name', 'o_app.name' ],
            query: 'test-app',
            lenient: true
          }
        }
      ],
      should: null
    }
  }
}
```

**Expected behavior**
Quickwit should ignore the case when a field doesn't exist and query against the fields that do.

**Configuration:**

```json5
    "build_info": {
      "build_date": "2024-07-31T06:15:28Z",
      "build_profile": "release",
      "build_target": "x86_64-unknown-linux-gnu",
      "cargo_pkg_version": "0.8.0",
      "commit_date": "2024-07-31T05:41:46Z",
      "commit_hash": "c263c8d8cfe4c154f8b21a22c5d2840b928369b8",
      "commit_short_hash": "c263c8d",
      "commit_tags": [
        "qw-airmail-20240731"
      ],
      "version": "0.8.0-nightly"
    },
```

**Comment by PSeitz** [comment]
ES behavior is to ignore not existing fields

**Comment by esatterwhite** [comment]
The `lenient` option on the query could be respected, and the strict behavior can be the default

**Comment by PSeitz** [comment]
Not existing fields also get ignored without the `lenient`

**Comment by esatterwhite** [comment]
Right, that's what I mean. The default behavior could be as it is today. The lenient option set to true would ignore the non existent fields.

**Comment by PSeitz** [comment]
What I meant was with `lenient: false` missing fields also never cause errors
