### ISSUE TITLE
Make sure the janitor does not spam the metastore too much

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5353]
In https://github.com/quickwit-oss/quickwit/pull/5346 we have spotted that our implementation of delete index was too aggressive.

For airmail, their internal job deleting a large number of indexes ended up hammering the metastore, hence disrupting indexing.

We want to make sure that we don't have a similar pattern in the janitor. In particular, when running the retention policy.

**Comment by fulmicoton** [comment]
(@trinity-1686a maybe there is not problem... If so, please just comment here and close the ticket)

**Comment by trinity-1686a** [comment]
we also seem to execute all GC calls at once, but scoping them by index, which causes many consecutive call, and much more often (every 10 or so minutes). That's something that can also be improved upon
