### ISSUE TITLE
Put an object to AWS S3 with server-side encryption

### ISSUE THREAD

**Issue by samoii** [quickwit-oss/quickwit#5399]
**Is your feature request related to a problem? Please describe.**
Currently, Quickwit doesn't upload objects to AWS S3 with the server-side encryption required by the security baseline on AWS.

**Comment by fulmicoton** [comment]
Since 2023 By default, SSE is enabled on all buckets on S3.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingServerSideEncryption.html

I don't think anything needs to be done on Quickwit side. Closing the issue for the moment, but please comment if this is not what you meant.
