### ISSUE TITLE
Lambda searcher: default metastore_uri breaks search

### ISSUE THREAD

**Issue by psanford** [quickwit-oss/quickwit#5401]
**Describe the bug**

I'm setting up quickwit in lambda for the first time. I loaded some data with the indexer but when I invoked the search lambda I would get back an `index not found` error. 

After I invoked the searcher I noticed a new file in my s3 bucket that had an unusual looking path:
```
s3://psanford-quickwit-search/index}#polling_interval=${QW_LAMBDA_SEARCHER_METASTORE_POLLING_INTERVAL_SECONDS:-60s/manifest.json
```

Note the improperly expanded variable literals.

This appeared to be coming from [searcher/environment.rs](https://github.com/quickwit-oss/quickwit/blob/fc5ef169c874be946dcd56616892cd892b0b5b52/quickwit/quickwit-lambda/src/searcher/environment.rs#L23).

I suspected that this might be related to my issue so I updated the code to:
```
metastore_uri: s3://${QW_LAMBDA_METASTORE_BUCKET}/index#polling_interval=60s
```

After deploying this change, the quickwit searcher lambda was able to find my index and return search results.

**Comment by rdettai** [comment]
The interpolation string looks right, but I also just noticed the error in our internal CI.
