### ISSUE TITLE
Make GC split deletion more robust

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5405]
Right now, GC stops as soon as it encounters and error when deleting splits.

This is problematic, because in presence of a 
- non transient error
-  transient error with a `probability > 1 / (number of splits to delete at each GC)`
we will end up with a divergent behavior.

**Comment by trinity-1686a** [comment]
One possibility is to count how many errors we got, and fetch with `OFFSET <error_count>`. Assuming the order is stable, this would just skip over the errored splits for the rest of the GC run. If the order is not stable, we would eventually reach error_count = num_splits and stop the gc run, while having tried most splits
