### ISSUE TITLE
Can not specify an index id on the http otel api

### ISSUE THREAD

**Issue by imphilippesimo** [quickwit-oss/quickwit#5413]
**Is your feature request related to a problem? Please describe.**
I am building a Java service to index Opentelemetry Logs into quickwit. The Java service is receiving logs from the OTel collector. (We need that extra Java layer to add business logic to it)

I use HttpUrlConnection to send Protobuf over HTTP. 
I found via the discord that the endpoint to use was : `/api/v1/otlp/v1/logs` 
Unfortunately, the logs are trying to be indexed in the default otel index: `otel-logs-v0_7`

**Describe the solution you'd like**
When setting the header `qw-otel-logs-index:my_custom_index`, quickwit should use my_custom_index when sending logs with protobuf over http

**Describe alternatives you've considered**
I try to define a custom index using `qw-otel-logs-index` but to no avail.

**Comment by trinity-1686a** [comment]
keeping open for now as we want to support getting the index from http header too
