### ISSUE TITLE
Support Pulsar TLS endpoints

### ISSUE THREAD

**Issue by miton18** [quickwit-oss/quickwit#5422]
**Is your feature request related to a problem? Please describe.**
Quickwit cannot connect to Pulsar broker which use TLS.

https://github.com/quickwit-oss/quickwit/blob/d142f59b8d26edeae699ab79bdd20d3077061ca0/quickwit/quickwit-config/src/source_config/mod.rs#L484

**Describe the solution you'd like**
Allow `pulsar+ssl://` URL scheme

**Describe alternatives you've considered**
-
**Additional context**

**Comment by guilload** [comment]
Closed via #5470.
