### ISSUE TITLE
Ingest v2 returning 503 service unavailable

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5545]
Ingest v2 seems to return a 503: ingest service is unavailable (no shards available)
error when trying to ingest with the CLI.

It seems like a recent change.
We need to check if this change is justified, in which case, we need to fix the client, or if it is not and we need to fix the bug.

**Comment by fulmicoton** [comment]
The shard autocreation is working just fine. 
This happens when all of the shard are getting rate limited, so the through the different attempt, we end up trying to get a shard that is not rate limited and cannot find any such shard.

In that case we return a no shards available error, which in turn is converted as a 503 error.

**Comment by rdettai** [comment]
This is related to https://github.com/quickwit-oss/quickwit/pull/5566. It seems to me that the fix here is to map this error to a 429 (TOO_MANY_REQUESTS), no?

**Comment by fulmicoton** [comment]
Yes
