### ISSUE TITLE
S3 as a Distributed Metadata Store

### ISSUE THREAD

**Issue by snac21** [quickwit-oss/quickwit#5554]
Description:
In the "Architecture" section, it states that in a clustered deployment, the metastore is typically a traditional RDBMS like PostgreSQL, which is the only supported option today. 

However, in the "Distributed search on AWS S3" section, the metastore_uri is set to S3. 
This raises the question: Is S3 also capable of being used as a distributed metadata store?

https://quickwit.io/docs/overview/architecture
https://quickwit.io/docs/get-started/tutorials/tutorial-hdfs-logs-distributed-search-aws-s3

**Comment by fulmicoton** [comment]
S3 can be used as a metastore, but if you use it, you are required to ahve only one metastore service in your cluster (making it a SPOF)
