### ISSUE TITLE
Needless change in affinity function

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#5576]
Rust changed the endianness of the IP address internal representation.

This has an impact on its "hash", which in turn has an impact on our affinity function.

https://github.com/rust-lang/rust/commit/fce1decc3c6508aa72f590d024e583dd5c0cf04d

As spotted and fixed by @trinity-1686a   in https://github.com/quickwit-oss/quickwit/pull/5564

The change is impactful for companies running quickwit with a large cache and wanting to upgrade.
We need to make sure our affinity function in 0.9 is the same as in 0.8.

**Comment by fulmicoton** [comment]
Actually I don't understand how https://github.com/rust-lang/rust/commit/fce1decc3c6508aa72f590d024e583dd5c0cf04d would make a difference on most little endian (pretty much everything) arch. I assume the problem is coming from a different commit.

**Comment by trinity-1686a** [comment]
there are two related commits:
- https://github.com/rust-lang/rust/commit/ba620344301aaa3b2733575a0696cdfd877edbdf changed how hash of ip are computed (from array/slice of u8 to a single u32)
- https://github.com/rust-lang/rust/commit/fce1decc3c6508aa72f590d024e583dd5c0cf04d made the hash slightly faster on big endian at the cost of being platform dependent (we only support little endian, so it has little impact on us)
