### ISSUE TITLE
Hotcache Size

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#588]
## Hotcache
Ideally we cache the hotcache for every split available on an incoming request. This is done in order to reduce one roundtrip to s3 and enable faster searches. We may have thousands of splits and their hotcaches on one leaf, so hotcache size may become relevant to **save RAM**.

## Size

With the [`inspect-split`](https://github.com/quickwit-inc/quickwit/pull/570) command I did check the hotcache contents of a wikipedia-index (216.91 KB, 500MB raw data) and hdfs-log (468.66 KB, 1GB raw data). See Output for more details. I tried to produce single splits  to have something reproducible.

The content of the hotcache consists mainly of the skip-index in the tantivy doc-store. 

## Doc Store Experiment
I did a small experiment on the wikipedia index, by replacing the skip-index with two blockwise linearinterpolation indexes (docids, and byte offset).

Index | Size in one Segment
------------ | -------------
|Skipindex | 130302|
|Linearinterpolation|  84950|
|Linearinterpolation + Fixed Blocksize|  ~65000|

With flexible blocksizes in the docstore (optimizing doc store chunks in terms of num documents first then size), this can be lowered to around 65K. The compression may be higher in cases like hdfslog, since it is more consistent. 

So there should be some slack to **reduce hotcache size by 50%** if required.

## Output

Wikipedia
```
"4bfe072e669147cfba011c4433ea8f60.fast" 99 B
"4bfe072e669147cfba011c4433ea8f60.fieldnorm" 900.12 KB
"4bfe072e669147cfba011c4433ea8f60.idx" 47.45 MB
"4bfe072e669147cfba011c4433ea8f60.pos" 111 B
"4bfe072e669147cfba011c4433ea8f60.store" 381.75 MB
"4bfe072e669147cfba011c4433ea8f60.term" 7.22 MB
"hotcache" 216.91 KB
"meta.json" 1.12 KB
HotCache ".managed.json" 258 B
HotCache "4bfe072e669147cfba011c4433ea8f60.fast" 99 B
HotCache "4bfe072e669147cfba011c4433ea8f60.fieldnorm" 121 B
HotCache "4bfe072e669147cfba011c4433ea8f60.idx" 129 B
HotCache "4bfe072e669147cfba011c4433ea8f60.pos" 111 B
HotCache "4bfe072e669147cfba011c4433ea8f60.store" 201.55 KB
HotCache "4bfe072e669147cfba011c4433ea8f60.term" 11.96 KB
HotCache "meta.json" 1.12 KB
```

hdfs
```
"5a94ba03c09c40b1b64418f25f149f48.fast" 99 B
"5a94ba03c09c40b1b64418f25f149f48.fieldnorm" 9.00 MB
"5a94ba03c09c40b1b64418f25f149f48.idx" 53.08 MB
"5a94ba03c09c40b1b64418f25f149f48.pos" 111 B
"5a94ba03c09c40b1b64418f25f149f48.store" 220.21 MB
"5a94ba03c09c40b1b64418f25f149f48.term" 6.75 MB
"hotcache" 468.66 KB
"meta.json" 994 B
HotCache ".managed.json" 258 B
HotCache "5a94ba03c09c40b1b64418f25f149f48.fast" 99 B
HotCache "5a94ba03c09c40b1b64418f25f149f48.fieldnorm" 123 B
HotCache "5a94ba03c09c40b1b64418f25f149f48.idx" 130 B
HotCache "5a94ba03c09c40b1b64418f25f149f48.pos" 111 B
HotCache "5a94ba03c09c40b1b64418f25f149f48.store" 456.53 KB
HotCache "5a94ba03c09c40b1b64418f25f149f48.term" 8.77 KB
HotCache "meta.json" 994 B
```

**Comment by fmassot** [comment]
It sounds like it is something more related to tantivy, is it?

It seems linear interpolation seems good for the doc store. Are there any downside of using linear interpolation instead of a skip index?

**Comment by PSeitz** [comment]
I didn't test the creation and search performance. I think get requests could be slower, but I'm not sure this would matter at all since it is probably dwarfed by decompression of the doc store blocks.

**Comment by PSeitz** [comment]
With the larger blocksize, the skip index is much smaller.  There are no major gains by changing the format
random HDFS split
```
 Files in Hotcache
+--------------------------------------------+----------+
|                 File Name                  |   Size   |
+--------------------------------------------+----------+
| .managed.json                              | 258 B    |
+--------------------------------------------+----------+
| e61abb9fa5254271abab19a8db09e00a.fast      | 104 B    |
+--------------------------------------------+----------+
| e61abb9fa5254271abab19a8db09e00a.fieldnorm | 123 B    |
+--------------------------------------------+----------+
| e61abb9fa5254271abab19a8db09e00a.idx       | 163 B    |
+--------------------------------------------+----------+
| e61abb9fa5254271abab19a8db09e00a.pos       | 126 B    |
+--------------------------------------------+----------+
| e61abb9fa5254271abab19a8db09e00a.store     | 14.11 KB |
+--------------------------------------------+----------+
| e61abb9fa5254271abab19a8db09e00a.term      | 26.77 KB |
+--------------------------------------------+----------+
| meta.json                                  | 1.28 KB  |
+--------------------------------------------+----------+
```

**Comment by fulmicoton** [comment]
I guess we can close the ticket then.
