### ISSUE TITLE
Consistent packaging, uploading and publishing for a demux operation

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#643]
The demuxer will produced `N` splits to replace `P` old splits. these splits will need to be part of the same publish operation that will happen once we know that the new splits are uploaded.

## Solution 1: modify the packager and uploader to package / upload a list of split
Cons: break the simple logic of operating on one split.

## Solution 2: send a one shot from demuxer/merger/indexer to the publisher. The publisher will wait until it receives the operation.
Cons: the demuxer/merger/indexer will wait for package and upload and do nothing during this period.

To avoid that, we can create a new actor that will handle the coordination between package / upload and publish. This actor will receiver an operation, will wait until all splits are uploaded and then will send a message to the publisher.

**Comment by fulmicoton** [comment]
ok  then.
