### ISSUE TITLE
Max retry attemps too high on s3 storage

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#690]
Currently we have `MAX_RETRY_ATTEMPTS = 30` which seems way too high.

I suggest to put the max retry at 3. This is the default for the cli: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html#cli-usage-retries-modes-standard.title

**Comment by fulmicoton** [comment]
Can you comment on the reopen @fmassot

**Comment by guilload** [comment]
After discussing offline with @fmassot, the issue appears much more complex than just tweaking the retry parameters of the S3 storage. So, closing in favor of #1488.
