### ISSUE TITLE
Repeat query in syntax error 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#748]
When there is a syntax error in the query parser, one important context is the query itself.

Since we pass it via an URL, it is not uncommon to mess up with the URL encoding. 
If Quickwit repeated the query it was trying to parse  in the error, that could help spot trivial URL encoding errors very fast.

**Comment by PSeitz** [comment]
Fixed via https://github.com/quickwit-oss/quickwit/pull/1335
