### ISSUE TITLE
`FileSource` does not support file URIs

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#854]
URIs such as `file:///<path to JSON file>` fail. This has to do with calling `std::fs::canonicalize` on the URI.

**Comment by evanxg852000** [comment]
@guilload I think the need for `Uri` type is now evident as you suggested.
all paths from the cli args should be extracted as `Uri` then anyone would call the methods:
-  `Uri::protocol()`  -> returns the protocol
-  `Uri::cannicalized_path()`   -> returns the `std::fs::canonicalize` path 
- `Uri::normalized_path()`   -> returns the `normalize_path` helper path 

What do you think?

**Comment by guilload** [comment]
I agree with you; this is when the `Uri` would come in very handy. Regarding the API, a Uri should always be normalized so I'm not sure `canonicalized_path()` and `normalized_path()` make sense. Let's take this conversation to the Uri issue: #834.

**Comment by fmassot** [comment]
I think we can close this one, I let you do that @guilload @evanxg852000

**Comment by fulmicoton** [comment]
@evanxg852000 ? Can we close?
