### ISSUE TITLE
Add definitions of new concepts in architecture doc page

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#874]
- Checkpoint
- Split store
- Data source
- Search stream

**Comment by fulmicoton** [comment]
Partially done

**Comment by PSeitz** [comment]
Everything seems to be covered except search streams and I'm not sure if this requires an own chapter in the architecture page

**Comment by fulmicoton** [comment]
Maybe we should replace the distirbuted queue section by a source section, and detail the existing options with their semantics, pros and cons.

**Comment by PSeitz** [comment]
I wrote something here: https://github.com/quickwit-oss/quickwit/pull/1398
Although not too much details, since I think this should be better places in the source docs (?)

**Comment by fulmicoton** [comment]
I think we can close this at the moment.
