### ISSUE TITLE
Migrate from rusoto to aws-sdk-rust

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#885]
`aws-sdk-rust` seems pretty stable (at least for s3) and I think we could move to the official aws rust SDK after the 0.2 release: https://github.com/awslabs/aws-sdk-rust

See these comments: https://www.reddit.com/r/rust/comments/r7icyz/comment/hn063uo/?utm_source=share&utm_medium=web2x&context=3

**Comment by fmassot** [comment]
One more reason to migrate, virtual-hosted style bucket are supported since this release https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-01-13 and won't be supported in rusoto.

**Comment by guilload** [comment]
Fixed via #3168.
