### ISSUE TITLE
Left rotate source table for the `quickwit source describe` command 

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#914]
The `quickwit source describe` command  outputs three tables:
- source table
- params table
- checkpoint table

The source table should be [left-rotated](https://github.com/zhiburt/tabled#Rotate) for a slicker display. However, when I tried to do so, I did not manage to get the content of the table properly left-aligned.

**Comment by infiniteregrets** [comment]
Hi, I have experimented with different alignments and formats but the output seems to be very off. For example, without PSQL
```
       +------+------------------+
       | Type |       file       |
+------+------+------------------+
 Source|  ID  | wikipedia-source |
+------+------+------------------+


           +-------+--------------------------------------+
           | Value | "/quickwit/wiki-articles-10000.json" |
+----------+-------+--------------------------------------+
 Parameters|  Key  |               filepath               |
+----------+-------+--------------------------------------+


           +--------------+
           |    Offset    |
+----------+--------------+
 Checkpoint| Partition ID |
+----------+--------------+
```
I would assume in this case we need dynamic tables as mentioned in the docs of the builder module https://docs.rs/tabled/latest/tabled/builder/struct.Builder.html
I think if I experiment a bit more, I might be able to figure out the correct way to display the data. However, I am new to rust and I can't seem to figure out the reason behind this unresolved import when I try to import the builder::Builder module. 

```rs
error[E0432]: unresolved import `tabled::builder`
  --> quickwit-cli/src/lib.rs:32:90
   |
32 | use tabled::{Alignment, Rotate, Header, Modify, Row, Full, Style, Table, Tabled, Indent, builder::Builder};
   |                                                                                          ^^^^^^^ could not find `builder` in `tabled`
   ```
  Would appreciate any help! Thank you!

**Comment by PSeitz** [comment]
Hi infiniteregrets, thanks for having a look at this.

Try to update tabled by setting `tabled = "0.5"` in Cargo.toml

Then it should match the docs you are looking at.

**Comment by infiniteregrets** [comment]
Thanks, that fixed the issue. I should have paid more attention. 

I have tried quite a few times now with different settings and it looks like the left rotation doesn't just come through, it is missing the headers. 

I think the default ASCII view is much better than the psql view:
ASCII:
```
 Source
+-------------------------+
|        ID        | Type |
+------------------+------+
| wikipedia-source | file |
+------------------+------+

 Parameters
+-------------------------------------------------+
|   Key    |                Value                 |
+----------+--------------------------------------+
| filepath | "/quickwit/wiki-articles-10000.json" |
+----------+--------------------------------------+

 Checkpoint
+-----------------------+
| Partition ID | Offset |
+--------------+--------+
```
PSQL:
```
Source                   |
-------------------------+
        ID        | Type
 wikipedia-source | file

Parameters                                       |
-------------------------------------------------+
   Key    |                Value
 filepath | "/quickwit/wiki-articles-10000.json"

Checkpoint             |
-----------------------+
 Partition ID | Offset
 ```
 Left rotation always gives incorrect output in all modes: 
 ```
 ╔╦══════╦══════════════════╗
║║ Type ║       file       ║
╠╬══════╬══════════════════╣
║Source ║ wikipedia-source ║
╚═══════╩══════════════════╩

╔═╦════════╦══════════════════════════════════════╗
║ ║ Value  ║ "/quickwit/wiki-articles-10000.json" ║
╠═╬════════╬══════════════════════════════════════╣
║Parameters║               filepath               ║
╚══════════╩══════════════════════════════════════╩

╔═╦════════╗
║ ║ Offset ║
╠═╬════════╣
║Checkpoint║
╚══════════╩
```
I think, left rotation even from the examples would make the results a bit hard to read for a user. I think sticking the simple ASCII mode is much sleek and nice making the results more separated and readabale. 
I can't really pin what is the issue, but I would believe it could be a bug in Tabled? Otherwise the examples in the manpage seem okay? 

If you like the ASCII mode, I can open a PR to change that. Sorry I couldn't really figure that left rotation, but if you have any suggestions for me to work on, please let me know! Thanks!

**Comment by fmassot** [comment]
@infiniteregrets thanks for your work.
Yes ASCII mode seems the best, you can open a PR for using it.
