### ISSUE TITLE
S3 LocalStack tests fail if no AWS credentials are set. 

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#944]
**Describe the bug**
S3 LocalStack tests fail if no AWS credentials are set. 

**Steps to reproduce (if applicable)**
1. Ensure AWS env variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are not set and `~/.aws/config` does not exist or is empty.
2. Run `make docker-compose-up` and `QUICKIT_ENV=local cargo test --all-features -- cli`

**Expected behavior**
The tests should pass.

We should set placeholder AWS keys for LocalStack tests or at least document this behavior for first-time contributors.

**Comment by fulmicoton** [comment]
`make test-all` seems to work.
