### ISSUE TITLE
Switch to POEM for the Rest API?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#989]
OpenAPI is nice but we ended up not using it because the edit yaml -> generate code
was actually a pain and was only supported by hyper.

poem seems to have great annotation based support for OpenAPI.
It might be worth giving it a try.
https://github.com/poem-web/poem/blob/master/poem-openapi/README.md

**Comment by sunli829** [comment]
That's a great idea, and I can help in any way I can. 😁

**Comment by fulmicoton** [comment]
@sunli829 Haha thanks for chiming it :).

We may have questions indeed. I gave poem, and especially poem-openapi a try this week end. I must say I was very happy with the result.

**Comment by sunli829** [comment]
Please feel free to contact me if you encounter any problems, I can solve them quickly. 😁

**Comment by fulmicoton** [comment]
sticking to warp at least for the momnet, upon judgement from @fmassot
